//! Required `.env` variable registry (contract "Required Env Variables").
//! Extracted from `config_schema_registry.rs` to stay under the monolith line cap.

use super::EnvVarSpec;

type RawEnvVar = (
    &'static str,
    bool,
    bool,
    Option<&'static str>,
    &'static str,
    bool,
    &'static str,
    &'static str,
);

// (name, required, secret, default, owner_crate, compose_usage, validation, description)
const RAW_ENV_VARS: &[RawEnvVar] = &[
    (
        "AXON_DATA_DIR",
        false,
        false,
        None,
        "axon-core",
        false,
        "path",
        "Bootstrap data-dir path override.",
    ),
    (
        "QDRANT_URL",
        true,
        false,
        Some("http://127.0.0.1:6333"),
        "axon-vectors",
        true,
        "url",
        "Vector store URL.",
    ),
    (
        "TEI_URL",
        true,
        false,
        None,
        "axon-embedding",
        true,
        "url",
        "Embedding provider URL.",
    ),
    (
        "AXON_CHROME_REMOTE_URL",
        false,
        false,
        None,
        "axon-adapters",
        true,
        "url",
        "Render provider (headless Chrome) URL.",
    ),
    (
        "AXON_HTTP_HOST",
        false,
        false,
        Some("127.0.0.1"),
        "axon-web",
        false,
        "host",
        "Unified server bind host.",
    ),
    (
        "AXON_HTTP_PORT",
        false,
        false,
        None,
        "axon-web",
        false,
        "port",
        "Unified server bind port.",
    ),
    (
        "AXON_PUBLIC_URL",
        false,
        false,
        None,
        "axon-web",
        false,
        "url",
        "OAuth/public URL.",
    ),
    (
        "AXON_HTTP_TOKEN",
        false,
        true,
        None,
        "axon-web",
        false,
        "none",
        "Static bearer auth token.",
    ),
    (
        "AXON_AUTH_MODE",
        false,
        false,
        None,
        "axon-authz",
        false,
        "enum",
        "One of none, bearer, or oauth.",
    ),
    (
        "AXON_GOOGLE_CLIENT_ID",
        false,
        false,
        None,
        "axon-authz",
        false,
        "none",
        "OAuth client id.",
    ),
    (
        "AXON_GOOGLE_CLIENT_SECRET",
        false,
        true,
        None,
        "axon-authz",
        false,
        "none",
        "OAuth client secret.",
    ),
    (
        "GITHUB_TOKEN",
        false,
        true,
        None,
        "axon-adapters",
        false,
        "none",
        "Private/rate-limited GitHub access.",
    ),
    (
        "GITLAB_TOKEN",
        false,
        true,
        None,
        "axon-adapters",
        false,
        "none",
        "Private/rate-limited GitLab access.",
    ),
    (
        "GITEA_TOKEN",
        false,
        true,
        None,
        "axon-adapters",
        false,
        "none",
        "Private/rate-limited Gitea/Forgejo access.",
    ),
    (
        "REDDIT_CLIENT_ID",
        false,
        false,
        None,
        "axon-adapters",
        false,
        "none",
        "Reddit source client id.",
    ),
    (
        "REDDIT_CLIENT_SECRET",
        false,
        true,
        None,
        "axon-adapters",
        false,
        "none",
        "Reddit source client secret.",
    ),
    (
        "TAVILY_API_KEY",
        false,
        true,
        None,
        "axon-adapters",
        false,
        "none",
        "Search fallback API key.",
    ),
    (
        "AXON_SEARXNG_URL",
        false,
        false,
        None,
        "axon-adapters",
        false,
        "url",
        "Self-hosted SearXNG search provider URL.",
    ),
    (
        "AXON_OPENAI_API_KEY",
        false,
        true,
        None,
        "axon-llm",
        false,
        "none",
        "OpenAI-compatible LLM backend API key.",
    ),
    (
        "AXON_OPENAI_BASE_URL",
        false,
        false,
        None,
        "axon-llm",
        false,
        "url",
        "OpenAI-compatible LLM backend base URL.",
    ),
    (
        "AXON_CODEX_HOME",
        false,
        false,
        None,
        "axon-llm",
        false,
        "path",
        "Codex app-server provider home override.",
    ),
];

pub fn env_var_registry() -> Vec<EnvVarSpec> {
    RAW_ENV_VARS
        .iter()
        .map(
            |&(
                name,
                required,
                secret,
                default,
                owner_crate,
                compose_usage,
                validation,
                description,
            )| {
                EnvVarSpec {
                    name,
                    required,
                    secret,
                    default,
                    owner_crate,
                    compose_usage,
                    validation,
                    example_allowed: !secret,
                    description,
                }
            },
        )
        .collect()
}
