//! Adapter spec matrix — one entry per source family.

use axon_api::source::{SourceKind, SourceScope};

use crate::family_matrix::SourceFamilyMatrix;
use crate::spec::{ParserFamily, SourceAdapterSpec, SourceFamily};

use super::scopes_content::{FEED_SCOPES, GIT_SCOPES, LOCAL_SCOPES, UPLOAD_SCOPES, WEB_SCOPES};
use super::scopes_tooling::{
    MCP_SCOPES, MEMORY_SCOPES, NO_CREDENTIALS, REDDIT_SCOPES, REGISTRY_SCOPES, SESSIONS_SCOPES,
    TOOL_SCOPES, YOUTUBE_SCOPES,
};

pub(super) const MATRIX: &[SourceAdapterSpec] = &[
    SourceAdapterSpec {
        family: SourceFamily::Local,
        adapter: "local",
        version: "1",
        source_kinds: &[SourceKind::Local],
        vector_namespace: "source:local",
        supported_schemes: &["file"],
        shorthand_patterns: &["./path", "../path", "/absolute/path", "~/<path>"],
        default_scope: SourceScope::File,
        scopes: LOCAL_SCOPES,
        credential_requirements: NO_CREDENTIALS,
        option_schema: "local-source-options/v1",
        parser_families: &[
            ParserFamily::Markdown,
            ParserFamily::Code,
            ParserFamily::Manifest,
        ],
        metadata_families: &["local", "filesystem", "security"],
        watch_supported: true,
        refresh_supported: true,
        may_access_local_paths: true,
        may_perform_network_fetches: false,
        may_call_render_provider: false,
        may_execute_tools: false,
        is_source_adapter: true,
        degraded_modes: &[
            "permission-denied",
            "file-too-large",
            "symlink-outside-root",
        ],
        required_graph_fact_kinds: &["document", "filesystem_path"],
        optional_graph_fact_kinds: &["symbol", "dependency"],
    },
    SourceAdapterSpec {
        family: SourceFamily::Upload,
        adapter: "upload",
        version: "1",
        source_kinds: &[SourceKind::Upload, SourceKind::Session, SourceKind::Local],
        vector_namespace: "source:upload",
        supported_schemes: &["upload"],
        shorthand_patterns: &["upload:<staged-id>"],
        default_scope: SourceScope::File,
        scopes: UPLOAD_SCOPES,
        credential_requirements: NO_CREDENTIALS,
        option_schema: "upload-source-options/v1",
        parser_families: &[
            ParserFamily::Markdown,
            ParserFamily::Code,
            ParserFamily::Manifest,
            ParserFamily::Session,
        ],
        metadata_families: &["upload", "filesystem", "security"],
        watch_supported: true,
        refresh_supported: true,
        may_access_local_paths: true,
        may_perform_network_fetches: false,
        may_call_render_provider: false,
        may_execute_tools: false,
        // `UploadSourceAdapter` is real and fully tested (`upload.rs` /
        // `upload_tests.rs`) via the `SourceAdapter` trait directly. This is
        // kept `false` only because `fixture_tests.rs` requires a matching
        // fixture pack in `crates/axon-parse/fixtures`,
        // `crates/axon-graph/fixtures`, and
        // `crates/axon-vectors/tests/fixtures/payload` for every
        // `is_source_adapter = true` row, and this workstream's territory is
        // `crates/axon-adapters/**` only. Flip to `true` and add those three
        // fixtures as a follow-up.
        is_source_adapter: false,
        degraded_modes: &[
            "permission-denied",
            "file-too-large",
            "symlink-outside-root",
        ],
        required_graph_fact_kinds: &["document", "filesystem_path"],
        optional_graph_fact_kinds: &["symbol", "dependency"],
    },
    SourceAdapterSpec {
        family: SourceFamily::Git,
        adapter: "git",
        version: "1",
        source_kinds: &[SourceKind::Git],
        vector_namespace: "source:git",
        supported_schemes: &["git", "ssh", "http", "https"],
        shorthand_patterns: &["github:owner/repo", "gitlab:owner/repo", "owner/repo"],
        default_scope: SourceScope::Repo,
        scopes: GIT_SCOPES,
        credential_requirements: NO_CREDENTIALS,
        option_schema: "git-source-options/v1",
        parser_families: &[
            ParserFamily::Code,
            ParserFamily::Manifest,
            ParserFamily::Markdown,
        ],
        metadata_families: &["git", "repository", "security"],
        watch_supported: true,
        refresh_supported: true,
        may_access_local_paths: true,
        may_perform_network_fetches: true,
        may_call_render_provider: false,
        may_execute_tools: false,
        is_source_adapter: true,
        degraded_modes: &["shallow-clone", "missing-provider-token", "rate-limited"],
        required_graph_fact_kinds: &["repository", "revision"],
        optional_graph_fact_kinds: &["symbol", "dependency", "release"],
    },
    SourceAdapterSpec {
        family: SourceFamily::Web,
        adapter: "web",
        version: "1",
        source_kinds: &[SourceKind::Web],
        vector_namespace: "source:web",
        supported_schemes: &["http", "https"],
        shorthand_patterns: &["https://example.com/path"],
        default_scope: SourceScope::Page,
        scopes: WEB_SCOPES,
        credential_requirements: NO_CREDENTIALS,
        option_schema: "web-source-options/v1",
        parser_families: &[ParserFamily::Html, ParserFamily::Markdown],
        metadata_families: &["web", "http", "security"],
        watch_supported: true,
        refresh_supported: true,
        may_access_local_paths: false,
        may_perform_network_fetches: true,
        may_call_render_provider: true,
        may_execute_tools: false,
        is_source_adapter: true,
        degraded_modes: &["http-only", "render-unavailable", "thin-content"],
        required_graph_fact_kinds: &["web_page", "canonical_url"],
        optional_graph_fact_kinds: &["link", "structured_data"],
    },
    // `deepwiki` composes onto the same prepared-content acquisition model as
    // `web`/`git` (this crate never calls live network APIs directly — see
    // module docs on `web.rs`/`registry_sources.rs`), so a real acquisition
    // path is feasible without a new network client. It is declared here as
    // the target catalog entry from `adapter-scopes.md`; it does not yet have
    // its own concrete `SourceAdapter` struct or provider-kind-based routing
    // onto `web`/`git` — that wiring is a follow-up (routing lives outside
    // this crate's territory).
    SourceAdapterSpec {
        family: SourceFamily::Deepwiki,
        adapter: "deepwiki",
        version: "1",
        source_kinds: &[SourceKind::Web, SourceKind::Git],
        vector_namespace: "source:deepwiki",
        supported_schemes: &["https"],
        shorthand_patterns: &["deepwiki:owner/repo", "https://deepwiki.com/owner/repo"],
        default_scope: SourceScope::Repo,
        scopes: GIT_SCOPES,
        credential_requirements: NO_CREDENTIALS,
        option_schema: "git-source-options/v1",
        parser_families: &[ParserFamily::Markdown, ParserFamily::Html],
        metadata_families: &["deepwiki", "web", "git", "security"],
        watch_supported: true,
        refresh_supported: true,
        may_access_local_paths: false,
        may_perform_network_fetches: true,
        may_call_render_provider: true,
        may_execute_tools: false,
        // No concrete `SourceAdapter` struct exists for `deepwiki` yet (see
        // comment above) and `fixture_tests.rs` requires a matching fixture
        // pack in `crates/axon-parse`/`crates/axon-graph`/
        // `crates/axon-vectors` for every `is_source_adapter = true` row —
        // outside this crate's `crates/axon-adapters/**` territory. Flip to
        // `true` once the adapter struct + those fixtures land.
        is_source_adapter: false,
        degraded_modes: &["http-only", "render-unavailable", "rate-limited"],
        required_graph_fact_kinds: &["repository"],
        optional_graph_fact_kinds: &["web_page", "link"],
    },
    SourceAdapterSpec {
        family: SourceFamily::Feed,
        adapter: "feed",
        version: "1",
        source_kinds: &[SourceKind::Feed],
        vector_namespace: "source:feed",
        supported_schemes: &["http", "https", "feed", "rss", "atom"],
        shorthand_patterns: &["feed:https://example.com/feed.xml", "rss:<url>"],
        default_scope: SourceScope::Feed,
        scopes: FEED_SCOPES,
        credential_requirements: NO_CREDENTIALS,
        option_schema: "feed-source-options/v1",
        parser_families: &[
            ParserFamily::Feed,
            ParserFamily::Html,
            ParserFamily::Markdown,
        ],
        metadata_families: &["feed", "web", "security"],
        watch_supported: true,
        refresh_supported: true,
        may_access_local_paths: false,
        may_perform_network_fetches: true,
        may_call_render_provider: false,
        may_execute_tools: false,
        is_source_adapter: true,
        degraded_modes: &["malformed-entry", "linked-page-unavailable", "rate-limited"],
        required_graph_fact_kinds: &["feed", "feed_entry"],
        optional_graph_fact_kinds: &["author", "link"],
    },
    SourceAdapterSpec {
        family: SourceFamily::Youtube,
        adapter: "youtube",
        version: "1",
        source_kinds: &[SourceKind::Youtube],
        vector_namespace: "source:youtube",
        supported_schemes: &["http", "https", "youtube", "youtu"],
        shorthand_patterns: &["youtube:<video-id>", "youtu.be/<video-id>"],
        default_scope: SourceScope::Video,
        scopes: YOUTUBE_SCOPES,
        credential_requirements: NO_CREDENTIALS,
        option_schema: "youtube-source-options/v1",
        parser_families: &[ParserFamily::Transcript],
        metadata_families: &["youtube", "video", "security"],
        watch_supported: true,
        refresh_supported: true,
        may_access_local_paths: false,
        may_perform_network_fetches: true,
        may_call_render_provider: false,
        may_execute_tools: false,
        is_source_adapter: true,
        degraded_modes: &["metadata-only", "transcript-unavailable", "rate-limited"],
        required_graph_fact_kinds: &["video"],
        optional_graph_fact_kinds: &["channel", "playlist", "transcript_segment"],
    },
    SourceAdapterSpec {
        family: SourceFamily::Reddit,
        adapter: "reddit",
        version: "1",
        source_kinds: &[SourceKind::Reddit],
        vector_namespace: "source:reddit",
        supported_schemes: &["http", "https", "reddit"],
        shorthand_patterns: &["r/<subreddit>", "reddit:<subreddit>", "reddit:<thread-url>"],
        default_scope: SourceScope::Thread,
        scopes: REDDIT_SCOPES,
        credential_requirements: NO_CREDENTIALS,
        option_schema: "reddit-source-options/v1",
        parser_families: &[ParserFamily::Markdown],
        metadata_families: &["reddit", "thread", "security"],
        watch_supported: true,
        refresh_supported: true,
        may_access_local_paths: false,
        may_perform_network_fetches: true,
        may_call_render_provider: false,
        may_execute_tools: false,
        is_source_adapter: true,
        degraded_modes: &[
            "public-json-unavailable",
            "comments-truncated",
            "rate-limited",
        ],
        required_graph_fact_kinds: &["thread", "comment"],
        optional_graph_fact_kinds: &["author", "subreddit"],
    },
    SourceAdapterSpec {
        family: SourceFamily::Sessions,
        adapter: "sessions",
        version: "1",
        source_kinds: &[SourceKind::Session],
        vector_namespace: "source:sessions",
        supported_schemes: &["session", "file"],
        shorthand_patterns: &[
            "session:claude:<path>",
            "session:codex:<path>",
            "session:gemini:<path>",
        ],
        default_scope: SourceScope::File,
        scopes: SESSIONS_SCOPES,
        credential_requirements: NO_CREDENTIALS,
        option_schema: "sessions-source-options/v1",
        parser_families: &[ParserFamily::Session],
        metadata_families: &["session", "agent", "security"],
        watch_supported: false,
        refresh_supported: true,
        may_access_local_paths: true,
        may_perform_network_fetches: false,
        may_call_render_provider: false,
        may_execute_tools: false,
        is_source_adapter: true,
        degraded_modes: &["unknown-export-format", "partial-turn", "redacted-secret"],
        required_graph_fact_kinds: &["session", "turn"],
        optional_graph_fact_kinds: &["tool_call", "artifact"],
    },
    SourceAdapterSpec {
        family: SourceFamily::Registry,
        adapter: "registry",
        version: "1",
        source_kinds: &[SourceKind::Registry],
        vector_namespace: "source:registry",
        // 13-ecosystem target from adapter-scopes.md's "Target Adapter
        // Registry" table. All 13 already have a real, feasible acquisition
        // path: `RegistrySourceAdapter` is ecosystem-agnostic — it reads a
        // prepared `RegistryDump` keyed by an arbitrary `registry: String`
        // (see `registry_sources/dump.rs`), so no ecosystem-specific client
        // code is needed here. Per-ecosystem *bridges* that fetch each
        // registry's live API into a `RegistryDump` are a follow-up outside
        // this crate (this crate never calls live registry APIs directly).
        supported_schemes: &[
            "pkg",
            "npm",
            "pypi",
            "crates",
            "docker",
            "maven",
            "nuget",
            "rubygems",
            "packagist",
            "hex",
            "pub",
            "terraform",
            "helm",
            "huggingface",
        ],
        shorthand_patterns: &[
            "pkg:npm/<name>",
            "pkg:pypi/<name>",
            "pkg:crates/<name>",
            "pkg:docker/<image>",
            "pkg:maven/<group>/<artifact>",
            "pkg:nuget/<name>",
            "pkg:rubygems/<name>",
            "pkg:packagist/<vendor>/<name>",
            "pkg:hex/<name>",
            "pkg:pub/<name>",
            "pkg:terraform/<namespace>/<name>/<provider>",
            "pkg:helm/<repository>/<chart>",
            "pkg:huggingface/<org>/<model>",
        ],
        default_scope: SourceScope::Package,
        scopes: REGISTRY_SCOPES,
        credential_requirements: NO_CREDENTIALS,
        option_schema: "registry-source-options/v1",
        parser_families: &[ParserFamily::PackageMetadata, ParserFamily::Manifest],
        metadata_families: &["package", "registry", "security"],
        watch_supported: true,
        refresh_supported: true,
        may_access_local_paths: false,
        may_perform_network_fetches: true,
        may_call_render_provider: false,
        may_execute_tools: false,
        is_source_adapter: true,
        degraded_modes: &["provider-unavailable", "version-yanked", "rate-limited"],
        required_graph_fact_kinds: &["package", "version"],
        optional_graph_fact_kinds: &["dependency", "release"],
    },
    SourceAdapterSpec {
        family: SourceFamily::CliTool,
        adapter: "cli_tool",
        version: "1",
        source_kinds: &[SourceKind::CliTool],
        vector_namespace: "source:cli_tool",
        supported_schemes: &["tool"],
        shorthand_patterns: &["tool:<command>"],
        default_scope: SourceScope::Tool,
        scopes: TOOL_SCOPES,
        credential_requirements: NO_CREDENTIALS,
        option_schema: "cli-tool-source-options/v1",
        parser_families: &[ParserFamily::ToolOutput],
        metadata_families: &["tool", "execution", "security"],
        watch_supported: false,
        refresh_supported: false,
        may_access_local_paths: true,
        may_perform_network_fetches: false,
        may_call_render_provider: false,
        may_execute_tools: true,
        // `CliToolSourceAdapter` (`cli_tool/adapter.rs`) is a real
        // `discover`/`acquire`/`normalize` implementation, but it is not a
        // production `index_source` adapter yet. Tool execution needs caller
        // scopes and configured allowlists threaded through the source
        // contract; until that exists, keep this out of generated "wired
        // source adapter" inventories.
        is_source_adapter: false,
        degraded_modes: &["metadata-only", "command-denied", "output-capped"],
        required_graph_fact_kinds: &["tool"],
        optional_graph_fact_kinds: &["tool_call", "artifact"],
    },
    SourceAdapterSpec {
        family: SourceFamily::McpTool,
        adapter: "mcp_tool",
        version: "1",
        source_kinds: &[SourceKind::McpTool],
        vector_namespace: "source:mcp_tool",
        supported_schemes: &["mcp"],
        shorthand_patterns: &["mcp://server/tool"],
        default_scope: SourceScope::Tool,
        scopes: MCP_SCOPES,
        credential_requirements: NO_CREDENTIALS,
        option_schema: "mcp-tool-source-options/v1",
        parser_families: &[ParserFamily::ApiSchema, ParserFamily::ToolOutput],
        metadata_families: &["mcp", "tool", "security"],
        watch_supported: false,
        refresh_supported: false,
        may_access_local_paths: false,
        may_perform_network_fetches: true,
        may_call_render_provider: false,
        may_execute_tools: true,
        // `McpToolSourceAdapter` (`mcp_tool/adapter.rs`) is a real
        // implementation, but not a production `index_source` adapter yet.
        // Keep it out of generated wired-adapter inventories until the
        // execute-scope/allowlist/caller threading contract exists.
        is_source_adapter: false,
        degraded_modes: &["schema-only", "tool-unavailable", "output-capped"],
        required_graph_fact_kinds: &["mcp_server", "mcp_tool"],
        optional_graph_fact_kinds: &["tool_call", "external_resource"],
    },
    SourceAdapterSpec {
        family: SourceFamily::MemoryIntegration,
        adapter: "memory",
        version: "1",
        source_kinds: &[SourceKind::Memory],
        vector_namespace: "memory",
        supported_schemes: &[],
        shorthand_patterns: &[],
        default_scope: SourceScope::Api,
        scopes: MEMORY_SCOPES,
        credential_requirements: NO_CREDENTIALS,
        option_schema: "memory-shared-pipeline-options/v1",
        parser_families: &[ParserFamily::Memory, ParserFamily::Markdown],
        metadata_families: &["memory", "retrieval", "graph"],
        watch_supported: false,
        refresh_supported: false,
        may_access_local_paths: false,
        may_perform_network_fetches: false,
        may_call_render_provider: false,
        may_execute_tools: false,
        is_source_adapter: false,
        degraded_modes: &["namespace-filtered", "superseded-memory"],
        required_graph_fact_kinds: &["memory_document"],
        optional_graph_fact_kinds: &["memory_link", "supersedes"],
    },
];

pub(super) fn source_family_matrix() -> SourceFamilyMatrix {
    MATRIX
}
