//! Media/registry/tooling-family scope tables (youtube/reddit/sessions/registry/cli_tool/mcp_tool/memory).

use axon_api::source::SourceScope;

use crate::spec::{SourceScopeCapability, scope_capability};

pub(crate) const YOUTUBE_SCOPES: &[SourceScopeCapability] = &[
    scope_capability(
        SourceScope::Video,
        true,
        "single video transcript/metadata",
        true,
        true,
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        "transcript",
        "youtube-source-options/v1",
        "transcript/v1",
        &["video"],
        &["channel", "playlist", "transcript_segment"],
        &["metadata-only", "transcript-unavailable", "rate-limited"],
    ),
    scope_capability(
        SourceScope::Playlist,
        true,
        "playlist items",
        true,
        true,
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        "video_candidate",
        "youtube-source-options/v1",
        "none",
        &[],
        &["video", "channel"],
        &["metadata-only", "rate-limited"],
    ),
    scope_capability(
        SourceScope::Channel,
        false,
        "channel hardening",
        false,
        true,
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        "video_candidate",
        "youtube-source-options/v1",
        "none",
        &[],
        &["video"],
        &["metadata-only", "rate-limited"],
    ),
];

pub(crate) const REDDIT_SCOPES: &[SourceScopeCapability] = &[
    scope_capability(
        SourceScope::Subreddit,
        true,
        "subreddit listing",
        true,
        true,
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        "thread_candidate",
        "reddit-source-options/v1",
        "none",
        &[],
        &["thread", "author"],
        &["public-json-unavailable", "rate-limited"],
    ),
    scope_capability(
        SourceScope::Thread,
        true,
        "thread and comments",
        true,
        true,
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        "thread",
        "reddit-source-options/v1",
        "reddit-thread/v1",
        &["thread", "comment"],
        &["author", "subreddit"],
        &[
            "public-json-unavailable",
            "comments-truncated",
            "rate-limited",
        ],
    ),
    scope_capability(
        SourceScope::Comment,
        false,
        "comment permalink",
        true,
        true,
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        "comment",
        "reddit-source-options/v1",
        "reddit-thread/v1",
        &["comment"],
        &["author"],
        &["public-json-unavailable"],
    ),
];

pub(crate) const SESSIONS_SCOPES: &[SourceScopeCapability] = &[
    scope_capability(
        SourceScope::File,
        true,
        "session export file",
        true,
        false,
        true,
        false,
        true,
        false,
        false,
        false,
        true,
        "transcript",
        "sessions-source-options/v1",
        "session-transcript/v1",
        &["session", "turn"],
        &["tool_call", "artifact"],
        &["unknown-export-format", "partial-turn", "redacted-secret"],
    ),
    scope_capability(
        SourceScope::Directory,
        true,
        "session export directory",
        true,
        false,
        true,
        false,
        true,
        false,
        false,
        false,
        true,
        "transcript",
        "sessions-source-options/v1",
        "session-transcript/v1",
        &["session", "turn"],
        &["tool_call", "artifact"],
        &["unknown-export-format", "partial-turn", "redacted-secret"],
    ),
];

pub(crate) const REGISTRY_SCOPES: &[SourceScopeCapability] = &[
    scope_capability(
        SourceScope::Package,
        true,
        "package metadata",
        true,
        true,
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        "package",
        "registry-source-options/v1",
        "package-metadata/v1",
        &["package", "version"],
        &["dependency", "release"],
        &["provider-unavailable", "version-yanked", "rate-limited"],
    ),
    scope_capability(
        SourceScope::Version,
        true,
        "version metadata",
        true,
        true,
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        "package",
        "registry-source-options/v1",
        "package-metadata/v1",
        &["package", "version"],
        &["dependency"],
        &["provider-unavailable", "version-yanked"],
    ),
];

/// `tool`/`script` scopes describe an installed CLI tool without ever
/// running it; `api` stands in for the contract's `run` scope (there is no
/// dedicated `SourceScope::Run` variant yet) — the only scope in this family
/// with `may_execute_tools = true`, gated on an explicit allowlist by
/// `cli_tool::resolve_and_acquire`.
pub(crate) const TOOL_SCOPES: &[SourceScopeCapability] = &[
    scope_capability(
        SourceScope::Tool,
        true,
        "metadata-only tool definition by default",
        true,
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        "tool",
        "cli-tool-source-options/v1",
        "tool-metadata/v1",
        &["tool"],
        &["tool_call", "artifact"],
        &["metadata-only"],
    ),
    scope_capability(
        SourceScope::Script,
        false,
        "explicit script source class",
        true,
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        "file",
        "cli-tool-source-options/v1",
        "code/v1",
        &["tool"],
        &["dependency"],
        &["metadata-only"],
    ),
    scope_capability(
        SourceScope::Api,
        false,
        "execute an allowlisted command (contract scope: run)",
        true,
        true,
        false,
        false,
        true,
        false,
        false,
        true,
        false,
        "tool_call",
        "cli-tool-source-options/v1",
        "tool-output/v1",
        &["tool_call"],
        &["artifact", "external_resource"],
        &["command-denied", "output-capped", "metadata-only"],
    ),
];

/// `tool` describes an MCP tool schema without calling it; `api` stands in
/// for the contract's `call` scope (there is no dedicated
/// `SourceScope::Call` variant yet) and is the only scope with
/// `may_execute_tools = true`, gated on an explicit allowlist by
/// `mcp_tool::resolve_and_acquire`.
pub(crate) const MCP_SCOPES: &[SourceScopeCapability] = &[
    scope_capability(
        SourceScope::Tool,
        true,
        "MCP tool schema",
        true,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        "tool_schema",
        "mcp-tool-source-options/v1",
        "api-schema/v1",
        &["mcp_server", "mcp_tool"],
        &["tool_call", "external_resource"],
        &["schema-only", "tool-unavailable"],
    ),
    scope_capability(
        SourceScope::Api,
        false,
        "MCP call result with explicit execution scope (contract scope: call)",
        true,
        true,
        false,
        false,
        false,
        true,
        false,
        true,
        false,
        "tool_call",
        "mcp-tool-source-options/v1",
        "tool-output/v1",
        &["mcp_tool", "tool_call"],
        &["external_resource"],
        &["tool-unavailable", "output-capped"],
    ),
];

pub(crate) const MEMORY_SCOPES: &[SourceScopeCapability] = &[scope_capability(
    SourceScope::Api,
    true,
    "one durable memory record",
    true,
    false,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    "memory_record",
    "memory-shared-pipeline-options/v1",
    "atomic-metadata/v1",
    &["memory_document"],
    &["memory_link", "supersedes", "contradicts"],
    &[
        "memory-not-found",
        "memory-not-authorized",
        "memory-not-recallable",
    ],
)];
pub(crate) const NO_CREDENTIALS: &[axon_api::source::CredentialRequirement] = &[];
