//! Content-family scope tables (local/upload/git/web/feed).

use axon_api::source::SourceScope;

use crate::spec::{SourceScopeCapability, scope_capability};

pub(crate) const LOCAL_SCOPES: &[SourceScopeCapability] = &[
    scope_capability(
        SourceScope::File,
        true,
        "single trusted local file",
        true,
        true,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        "file",
        "local-source-options/v1",
        "local-file/v1",
        &["document", "filesystem_path"],
        &["symbol", "dependency"],
        &["permission-denied", "file-too-large"],
    ),
    scope_capability(
        SourceScope::Directory,
        true,
        "trusted contained directory walk",
        true,
        true,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        "directory",
        "local-source-options/v1",
        "local-directory/v1",
        &["document", "filesystem_path"],
        &["symbol", "dependency"],
        &[
            "permission-denied",
            "file-too-large",
            "symlink-outside-root",
        ],
    ),
    scope_capability(
        SourceScope::Workspace,
        false,
        "trusted workspace source",
        true,
        true,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        "workspace",
        "local-source-options/v1",
        "local-directory/v1",
        &["document", "filesystem_path"],
        &["symbol", "dependency"],
        &[
            "permission-denied",
            "file-too-large",
            "symlink-outside-root",
        ],
    ),
];

pub(crate) const UPLOAD_SCOPES: &[SourceScopeCapability] = &[
    scope_capability(
        SourceScope::File,
        true,
        "single uploaded file",
        true,
        true,
        true,
        false,
        true,
        false,
        false,
        false,
        true,
        "file",
        "upload-source-options/v1",
        "local-file/v1",
        &["document", "filesystem_path"],
        &["symbol", "dependency"],
        &["permission-denied", "file-too-large"],
    ),
    scope_capability(
        SourceScope::Directory,
        true,
        "unpacked archive or repomix bundle",
        true,
        true,
        true,
        false,
        true,
        false,
        false,
        false,
        true,
        "directory",
        "upload-source-options/v1",
        "local-directory/v1",
        &["document", "filesystem_path"],
        &["symbol", "dependency"],
        &[
            "permission-denied",
            "file-too-large",
            "symlink-outside-root",
        ],
    ),
    scope_capability(
        SourceScope::Map,
        false,
        "staged content discovery without embedding",
        false,
        true,
        true,
        false,
        true,
        false,
        false,
        false,
        true,
        "candidate",
        "upload-source-options/v1",
        "none",
        &[],
        &["filesystem_path"],
        &["permission-denied"],
    ),
];

pub(crate) const GIT_SCOPES: &[SourceScopeCapability] = &[
    scope_capability(
        SourceScope::Repo,
        true,
        "repository snapshot",
        true,
        true,
        true,
        false,
        true,
        true,
        false,
        false,
        false,
        "repo_file",
        "git-source-options/v1",
        "git-repo/v1",
        &["repository", "revision"],
        &["symbol", "dependency", "release"],
        &["shallow-clone", "missing-provider-token", "rate-limited"],
    ),
    scope_capability(
        SourceScope::Branch,
        false,
        "branch-specific snapshot",
        true,
        true,
        true,
        false,
        true,
        true,
        false,
        false,
        false,
        "repo_file",
        "git-source-options/v1",
        "git-repo/v1",
        &["repository", "revision"],
        &["symbol", "dependency"],
        &["shallow-clone", "rate-limited"],
    ),
    scope_capability(
        SourceScope::Org,
        false,
        "provider-specific hardening",
        false,
        true,
        true,
        true,
        false,
        true,
        false,
        false,
        false,
        "repo_candidate",
        "git-source-options/v1",
        "none",
        &[],
        &["repository"],
        &["rate-limited", "missing-provider-token"],
    ),
];

pub(crate) const WEB_SCOPES: &[SourceScopeCapability] = &[
    scope_capability(
        SourceScope::Page,
        true,
        "single URL",
        true,
        true,
        true,
        false,
        false,
        true,
        true,
        false,
        false,
        "page",
        "web-source-options/v1",
        "web-page/v1",
        &["web_page", "canonical_url"],
        &["link", "structured_data"],
        &["http-only", "render-unavailable", "thin-content"],
    ),
    scope_capability(
        SourceScope::Site,
        true,
        "site crawl",
        true,
        true,
        true,
        false,
        false,
        true,
        true,
        false,
        false,
        "page",
        "web-source-options/v1",
        "web-page/v1",
        &["web_page", "canonical_url"],
        &["link", "structured_data"],
        &["http-only", "render-unavailable", "thin-content"],
    ),
    scope_capability(
        SourceScope::Map,
        true,
        "URL discovery",
        false,
        true,
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        "candidate",
        "web-source-options/v1",
        "none",
        &[],
        &["link", "structured_data"],
        &["thin-content"],
    ),
];

pub(crate) const FEED_SCOPES: &[SourceScopeCapability] = &[
    scope_capability(
        SourceScope::Feed,
        true,
        "RSS/Atom/JSON feed",
        true,
        true,
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        "feed_entry",
        "feed-source-options/v1",
        "feed-entry/v1",
        &["feed", "feed_entry"],
        &["author", "link"],
        &["malformed-entry", "rate-limited"],
    ),
    scope_capability(
        SourceScope::Page,
        false,
        "linked entry page",
        true,
        true,
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        "page",
        "feed-source-options/v1",
        "web-page/v1",
        &["feed_entry"],
        &["link"],
        &["linked-page-unavailable"],
    ),
];
