//! Shared "generated file" header comment, in each target language's comment
//! syntax, carrying the contract version + source hash per the contract.

use super::model::TokenSource;

pub fn css_header(src: &TokenSource) -> String {
    format!(
        "/* generated by cargo xtask presentation generate; do not edit directly */\n\
         /* contract-version: {} | source-hash: {} */\n\
         /* source of truth: {} */\n\n",
        src.contract_version,
        src.source_hash(),
        src.source_doc,
    )
}

pub fn rust_header(src: &TokenSource) -> String {
    format!(
        "// generated by cargo xtask presentation generate; do not edit directly\n\
         // contract-version: {} | source-hash: {}\n\
         // source of truth: {}\n\n",
        src.contract_version,
        src.source_hash(),
        src.source_doc,
    )
}

pub fn kotlin_header(src: &TokenSource) -> String {
    format!(
        "// generated by cargo xtask presentation generate; do not edit directly\n\
         // contract-version: {} | source-hash: {}\n\
         // source of truth: {}\n\n",
        src.contract_version,
        src.source_hash(),
        src.source_doc,
    )
}

pub fn markdown_header(src: &TokenSource) -> String {
    format!(
        "<!-- generated by cargo xtask presentation generate; do not edit directly -->\n\
         <!-- contract-version: {} | source-hash: {} -->\n\n",
        src.contract_version,
        src.source_hash(),
    )
}
