//! Emits the consumption-pointer README alongside the generated token
//! artifacts (`docs/reference/presentation/README.md`). Not itself a
//! "do not edit directly" generated file's header — it's prose — but it is
//! still written by `presentation generate` so it stays accurate about the
//! artifact list below.

use super::model::TokenSource;

pub fn render(src: &TokenSource) -> String {
    format!(
        "# Presentation Tokens — Generator Output\n\n\
         Generated by `cargo xtask presentation generate` from the single canonical\n\
         source at `xtask/src/presentation/source.json` \
         (contract version `{version}`, source hash `{hash}`).\n\n\
         This is the U3-14 generator slice: it emits token artifacts alongside the\n\
         existing hand-written styles/themes. **Apps are not yet rewired to consume\n\
         these files** — that migration is a follow-up. Do not delete the existing\n\
         `aurora.css` files or `AxonTheme.kt`; the generated files below are additive.\n\n\
         ## Generated files\n\n\
         | File | Consumed by (follow-up) |\n\
         |---|---|\n\
         | `docs/reference/presentation/tokens.md` | human reference |\n\
         | `docs/reference/presentation/tokens.schema.json` | schema validation for `source.json` |\n\
         | `apps/web/src/styles/axon-tokens.css` | web app root, alongside `aurora.css` |\n\
         | `apps/palette-tauri/src/styles/axon-tokens.css` | Palette desktop, alongside `aurora.css` |\n\
         | `apps/chrome-extension/src/styles/axon-tokens.css` | extension popup/content styles |\n\
         | `apps/android/app/src/main/java/com/axon/app/ui/theme/generated/AxonTokens.kt` | `AxonTheme.kt` migration target |\n\
         | `crates/axon-cli/src/ui/tokens.rs` | `CliTheme`/ad hoc CLI color sites |\n\n\
         Note: the Android artifact lives under the existing `apps/android/app` module\n\
         rather than the contract doc's illustrative `core/design` module path, because\n\
         no such module exists in this repo yet — creating one is out of scope for the\n\
         generator itself.\n\n\
         ## Regenerating\n\n\
         ```bash\n\
         cargo xtask presentation generate       # write/refresh all artifacts\n\
         cargo xtask presentation generate --check   # drift check, no writes\n\
         ```\n\n\
         Generation is idempotent: running `generate` twice with an unchanged\n\
         `source.json` produces byte-identical output the second time.\n",
        version = src.contract_version,
        hash = src.source_hash(),
    )
}
