import { deriveConfigModel } from "./configDefaults";
import type { TomlConfigGroup } from "./configTypes";
import { ENV_GROUPS } from "./envGroups";

export type { ConfigField, ConfigFieldType, EnvGroup, TomlConfigGroup } from "./configTypes";
export { ENV_GROUPS } from "./envGroups";

/* ── CONFIG layer — ~/.axon/config.toml : non-secret tuning ── */
export const CONFIG_GROUPS: TomlConfigGroup[] = [
  {
    id: "providers-vector",
    section: "[providers.vector]",
    label: "Vector Provider",
    icon: "search",
    note: "Qdrant hybrid and HNSW tuning.",
    knobs: [
      {
        key: "hybrid-enabled",
        type: "bool",
        def: true,
        env: "AXON_HYBRID_SEARCH",
        desc: "Enable RRF hybrid search (needs a named-mode collection).",
      },
      {
        key: "hnsw-ef",
        type: "int",
        def: 128,
        env: "AXON_HNSW_EF_SEARCH",
        desc: "HNSW ef for named-mode collections (32–512).",
      },
    ],
  },
  {
    id: "retrieval",
    section: "[retrieval]",
    label: "Retrieval",
    icon: "search",
    note: "RRF retrieval candidate windows.",
    knobs: [
      {
        key: "hybrid-candidates",
        type: "int",
        def: 100,
        env: "AXON_HYBRID_CANDIDATES",
        desc: "Candidates per prefetch arm before RRF fusion (10–500).",
      },
      {
        key: "ask-hybrid-candidates",
        type: "int",
        def: 150,
        env: "AXON_ASK_HYBRID_CANDIDATES",
        desc: "Hybrid prefetch window for the ask pipeline (10–500).",
      },
    ],
  },
  {
    id: "ask",
    section: "[ask]",
    label: "Ask Pipeline",
    icon: "ask",
    note: "Context assembly, chunk limits, and rerank gating for RAG answers.",
    knobs: [
      {
        key: "max-context-chars",
        type: "int",
        def: 300000,
        env: "AXON_ASK_MAX_CONTEXT_CHARS",
        desc: "Max context chars to the LLM (20k–1M).",
      },
      {
        key: "chunk-limit",
        type: "int",
        def: 20,
        env: "AXON_ASK_CHUNK_LIMIT",
        desc: "Max chunks returned per ask query (3–40).",
      },
      {
        key: "candidate-limit",
        type: "int",
        def: 250,
        env: "AXON_ASK_CANDIDATE_LIMIT",
        desc: "Max candidate chunks fetched before scoring (8–300).",
      },
      {
        key: "full-docs",
        type: "int",
        def: 6,
        env: "AXON_ASK_FULL_DOCS",
        desc: "Max full documents in context (1–20).",
      },
      {
        key: "backfill-chunks",
        type: "int",
        def: 5,
        env: "AXON_ASK_BACKFILL_CHUNKS",
        desc: "Backfill chunks from top docs to pad context (0–20).",
      },
      {
        key: "doc-fetch-concurrency",
        type: "int",
        def: 4,
        env: "AXON_ASK_DOC_FETCH_CONCURRENCY",
        desc: "Concurrent doc fetches during context build (1–16).",
      },
      {
        key: "doc-chunk-limit",
        type: "int",
        def: 96,
        env: "AXON_ASK_DOC_CHUNK_LIMIT",
        desc: "Max chunks per document in context (8–2000).",
      },
      {
        key: "min-relevance-score",
        type: "float",
        def: 0.45,
        env: "AXON_ASK_MIN_RELEVANCE_SCORE",
        desc: "Min relevance score to include a chunk (-1.0–2.0).",
      },
      {
        key: "authoritative-domains",
        type: "list",
        def: ["code.claude.com"],
        env: "AXON_ASK_AUTHORITATIVE_DOMAINS",
        desc: "Domains treated as authoritative during reranking.",
      },
      {
        key: "authoritative-boost",
        type: "float",
        def: 0.12,
        env: "AXON_ASK_AUTHORITATIVE_BOOST",
        desc: "Boost weight for authoritative domains (0.0–0.5).",
      },
      {
        key: "min-citations-nontrivial",
        type: "int",
        def: 2,
        env: "AXON_ASK_MIN_CITATIONS_NONTRIVIAL",
        desc: "Min unique citations for non-trivial answers (1–5).",
      },
    ],
  },
  {
    id: "ask-cache",
    section: "[ask.cache]",
    label: "Ask Cache",
    icon: "database",
    note: "In-process doc-chunk cache. Only useful in long-lived parents (serve / mcp).",
    knobs: [
      { key: "enabled", type: "bool", def: false, desc: "Enable the ask full-doc fetch cache." },
      {
        key: "max-capacity-bytes",
        type: "int",
        def: 268435456,
        desc: "Max cached bytes (default 256 MiB).",
      },
      {
        key: "ttl-secs",
        type: "int",
        def: 300,
        desc: "TTL for cached entries (hard-capped at 300s).",
      },
    ],
  },
  {
    id: "ask-adaptive",
    section: "[ask.adaptive]",
    label: "Ask Adaptive",
    icon: "zap",
    note: "Full-doc fetch skip gate. Enable only if evaluate shows no quality regression.",
    knobs: [
      {
        key: "fulldoc-skip-enabled",
        type: "bool",
        def: false,
        desc: "Elide the full-doc backfill when top-K already covers enough.",
      },
      {
        key: "fulldoc-skip-min-urls",
        type: "int",
        def: 3,
        desc: "Min unique URLs required in reranked top-K (1–50).",
      },
      {
        key: "fulldoc-skip-min-chars",
        type: "int",
        def: 4000,
        desc: "Min total chunk bytes across top-K (500–200k).",
      },
      {
        key: "fulldoc-skip-score-delta",
        type: "float",
        def: 0.15,
        desc: "Cosine-mode score floor offset (0.0–1.0). Ignored on RRF.",
      },
    ],
  },
  {
    id: "providers-embedding",
    section: "[providers.embedding]",
    label: "Embedding Provider",
    icon: "layers",
    note: "Embeddings client retry, timeout, and batch tuning.",
    knobs: [
      {
        key: "max-retries",
        type: "int",
        def: 5,
        env: "TEI_MAX_RETRIES",
        desc: "Max retry attempts after the initial TEI request.",
      },
      {
        key: "request-timeout-ms",
        type: "int",
        def: 30000,
        env: "TEI_REQUEST_TIMEOUT_MS",
        desc: "Per-attempt timeout in milliseconds.",
      },
      {
        key: "batch-size",
        type: "int",
        def: 128,
        env: "TEI_MAX_CLIENT_BATCH_SIZE",
        desc: "Default batch size; auto-splits on HTTP 413.",
      },
    ],
  },
  {
    id: "pipeline",
    section: "[pipeline]",
    label: "Pipeline",
    icon: "activity",
    note: "Unified pipeline concurrency and buffering.",
    knobs: [
      {
        key: "unified-worker-concurrency",
        type: "int",
        def: 8,
        env: "AXON_UNIFIED_WORKER_CONCURRENCY",
        desc: "Maximum concurrent unified jobs (1–64).",
      },
      {
        key: "embed-doc-timeout-secs",
        type: "int",
        def: 300,
        env: "AXON_EMBED_DOC_TIMEOUT_SECS",
        desc: "Per-document embed timeout in seconds.",
      },
      {
        key: "queue-summary-secs",
        type: "int",
        def: 30,
        env: "AXON_QUEUE_SUMMARY_SECS",
        desc: "Queue summary interval (0 disables, 0–3600).",
      },
      {
        key: "qdrant-point-buffer",
        type: "int",
        def: 256,
        env: "AXON_QDRANT_POINT_BUFFER",
        desc: "Buffered Qdrant points before flush (128–16384).",
      },
      {
        key: "job-wait-timeout-secs",
        type: "int",
        def: 300,
        env: "AXON_JOB_WAIT_TIMEOUT_SECS",
        desc: "Timeout for --wait true polling (30–3600).",
      },
    ],
  },
  {
    id: "providers-render",
    section: "[providers.render]",
    label: "Render Provider",
    icon: "globe",
    note: "Headless Chrome render path — UA, TLS, idle, and bootstrap probes.",
    knobs: [
      {
        key: "user-agent",
        type: "text",
        def: "",
        env: "AXON_CHROME_USER_AGENT",
        desc: "Custom Chrome UA. Unset = Spider default.",
      },
      {
        key: "bypass-csp",
        type: "bool",
        def: false,
        desc: "Bypass Content Security Policy in Chrome.",
      },
      {
        key: "accept-invalid-certs",
        type: "bool",
        def: false,
        desc: "Accept invalid / self-signed TLS certs.",
      },
      {
        key: "network-idle-timeout-secs",
        type: "int",
        def: 15,
        desc: "Wait for network idle before page capture.",
      },
      {
        key: "bootstrap-timeout-ms",
        type: "int",
        def: 3000,
        desc: "Remote Chrome bootstrap probe timeout (≥250).",
      },
      {
        key: "bootstrap-retries",
        type: "int",
        def: 2,
        desc: "Remote Chrome bootstrap probe retries (0–10).",
      },
    ],
  },
  {
    id: "providers-fetch",
    section: "[providers.fetch]",
    label: "Fetch Provider",
    icon: "globe",
    note: "HTTP delay, timeout, and retry policy.",
    knobs: [
      { key: "delay-ms", type: "int", def: 0, desc: "Delay between requests in milliseconds." },
      { key: "request-timeout-ms", type: "int", def: 20000, desc: "Per-request HTTP timeout." },
      { key: "retries", type: "int", def: 2, desc: "Fetch retry count." },
      { key: "retry-backoff-ms", type: "int", def: 250, desc: "Retry backoff in milliseconds." },
    ],
  },
  {
    id: "crawl",
    section: "[crawl]",
    label: "Site Acquisition",
    icon: "scrape",
    note: "Fetch behavior, sitemap/llms.txt backfill, auto-switch, and the DOM retry ladder.",
    knobs: [
      { key: "respect-robots", type: "bool", def: false, desc: "Respect robots.txt directives." },
      {
        key: "min-markdown-chars",
        type: "int",
        def: 200,
        desc: "Thin-page threshold in markdown characters.",
      },
      {
        key: "drop-thin-markdown",
        type: "bool",
        def: true,
        desc: "Skip thin pages instead of saving / embedding.",
      },
      {
        key: "discover-sitemaps",
        type: "bool",
        def: true,
        desc: "Backfill URLs from sitemap.xml after crawl.",
      },
      {
        key: "sitemap-since-days",
        type: "int",
        def: 0,
        desc: "Only backfill sitemap URLs newer than N days (0 = off).",
      },
      {
        key: "max-sitemaps",
        type: "int",
        def: 512,
        desc: "Max sitemap documents to parse (0 = unlimited).",
      },
      {
        key: "discover-llms-txt",
        type: "bool",
        def: true,
        desc: "Probe /llms.txt and merge its links into discovery.",
      },
      {
        key: "max-llms-txt-urls",
        type: "int",
        def: 512,
        desc: "Max URLs from a single /llms.txt (0 = unlimited).",
      },
      {
        key: "auto-switch-thin-ratio",
        type: "float",
        def: 0.6,
        desc: "Thin-page ratio that triggers auto-switch to Chrome.",
      },
      {
        key: "auto-switch-min-pages",
        type: "int",
        def: 10,
        desc: "Min page count before auto-switch eligibility.",
      },
      {
        key: "url-whitelist",
        type: "list",
        def: [],
        desc: "Only crawl URLs matching these regex patterns.",
      },
      {
        key: "max-page-bytes",
        type: "int",
        def: 0,
        desc: "Max response size per page (0 = unlimited).",
      },
      {
        key: "redirect-policy-strict",
        type: "bool",
        def: false,
        desc: "Only follow same-origin redirects.",
      },
      {
        key: "ladder-strategy1-threshold",
        type: "int",
        def: 30,
        env: "AXON_LADDER_STRATEGY1_THRESHOLD",
        desc: "Ladder S1 word threshold → retry with only_main_content=false (1–1000).",
      },
      {
        key: "ladder-strategy2-threshold",
        type: "int",
        def: 200,
        env: "AXON_LADDER_STRATEGY2_THRESHOLD",
        desc: "Ladder S2 word threshold → retry with body selector (1–10000).",
      },
      {
        key: "ladder-body-multiplier",
        type: "float",
        def: 2.0,
        env: "AXON_LADDER_BODY_MULTIPLIER",
        desc: "Body wins only if it yields N× scored words (1.0–10.0).",
      },
    ],
  },
  {
    id: "crawl-verticals",
    section: "[crawl.verticals]",
    label: "Vertical Extractors",
    icon: "braces",
    note: "Per-site extractors (GitHub, PyPI, Reddit, HN…) with per-vertical cache TTLs.",
    knobs: [
      {
        key: "enabled",
        type: "bool",
        def: true,
        env: "AXON_ENABLE_VERTICALS",
        desc: "Enable per-site vertical extractors.",
      },
      {
        key: "auto-dispatch-skip",
        type: "list",
        def: [],
        env: "AXON_AUTO_DISPATCH_SKIP",
        desc: "Verticals to skip in auto-dispatch (still available explicitly).",
      },
    ],
  },
  {
    id: "crawl-antibot",
    section: "[crawl.antibot]",
    label: "Anti-bot",
    icon: "shield",
    note: "Akamai / Cloudflare challenge handling.",
    knobs: [
      {
        key: "cookie-warmup",
        type: "bool",
        def: true,
        env: "AXON_CHALLENGE_WARMUP",
        desc: "Cookie warmup retry on antibot challenge.",
      },
      {
        key: "max-body-scan-bytes",
        type: "int",
        def: 150000,
        env: "AXON_ANTIBOT_MAX_BODY_SCAN_BYTES",
        desc: "Max bytes scanned for challenge patterns (1k–10 MiB).",
      },
    ],
  },
  {
    id: "providers-vector-payload",
    section: "[providers.vector]",
    label: "Vector Payload",
    icon: "database",
    note: "Qdrant structured-blob payload sizing.",
    knobs: [
      {
        key: "structured-data-max-bytes",
        type: "int",
        def: 65536,
        env: "AXON_STRUCTURED_DATA_MAX_BYTES",
        desc: "Max structured_blob bytes per chunk (1 KiB–16 MiB).",
      },
    ],
  },
];

export const { ENV_DEFAULTS, CONFIG_DEFAULTS, ENV_COUNT, CONFIG_COUNT } = deriveConfigModel(
  ENV_GROUPS,
  CONFIG_GROUPS,
);
