// Generic async-job progress model for the palette's live job view.
//
// `crawl` has its own richer model (`crawlJob.ts`) because it surfaces a live
// page frontier, depth, and a two-phase crawl→embed handoff. The other async
// job families — `embed`, `extract`, `ingest` — share a much simpler shape:
// poll `GET /v1/{family}/{id}`, read `status` + a handful of `result_json`
// counters, and render a status card until the job reaches a terminal state.
//
// Everything here is derived from REAL data polled from `axon serve`; the
// derivation (phase, percent, metrics) is pure and unit-tested. The view layer
// (`JobProgressView`) renders a `JobSnapshot` and never re-derives.

import type { components } from "./axon-api";

export type AsyncJobFamily = "embed" | "extract" | "ingest";

export type JobPhase = "pending" | "running" | "done" | "failed" | "canceled";

export interface JobMetric {
  label: string;
  value: string;
}

// Compile-time drift guard: the palette's local view-model unions MUST stay
// aligned with the server's generated `JobProgress` contract (axon-api →
// `axon-api.d.ts`, regenerated by `cargo xtask check-openapi-drift`). If the
// backend changes the phase set, family set, or metric shape, these assignability
// checks fail at `pnpm typecheck` instead of silently mis-parsing at runtime.
type _AssertFamily = AsyncJobFamily extends components["schemas"]["JobFamily"] ? true : never;
type _AssertFamilyBack = components["schemas"]["JobFamily"] extends AsyncJobFamily ? true : never;
type _AssertPhase = JobPhase extends components["schemas"]["JobPhase"] ? true : never;
type _AssertPhaseBack = components["schemas"]["JobPhase"] extends JobPhase ? true : never;
type _AssertMetric = components["schemas"]["JobMetric"] extends JobMetric ? true : never;
const _drift: [_AssertFamily, _AssertFamilyBack, _AssertPhase, _AssertPhaseBack, _AssertMetric] = [
  true,
  true,
  true,
  true,
  true,
];
void _drift;

export interface JobSnapshot {
  family: AsyncJobFamily;
  jobId: string;
  /** Display label for the target (repo slug, URL, embed input). */
  label: string;
  /** Raw backend status string. */
  status: string;
  phase: JobPhase;
  /** 0–100 when determinate; `null` means indeterminate (pulsing bar). */
  percent: number | null;
  /** Key counters pulled from `result_json`, family-specific. */
  metrics: JobMetric[];
  errorText: string | null;
  /** Epoch ms of the last backend write (heartbeat or progress persist). */
  updatedAtMs: number | null;
  startedAtMs: number | null;
}

export function isJobPhaseTerminal(phase: JobPhase): boolean {
  return phase === "done" || phase === "failed" || phase === "canceled";
}

const FAMILY_VERB: Record<AsyncJobFamily, string> = {
  embed: "Embedding",
  extract: "Extracting",
  ingest: "Ingesting",
};

/** Present-tense gerund for a running job of this family ("Ingesting"). */
export function jobFamilyVerb(family: AsyncJobFamily): string {
  return FAMILY_VERB[family];
}

interface JsonRecord {
  [key: string]: unknown;
}

function asRecord(value: unknown): JsonRecord | null {
  return value && typeof value === "object" && !Array.isArray(value) ? (value as JsonRecord) : null;
}

function str(value: unknown): string | null {
  return typeof value === "string" && value.length > 0 ? value : null;
}

function phaseFor(status: string): JobPhase {
  switch (status) {
    case "pending":
      return "pending";
    case "completed":
      return "done";
    case "failed":
      return "failed";
    case "canceled":
    case "cancelled":
      return "canceled";
    case "running":
      return "running";
    default:
      return "running";
  }
}

function parseTimestamp(value: unknown): number | null {
  const s = str(value);
  if (!s) return null;
  const ms = Date.parse(s);
  return Number.isNaN(ms) ? null : ms;
}

const PHASES: readonly JobPhase[] = ["pending", "running", "done", "failed", "canceled"];

function parsePhase(value: unknown): JobPhase | null {
  return typeof value === "string" && (PHASES as readonly string[]).includes(value)
    ? (value as JobPhase)
    : null;
}

function parseMetrics(value: unknown): JobMetric[] {
  if (!Array.isArray(value)) return [];
  const metrics: JobMetric[] = [];
  for (const item of value) {
    const rec = asRecord(item);
    const label = str(rec?.label);
    const v = str(rec?.value);
    if (label && v != null) metrics.push({ label, value: v });
  }
  return metrics;
}

export interface JobSummaryInput {
  jobId: string;
  /** Display label for the target (repo, URL, input). */
  label: string;
}

/**
 * Assemble a `JobSnapshot` from a polled job payload. The risk-prone derivation
 * (phase / percent / metrics) is the SERVER's job: `GET /v1/{family}/{id}`
 * returns a canonical `progress` block (axon-api `JobProgress`) that every
 * surface consumes, so the logic can't drift across CLI/MCP/REST/palette. This
 * is a thin view-model assembler — prefer `progress`, and fall back to a
 * status-only snapshot for the brief pre-first-poll window (the POST accept
 * response carries no `progress`).
 */
export function summarizeJob(
  family: AsyncJobFamily,
  payload: unknown,
  input: JobSummaryInput,
): JobSnapshot {
  const root = asRecord(payload) ?? {};
  const job = asRecord(root.job) ?? root;
  const progress = asRecord(root.progress);
  const status = str(job.status) ?? "pending";
  const updatedAtMs = parseTimestamp(job.updated_at);
  const startedAtMs = parseTimestamp(job.started_at);

  if (progress) {
    return {
      family,
      jobId: input.jobId,
      label: input.label,
      status,
      phase: parsePhase(progress.phase) ?? phaseFor(status),
      percent: typeof progress.percent === "number" ? progress.percent : null,
      metrics: parseMetrics(progress.metrics),
      errorText: str(progress.error),
      updatedAtMs,
      startedAtMs,
    };
  }

  // No server progress yet (the 202 accept response): status-only placeholder.
  return {
    family,
    jobId: input.jobId,
    label: input.label,
    status,
    phase: phaseFor(status),
    percent: status === "completed" ? 100 : null,
    metrics: [],
    errorText: str(job.error_text),
    updatedAtMs,
    startedAtMs,
  };
}

/** A pending placeholder snapshot shown immediately on submit. */
export function pendingJobSnapshot(family: AsyncJobFamily, label: string): JobSnapshot {
  return summarizeJob(family, { job: { status: "pending" } }, { jobId: "", label });
}
