use super::AxonMcpServer;
use super::common::MCP_TOOL_SCHEMA_URI;
use super::metadata::{
    MCP_APP_MIME_TYPE, STATUS_DASHBOARD_HTML, STATUS_DASHBOARD_URI, axon_tool_meta,
    mcp_apps_server_capabilities, mcp_tool_schema_markdown,
};
use super::scope::{check_scope, require_auth_context, required_scope_for};
use crate::services::system;
use rmcp::model::{
    CallToolRequestParams, CallToolResult, ErrorData, InitializeRequestParams, InitializeResult,
    ListResourcesResult, PaginatedRequestParams, RawResource, ReadResourceRequestParams,
    ReadResourceResult, Resource, ResourceContents, ServerInfo,
};
use rmcp::service::RequestContext;
use rmcp::{RoleServer, ServerHandler};

#[async_trait::async_trait]
impl ServerHandler for AxonMcpServer {
    async fn call_tool(
        &self,
        request: CallToolRequestParams,
        context: RequestContext<RoleServer>,
    ) -> Result<CallToolResult, ErrorData> {
        // Extract action and subaction for scope check before any processing.
        let action: String = request
            .arguments
            .as_ref()
            .and_then(|m| m.get("action"))
            .and_then(serde_json::Value::as_str)
            .unwrap_or("")
            .to_owned();
        let subaction: String = request
            .arguments
            .as_ref()
            .and_then(|m| m.get("subaction"))
            .and_then(serde_json::Value::as_str)
            .unwrap_or("")
            .to_owned();

        // Fail-closed auth check: require AuthContext when Mounted, then scope.
        // LoopbackDev returns None — no scope enforcement applies.
        let auth = require_auth_context(&self.auth_policy, &context)?;
        match (auth, required_scope_for(&action, &subaction)) {
            // Deny: sentinel returned for unknown actions — even with a valid
            // token, we refuse rather than accidentally granting access.
            (Some(_), Some("__deny__")) => {
                tracing::warn!(
                    action = %action,
                    "MCP tool invocation denied: unknown action (fail-conservative)"
                );
                return Err(ErrorData::invalid_request(
                    format!("forbidden: unknown action `{action}`"),
                    None,
                ));
            }
            // No scope required (e.g. "help") — allowed through when authenticated.
            (Some(_), None) => {}
            // Scope check required.
            (Some(auth_ctx), Some(required_scope)) => {
                check_scope(auth_ctx, required_scope, &action)?;
            }
            // LoopbackDev — no enforcement.
            (None, _) => {}
        }

        // Delegate to the tool router generated by #[tool_router].
        let tcc = rmcp::handler::server::tool::ToolCallContext::new(self, request, context);
        Self::tool_router().call(tcc).await
    }

    async fn initialize(
        &self,
        request: InitializeRequestParams,
        _context: RequestContext<RoleServer>,
    ) -> Result<InitializeResult, ErrorData> {
        tracing::info!(
            client_name = %request.client_info.name,
            client_version = %request.client_info.version,
            protocol_version = %request.protocol_version,
            has_extensions = %request.capabilities.extensions.is_some(),
            extensions = ?request.capabilities.extensions,
            "mcp_app initialize — client capabilities"
        );
        let info = self.get_info();
        Ok(InitializeResult::new(info.capabilities)
            .with_protocol_version(request.protocol_version)
            .with_server_info(info.server_info)
            .with_instructions(info.instructions.unwrap_or_default()))
    }

    fn get_info(&self) -> ServerInfo {
        tracing::info!("mcp_app get_info called — client connected");
        let mut info = ServerInfo::default();
        info.instructions = Some(concat!(
            "Axon is a self-hosted RAG engine for web crawl, scrape, extract, embed, and semantic search.\n",
            "\n",
            "Use the single `axon` tool with `action`/`subaction` routing for all operations.\n",
            "Call `action:help` first to discover all available actions, subactions, and parameter defaults.\n",
            "\n",
            "Search for this server's tools when the user wants to:\n",
            "- Crawl or scrape websites and index their content\n",
            "- Embed documents or URLs into the vector knowledge base\n",
            "- Run semantic search or RAG queries over indexed content\n",
            "- Ingest external sources (GitHub repos, Reddit threads/subreddits, YouTube videos/playlists)\n",
            "- Ask grounded questions against indexed docs (RAG with LLM synthesis)\n",
            "- Research topics via web search with automatic indexing\n",
            "- Extract structured data from pages using LLM-powered extraction\n",
            "- Check job queue status, cancel jobs, or manage async workers\n",
            "- Take screenshots, map site URLs, retrieve stored documents\n",
            "\n",
            "Key capabilities:\n",
            "- `crawl` — full-site async crawl with HTTP/Chrome auto-switch\n",
            "- `scrape` — single-page markdown extraction\n",
            "- `embed` — index file, directory, or URL into Qdrant\n",
            "- `ingest` — GitHub/Reddit/YouTube source ingestion\n",
            "- `query` — dense + BM42 hybrid semantic search\n",
            "- `ask` — RAG: retrieve context + LLM answer\n",
            "- `evaluate` — compare RAG quality against a baseline with judge diagnostics\n",
            "- `suggest` — propose new crawl targets from indexed source coverage\n",
            "- `research` — Tavily AI search with LLM synthesis\n",
            "- `extract` — structured data extraction via LLM\n",
            "- `status` / `doctor` — job queue health and service diagnostics\n",
            "- `artifacts` — read/grep/inspect large output files\n",
            "- MCP Apps enabled — exposes `ui://axon/status-dashboard` for live queue status widgets\n",
            "\n",
            "Async operations (crawl, embed, ingest, extract) return a job_id. Poll the same action with `subaction:status` and the returned `job_id`."
        ).into());
        info.capabilities = mcp_apps_server_capabilities();
        info
    }

    async fn list_resources(
        &self,
        _request: Option<PaginatedRequestParams>,
        _context: RequestContext<RoleServer>,
    ) -> Result<ListResourcesResult, ErrorData> {
        tracing::info!("mcp_app list_resources called");
        let schema_resource: Resource = RawResource {
            uri: MCP_TOOL_SCHEMA_URI.to_string(),
            name: "mcp-tool-schema".to_string(),
            title: Some("Axon MCP Tool Schema".to_string()),
            description: Some(
                "Source-of-truth schema and routing contract for the unified axon tool".to_string(),
            ),
            mime_type: Some("text/markdown".to_string()),
            size: None,
            icons: None,
            meta: None,
        }
        .no_annotation();

        let dashboard_resource: Resource = RawResource {
            uri: STATUS_DASHBOARD_URI.to_string(),
            name: "status-dashboard".to_string(),
            title: Some("Axon Status Dashboard".to_string()),
            description: Some(
                "Interactive MCP App widget showing live job queue status for all Axon workers"
                    .to_string(),
            ),
            mime_type: Some(MCP_APP_MIME_TYPE.to_string()),
            size: None,
            icons: None,
            meta: None,
        }
        .no_annotation();

        Ok(ListResourcesResult {
            meta: None,
            resources: vec![schema_resource, dashboard_resource],
            next_cursor: None,
        })
    }

    async fn read_resource(
        &self,
        request: ReadResourceRequestParams,
        _context: RequestContext<RoleServer>,
    ) -> Result<ReadResourceResult, ErrorData> {
        tracing::info!(uri = %request.uri, "mcp_app read_resource called");
        if request.uri == STATUS_DASHBOARD_URI {
            // Inject current status data so the widget renders immediately, bypassing
            // the MCP Apps postMessage bridge which may not be available in all hosts.
            let status_json =
                match crate::services::context::ServiceContext::new(self.cfg.clone()).await {
                    Ok(ctx) => match system::full_status(&ctx).await {
                        Ok(r) => {
                            serde_json::to_string(&r.payload).unwrap_or_else(|_| "null".to_string())
                        }
                        Err(_) => "null".to_string(),
                    },
                    Err(_) => "null".to_string(),
                };
            let html = STATUS_DASHBOARD_HTML.replacen(
                "window.__AXON_INITIAL_STATUS__ = null;",
                &format!("window.__AXON_INITIAL_STATUS__ = {};", status_json),
                1,
            );
            return Ok(ReadResourceResult::new(vec![
                ResourceContents::TextResourceContents {
                    uri: STATUS_DASHBOARD_URI.to_string(),
                    mime_type: Some(MCP_APP_MIME_TYPE.to_string()),
                    text: html,
                    meta: None,
                },
            ]));
        }
        if request.uri != MCP_TOOL_SCHEMA_URI {
            return Err(ErrorData::invalid_params(
                format!("resource not found: {}", request.uri),
                None,
            ));
        }
        Ok(ReadResourceResult::new(vec![
            ResourceContents::TextResourceContents {
                uri: MCP_TOOL_SCHEMA_URI.to_string(),
                mime_type: Some("text/markdown".to_string()),
                text: mcp_tool_schema_markdown().to_string(),
                meta: None,
            },
        ]))
    }
}
