use std::fs;

#[test]
fn services_compose_reads_repo_root_services_env() {
    let compose = fs::read_to_string("config/docker-compose.services.yaml")
        .expect("config/docker-compose.services.yaml should be readable");

    assert!(
        compose.contains("- ../services.env"),
        "config/docker-compose.services.yaml lives under config/, so env_file must point at \
         the repo-root services.env generated by docs and CI"
    );

    assert!(
        !compose.contains("- services.env"),
        "bare services.env resolves to config/services.env from this compose file and breaks \
         fresh checkouts"
    );
}

#[test]
fn ci_env_file_contains_compose_interpolation_values() {
    let workflow = fs::read_to_string(".github/workflows/ci.yml")
        .expect(".github/workflows/ci.yml should be readable");

    let env_block_start = workflow
        .find("} > .env")
        .expect("CI workflow should create a repo-root .env file");
    let env_block = &workflow[..env_block_start];

    for key in [
        "TEI_HTTP_PORT=52000",
        "TEI_EMBEDDING_MODEL=BAAI/bge-small-en-v1.5",
    ] {
        assert!(
            env_block.contains(key),
            "compose interpolation value {key} must be written to .env, not only services.env"
        );
    }

    assert!(
        workflow.contains(
            "docker compose --env-file .env -f config/docker-compose.services.yaml config"
        ),
        "CI should validate compose with the same repo-root .env file used for interpolation"
    );
}
