use std::fs;

#[test]
fn services_compose_reads_repo_root_services_env() {
    let compose = fs::read_to_string("config/docker-compose.services.yaml")
        .expect("config/docker-compose.services.yaml should be readable");

    assert!(
        compose.contains("- ../services.env"),
        "config/docker-compose.services.yaml lives under config/, so env_file must point at \
         the repo-root services.env generated by docs and CI"
    );

    assert!(
        !compose.contains("- services.env"),
        "bare services.env resolves to config/services.env from this compose file and breaks \
         fresh checkouts"
    );
}
