use super::EnvClassification::*;
use super::LegacyBehavior::*;
use super::RuntimePlacement::*;
use super::{EnvKeySpec, spec};

pub(crate) const RUNTIME_ENV_KEY_SPECS: &[EnvKeySpec] = &[
    spec("QDRANT_URL", KeepEnv, Both, None, Canonical, false),
    spec(
        "AXON_QDRANT_URL",
        ComposeEnv,
        ComposeInterpolation,
        None,
        Canonical,
        false,
    ),
    spec(
        "QDRANT_HTTP_PORT",
        ComposeEnv,
        ComposeInterpolation,
        None,
        Canonical,
        false,
    ),
    spec(
        "QDRANT_GRPC_PORT",
        ComposeEnv,
        ComposeInterpolation,
        None,
        Canonical,
        false,
    ),
    spec("TEI_URL", KeepEnv, Both, None, Canonical, false),
    spec(
        "AXON_CHROME_REMOTE_URL",
        KeepEnv,
        Both,
        None,
        Canonical,
        false,
    ),
    spec(
        "AXON_MCP_HTTP_TOKEN",
        KeepEnv,
        ContainerRequired,
        None,
        Canonical,
        true,
    ),
    spec("AXON_MCP_AUTH_MODE", KeepEnv, Both, None, Canonical, false),
    spec("AXON_MCP_PUBLIC_URL", KeepEnv, Both, None, Canonical, false),
    spec(
        "AXON_MCP_GOOGLE_CLIENT_ID",
        KeepEnv,
        Both,
        None,
        Canonical,
        false,
    ),
    spec(
        "AXON_MCP_GOOGLE_CLIENT_SECRET",
        KeepEnv,
        Both,
        None,
        Canonical,
        true,
    ),
    spec(
        "AXON_MCP_AUTH_ADMIN_EMAIL",
        KeepEnv,
        Both,
        None,
        Canonical,
        false,
    ),
    spec(
        "AXON_MCP_AUTH_ALLOWED_REDIRECT_URIS",
        KeepEnv,
        Both,
        None,
        Canonical,
        false,
    ),
    spec(
        "AXON_MCP_ALLOWED_ORIGINS",
        KeepEnv,
        Both,
        None,
        Canonical,
        false,
    ),
    spec("TAVILY_API_KEY", KeepEnv, Both, None, Canonical, true),
    spec("GITHUB_TOKEN", KeepEnv, Both, None, Canonical, true),
    spec("GITLAB_TOKEN", KeepEnv, Both, None, Canonical, true),
    spec("GITEA_TOKEN", KeepEnv, Both, None, Canonical, true),
    spec("REDDIT_CLIENT_ID", KeepEnv, Both, None, Canonical, false),
    spec("REDDIT_CLIENT_SECRET", KeepEnv, Both, None, Canonical, true),
    spec(
        "HF_TOKEN",
        KeepEnv,
        ComposeInterpolation,
        None,
        Canonical,
        true,
    ),
    spec("AXON_LLM_BACKEND", KeepEnv, Both, None, Canonical, false),
    spec("AXON_PROVIDER", KeepEnv, Both, None, Canonical, false),
    spec(
        "AXON_HEADLESS_GEMINI_CMD",
        KeepEnv,
        Both,
        None,
        Canonical,
        false,
    ),
    spec(
        "AXON_SYNTHESIS_HEADLESS_GEMINI_MODEL",
        KeepEnv,
        Both,
        None,
        Canonical,
        false,
    ),
    spec(
        "AXON_HEADLESS_GEMINI_MODEL",
        KeepEnv,
        Both,
        None,
        Canonical,
        false,
    ),
    spec(
        "AXON_CHAT_HEADLESS_GEMINI_MODEL",
        KeepEnv,
        Both,
        None,
        Canonical,
        false,
    ),
    spec(
        "AXON_LLM_COMPLETION_CONCURRENCY",
        KeepEnv,
        Both,
        None,
        Canonical,
        false,
    ),
    spec(
        "AXON_LLM_COMPLETION_TIMEOUT_SECS",
        KeepEnv,
        Both,
        None,
        Canonical,
        false,
    ),
    spec(
        "AXON_OPENAI_BASE_URL",
        KeepEnv,
        Both,
        None,
        Canonical,
        false,
    ),
    spec("AXON_OPENAI_API_KEY", KeepEnv, Both, None, Canonical, true),
    spec("AXON_CODEX_MODEL", KeepEnv, Both, None, Canonical, false),
    spec(
        "AXON_SYNTHESIS_CODEX_MODEL",
        KeepEnv,
        Both,
        None,
        Canonical,
        false,
    ),
    spec(
        "AXON_CODEX_COMPLETION_CONCURRENCY",
        KeepEnv,
        Both,
        None,
        Canonical,
        false,
    ),
    spec(
        "AXON_CODEX_LOAD_USER_CONFIG",
        KeepEnv,
        Both,
        None,
        Canonical,
        false,
    ),
    spec(
        "AXON_SYNTHESIS_OPENAI_MODEL",
        KeepEnv,
        Both,
        None,
        Canonical,
        false,
    ),
    spec("AXON_OPENAI_MODEL", KeepEnv, Both, None, Canonical, false),
    spec(
        "AXON_CHAT_OPENAI_MODEL",
        KeepEnv,
        Both,
        None,
        Canonical,
        false,
    ),
    spec("GEMINI_API_KEY", KeepEnv, Both, None, Canonical, true),
    spec("GOOGLE_API_KEY", KeepEnv, Both, None, Canonical, true),
    spec(
        "AXON_WEB_API_TOKEN",
        KeepEnv,
        ContainerRequired,
        None,
        Canonical,
        true,
    ),
    spec("AXON_CHROME_PROXY", KeepEnv, Both, None, Canonical, false),
];
