-- ---------------------------------------------------------------------------
-- The seven unified-ledger contract tables (`sources`, `source_generations`,
-- `source_manifests`, `source_items`, `document_status`, `cleanup_debt`,
-- `leases`) live in crates/axon-ledger/src/migrations/0001_ledger_lifecycle.sql.
-- The composed cross-crate migration runner (crates/axon-jobs/src/migrations.rs)
-- applies axon-ledger's migration FIRST against the SAME pool, so `axon-ledger`
-- is the SOLE creator of the contract tables (schema-contract.md).
-- `jobs.source_id` (migration 0018) FKs `sources(source_id)` because the ledger
-- set runs before the jobs set.
--
-- The legacy `axon_source_*` tables (`axon_source_sources`,
-- `axon_source_manifest_items`, `axon_source_cleanup_debt`) that previously
-- backed the retired `axon-source-ledger` crate were removed here (bead 5mlrh):
-- axon-ledger is now the sole source ledger. This migration is intentionally a
-- no-op comment marker — deleting the file would renumber the applied-migration
-- history and break checksum pinning, so the file is kept but creates nothing.
-- ---------------------------------------------------------------------------
