//! Closed `GraphEdgeKind` registry for the SourceGraph.
//!
//! The canonical edge-kind list is defined in
//! `docs/pipeline-unification/sources/source-graph.md` ("Edge Kinds"). This
//! enum encodes that closed registry exactly. The graph store rejects any edge
//! whose `edge_kind` string does not parse into one of these variants
//! ("graph store rejects unknown kinds before write" — graph-schema.md).

use std::fmt;
use std::str::FromStr;

use serde::{Deserialize, Serialize};

use crate::error::graph_validation_error;

/// A closed edge kind from the canonical SourceGraph registry.
///
/// Serialized as the exact registry name (e.g. `repo_has_docs`,
/// `session_mentions_repo`). Deserialization of an unknown string fails.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum GraphEdgeKind {
    AliasOf,
    CanonicalizesTo,
    OfficialFor,
    DerivedFrom,
    Mirrors,
    PackageHasRepo,
    PackageHasDocs,
    PackageHasVersion,
    PackageOwnedBy,
    RepoDeclaresDependency,
    RepoLocksDependencyVersion,
    RepoUsesContainerImage,
    RepoUsesGithubAction,
    RepoUsesToolchain,
    RepoUsesSystemPackage,
    RepoUsesTerraformProvider,
    RepoUsesHelmChart,
    RepoDeclaresService,
    ServiceUsesImage,
    ServiceExposesEndpoint,
    ServiceMountsVolume,
    ServiceRequiresEnv,
    RepoDeclaresEnvVar,
    RepoDeclaresApi,
    ServiceExposesApi,
    ApiUsesProtocol,
    ApiHasOperation,
    OperationUsesSchema,
    SchemaHasField,
    PackageGeneratesApiClient,
    RepoHasDocs,
    RepoHasWiki,
    RepoOwnedBy,
    RepoHasBranch,
    BranchPointsToCommit,
    CommitContainsFile,
    LocalCheckoutTracksRepo,
    LocalCheckoutAtCommit,
    DocsSiteContainsPage,
    WebOriginHasDocs,
    FeedContainsEntry,
    YoutubeChannelHasVideo,
    YoutubePlaylistHasVideo,
    SubredditHasThread,
    SessionHasTurn,
    SessionAboutRepo,
    SessionMentionsRepo,
    SessionMentionsSource,
    SessionMentionsIssue,
    SessionMentionsPr,
    SessionMentionsPackage,
    SessionProducedDecision,
    SessionInvokedAgent,
    AgentInvocationUsesAgent,
    AgentInvocationUsedSkill,
    AgentInvocationUsedTool,
    AgentInvocationProducedArtifact,
    AgentInvocationRelatedToRepo,
    AgentInvocationRelatedToIssue,
    SessionInvokedSkill,
    SkillInvocationUsesSkill,
    SkillInvocationProducedArtifact,
    SkillInvocationRelatedToRepo,
    SkillInvocationRelatedToIssue,
    TurnInvokedTool,
    TurnInvokedSkill,
    ToolCallUsesTool,
    ToolCallTouchedFile,
    ToolCallProducedArtifact,
    ToolCallReadResource,
    ToolCallMutatedResource,
    ToolCallRelatedToRepo,
    ToolCallRelatedToIssue,
    MemoryRelatesTo,
    MemorySupersedes,
    MemoryContradicts,
    MemoryCompacts,
    MemoryAboutSource,
    MemoryAboutFile,
    MemoryAboutIssue,
    MemoryUsedInContext,
    SourceProducedArtifact,
    SourceIndexedAs,
}

impl GraphEdgeKind {
    /// Every edge kind in registry order.
    pub const ALL: &'static [GraphEdgeKind] = &[
        Self::AliasOf,
        Self::CanonicalizesTo,
        Self::OfficialFor,
        Self::DerivedFrom,
        Self::Mirrors,
        Self::PackageHasRepo,
        Self::PackageHasDocs,
        Self::PackageHasVersion,
        Self::PackageOwnedBy,
        Self::RepoDeclaresDependency,
        Self::RepoLocksDependencyVersion,
        Self::RepoUsesContainerImage,
        Self::RepoUsesGithubAction,
        Self::RepoUsesToolchain,
        Self::RepoUsesSystemPackage,
        Self::RepoUsesTerraformProvider,
        Self::RepoUsesHelmChart,
        Self::RepoDeclaresService,
        Self::ServiceUsesImage,
        Self::ServiceExposesEndpoint,
        Self::ServiceMountsVolume,
        Self::ServiceRequiresEnv,
        Self::RepoDeclaresEnvVar,
        Self::RepoDeclaresApi,
        Self::ServiceExposesApi,
        Self::ApiUsesProtocol,
        Self::ApiHasOperation,
        Self::OperationUsesSchema,
        Self::SchemaHasField,
        Self::PackageGeneratesApiClient,
        Self::RepoHasDocs,
        Self::RepoHasWiki,
        Self::RepoOwnedBy,
        Self::RepoHasBranch,
        Self::BranchPointsToCommit,
        Self::CommitContainsFile,
        Self::LocalCheckoutTracksRepo,
        Self::LocalCheckoutAtCommit,
        Self::DocsSiteContainsPage,
        Self::WebOriginHasDocs,
        Self::FeedContainsEntry,
        Self::YoutubeChannelHasVideo,
        Self::YoutubePlaylistHasVideo,
        Self::SubredditHasThread,
        Self::SessionHasTurn,
        Self::SessionAboutRepo,
        Self::SessionMentionsRepo,
        Self::SessionMentionsSource,
        Self::SessionMentionsIssue,
        Self::SessionMentionsPr,
        Self::SessionMentionsPackage,
        Self::SessionProducedDecision,
        Self::SessionInvokedAgent,
        Self::AgentInvocationUsesAgent,
        Self::AgentInvocationUsedSkill,
        Self::AgentInvocationUsedTool,
        Self::AgentInvocationProducedArtifact,
        Self::AgentInvocationRelatedToRepo,
        Self::AgentInvocationRelatedToIssue,
        Self::SessionInvokedSkill,
        Self::SkillInvocationUsesSkill,
        Self::SkillInvocationProducedArtifact,
        Self::SkillInvocationRelatedToRepo,
        Self::SkillInvocationRelatedToIssue,
        Self::TurnInvokedTool,
        Self::TurnInvokedSkill,
        Self::ToolCallUsesTool,
        Self::ToolCallTouchedFile,
        Self::ToolCallProducedArtifact,
        Self::ToolCallReadResource,
        Self::ToolCallMutatedResource,
        Self::ToolCallRelatedToRepo,
        Self::ToolCallRelatedToIssue,
        Self::MemoryRelatesTo,
        Self::MemorySupersedes,
        Self::MemoryContradicts,
        Self::MemoryCompacts,
        Self::MemoryAboutSource,
        Self::MemoryAboutFile,
        Self::MemoryAboutIssue,
        Self::MemoryUsedInContext,
        Self::SourceProducedArtifact,
        Self::SourceIndexedAs,
    ];

    /// The exact registry name (snake_case) for this edge kind.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::AliasOf => "alias_of",
            Self::CanonicalizesTo => "canonicalizes_to",
            Self::OfficialFor => "official_for",
            Self::DerivedFrom => "derived_from",
            Self::Mirrors => "mirrors",
            Self::PackageHasRepo => "package_has_repo",
            Self::PackageHasDocs => "package_has_docs",
            Self::PackageHasVersion => "package_has_version",
            Self::PackageOwnedBy => "package_owned_by",
            Self::RepoDeclaresDependency => "repo_declares_dependency",
            Self::RepoLocksDependencyVersion => "repo_locks_dependency_version",
            Self::RepoUsesContainerImage => "repo_uses_container_image",
            Self::RepoUsesGithubAction => "repo_uses_github_action",
            Self::RepoUsesToolchain => "repo_uses_toolchain",
            Self::RepoUsesSystemPackage => "repo_uses_system_package",
            Self::RepoUsesTerraformProvider => "repo_uses_terraform_provider",
            Self::RepoUsesHelmChart => "repo_uses_helm_chart",
            Self::RepoDeclaresService => "repo_declares_service",
            Self::ServiceUsesImage => "service_uses_image",
            Self::ServiceExposesEndpoint => "service_exposes_endpoint",
            Self::ServiceMountsVolume => "service_mounts_volume",
            Self::ServiceRequiresEnv => "service_requires_env",
            Self::RepoDeclaresEnvVar => "repo_declares_env_var",
            Self::RepoDeclaresApi => "repo_declares_api",
            Self::ServiceExposesApi => "service_exposes_api",
            Self::ApiUsesProtocol => "api_uses_protocol",
            Self::ApiHasOperation => "api_has_operation",
            Self::OperationUsesSchema => "operation_uses_schema",
            Self::SchemaHasField => "schema_has_field",
            Self::PackageGeneratesApiClient => "package_generates_api_client",
            Self::RepoHasDocs => "repo_has_docs",
            Self::RepoHasWiki => "repo_has_wiki",
            Self::RepoOwnedBy => "repo_owned_by",
            Self::RepoHasBranch => "repo_has_branch",
            Self::BranchPointsToCommit => "branch_points_to_commit",
            Self::CommitContainsFile => "commit_contains_file",
            Self::LocalCheckoutTracksRepo => "local_checkout_tracks_repo",
            Self::LocalCheckoutAtCommit => "local_checkout_at_commit",
            Self::DocsSiteContainsPage => "docs_site_contains_page",
            Self::WebOriginHasDocs => "web_origin_has_docs",
            Self::FeedContainsEntry => "feed_contains_entry",
            Self::YoutubeChannelHasVideo => "youtube_channel_has_video",
            Self::YoutubePlaylistHasVideo => "youtube_playlist_has_video",
            Self::SubredditHasThread => "subreddit_has_thread",
            Self::SessionHasTurn => "session_has_turn",
            Self::SessionAboutRepo => "session_about_repo",
            Self::SessionMentionsRepo => "session_mentions_repo",
            Self::SessionMentionsSource => "session_mentions_source",
            Self::SessionMentionsIssue => "session_mentions_issue",
            Self::SessionMentionsPr => "session_mentions_pr",
            Self::SessionMentionsPackage => "session_mentions_package",
            Self::SessionProducedDecision => "session_produced_decision",
            Self::SessionInvokedAgent => "session_invoked_agent",
            Self::AgentInvocationUsesAgent => "agent_invocation_uses_agent",
            Self::AgentInvocationUsedSkill => "agent_invocation_used_skill",
            Self::AgentInvocationUsedTool => "agent_invocation_used_tool",
            Self::AgentInvocationProducedArtifact => "agent_invocation_produced_artifact",
            Self::AgentInvocationRelatedToRepo => "agent_invocation_related_to_repo",
            Self::AgentInvocationRelatedToIssue => "agent_invocation_related_to_issue",
            Self::SessionInvokedSkill => "session_invoked_skill",
            Self::SkillInvocationUsesSkill => "skill_invocation_uses_skill",
            Self::SkillInvocationProducedArtifact => "skill_invocation_produced_artifact",
            Self::SkillInvocationRelatedToRepo => "skill_invocation_related_to_repo",
            Self::SkillInvocationRelatedToIssue => "skill_invocation_related_to_issue",
            Self::TurnInvokedTool => "turn_invoked_tool",
            Self::TurnInvokedSkill => "turn_invoked_skill",
            Self::ToolCallUsesTool => "tool_call_uses_tool",
            Self::ToolCallTouchedFile => "tool_call_touched_file",
            Self::ToolCallProducedArtifact => "tool_call_produced_artifact",
            Self::ToolCallReadResource => "tool_call_read_resource",
            Self::ToolCallMutatedResource => "tool_call_mutated_resource",
            Self::ToolCallRelatedToRepo => "tool_call_related_to_repo",
            Self::ToolCallRelatedToIssue => "tool_call_related_to_issue",
            Self::MemoryRelatesTo => "memory_relates_to",
            Self::MemorySupersedes => "memory_supersedes",
            Self::MemoryContradicts => "memory_contradicts",
            Self::MemoryCompacts => "memory_compacts",
            Self::MemoryAboutSource => "memory_about_source",
            Self::MemoryAboutFile => "memory_about_file",
            Self::MemoryAboutIssue => "memory_about_issue",
            Self::MemoryUsedInContext => "memory_used_in_context",
            Self::SourceProducedArtifact => "source_produced_artifact",
            Self::SourceIndexedAs => "source_indexed_as",
        }
    }
}

impl fmt::Display for GraphEdgeKind {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

impl FromStr for GraphEdgeKind {
    type Err = axon_api::source::ApiError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        Self::ALL
            .iter()
            .copied()
            .find(|kind| kind.as_str() == value)
            .ok_or_else(|| graph_validation_error(format!("unknown graph edge kind: {value:?}")))
    }
}

#[cfg(test)]
#[path = "edge_tests.rs"]
mod tests;
