//! Continuation of `crate_contracts_spec.rs`'s `CRATE_CONTRACTS` table — split
//! purely to stay under the repo's 500-line monolith cap. See that file's
//! module doc for what the fields mean and [`super::all_crate_contracts`] to
//! iterate the combined table.

use super::crate_contracts_spec::CrateContract;

pub const CRATE_CONTRACTS_CONT: &[CrateContract] = &[
    CrateContract {
        name: "axon-jobs",
        modules: &[],
        // README: axon-jobs must not depend on axon-services (contradiction-review.md:
        // "axon-jobs may not depend on axon-services" — the composition layer injects
        // worker functions instead). Legacy crates are intentionally NOT forbidden here:
        // axon-jobs' worker runners currently wrap axon-crawl/axon-vector/axon-ingest/
        // axon-extract behavior pre-cutover.
        forbidden_axon_deps: &["axon-services", "axon-cli", "axon-mcp", "axon-web"],
    },
    CrateContract {
        name: "axon-ledger",
        modules: &[
            "store",
            "sqlite",
            "migration",
            "source",
            "item",
            "manifest",
            "diff",
            "generation",
            "document_status",
            "lease",
            "cleanup_debt",
            "transaction",
            "testing",
        ],
        forbidden_axon_deps: &[
            "axon-adapters",
            "axon-services",
            "axon-cli",
            "axon-mcp",
            "axon-web",
            "axon-vector",
            "axon-crawl",
            "axon-ingest",
            "axon-extract",
            "axon-code-index",
        ],
    },
    CrateContract {
        name: "axon-llm",
        modules: &[
            "provider",
            "capability",
            "completion",
            "stream",
            "prompt",
            "openai_compat",
            "codex",
            "gemini",
            "fake",
            "testing",
        ],
        forbidden_axon_deps: &[
            "axon-retrieval",
            "axon-vectors",
            "axon-cli",
            "axon-mcp",
            "axon-web",
            "axon-vector",
            "axon-crawl",
            "axon-ingest",
            "axon-extract",
            "axon-code-index",
        ],
    },
    CrateContract {
        name: "axon-mcp",
        modules: &[],
        forbidden_axon_deps: &["axon-cli", "axon-web"],
    },
    CrateContract {
        name: "axon-memory",
        modules: &[
            "store",
            "sqlite",
            "migration",
            "record",
            "link",
            "decay",
            "review",
            "recall",
            "context",
            "graph",
            "testing",
        ],
        forbidden_axon_deps: &[
            "axon-llm",
            "axon-cli",
            "axon-mcp",
            "axon-web",
            "axon-vector",
            "axon-crawl",
            "axon-ingest",
            "axon-extract",
            "axon-code-index",
        ],
    },
    CrateContract {
        name: "axon-observe",
        modules: &[
            "event",
            "phase",
            "heartbeat",
            "progress",
            "metric",
            "span",
            "log",
            "collector",
            "testing",
        ],
        forbidden_axon_deps: &[
            "axon-jobs",
            "axon-adapters",
            "axon-vectors",
            "axon-embedding",
            "axon-llm",
            "axon-cli",
            "axon-mcp",
            "axon-web",
            "axon-vector",
            "axon-crawl",
            "axon-ingest",
            "axon-extract",
            "axon-code-index",
        ],
    },
    CrateContract {
        name: "axon-parse",
        modules: &[
            "parser",
            "registry",
            "facts",
            "graph_candidate",
            "code",
            "manifest",
            "schema",
            "session",
            "tool",
            "env",
            "docker",
            "config",
            "testing",
        ],
        forbidden_axon_deps: &[
            "axon-vectors",
            "axon-embedding",
            "axon-llm",
            "axon-ledger",
            "axon-graph",
            "axon-cli",
            "axon-mcp",
            "axon-web",
            "axon-vector",
            "axon-crawl",
            "axon-ingest",
            "axon-extract",
            "axon-code-index",
        ],
    },
    CrateContract {
        name: "axon-prune",
        modules: &[
            "plan",
            "executor",
            "debt",
            "generation",
            "orphan",
            "dedupe",
            "receipt",
            "safety",
            "testing",
        ],
        forbidden_axon_deps: &[
            "axon-adapters",
            "axon-embedding",
            "axon-llm",
            "axon-cli",
            "axon-mcp",
            "axon-web",
            "axon-vector",
            "axon-crawl",
            "axon-ingest",
            "axon-extract",
            "axon-code-index",
        ],
    },
    CrateContract {
        name: "axon-retrieval",
        modules: &[
            "engine", "plan", "query", "filter", "rank", "context", "citation", "memory", "graph",
            "testing",
        ],
        forbidden_axon_deps: &[
            "axon-llm",
            "axon-cli",
            "axon-mcp",
            "axon-web",
            "axon-vector",
            "axon-crawl",
            "axon-ingest",
            "axon-extract",
            "axon-code-index",
        ],
    },
    CrateContract {
        name: "axon-route",
        modules: &[
            "resolver",
            "router",
            "canonical",
            "source_id",
            "scope",
            "authority",
            "alias",
            "capability",
            "testing",
        ],
        forbidden_axon_deps: &[
            "axon-ledger",
            "axon-parse",
            "axon-vectors",
            "axon-services",
            "axon-cli",
            "axon-mcp",
            "axon-web",
            "axon-vector",
            "axon-crawl",
            "axon-ingest",
            "axon-extract",
            "axon-code-index",
        ],
    },
    CrateContract {
        name: "axon-services",
        modules: &[],
        // Legacy crates intentionally NOT forbidden: axon-services currently
        // composes axon-crawl/axon-vector/axon-ingest/axon-extract pre-cutover.
        forbidden_axon_deps: &["axon-cli", "axon-mcp", "axon-web"],
    },
    CrateContract {
        name: "axon-vectors",
        modules: &[
            "store",
            "qdrant",
            "collection",
            "point",
            "payload",
            "filter",
            "query",
            "health",
            "testing",
        ],
        forbidden_axon_deps: &[
            "axon-embedding",
            "axon-adapters",
            "axon-parse",
            "axon-jobs",
            "axon-llm",
            "axon-cli",
            "axon-mcp",
            "axon-web",
            "axon-vector",
            "axon-crawl",
            "axon-ingest",
            "axon-extract",
            "axon-code-index",
        ],
    },
    CrateContract {
        name: "axon-web",
        modules: &[],
        forbidden_axon_deps: &["axon-cli", "axon-mcp"],
    },
];
