//! `cargo xtask check-dep-graph` / `gen-dep-graph` — crate dependency-graph
//! snapshot + acyclicity guard.
//!
//! The workspace layering is an acyclic DAG (`axon-error → axon-api → axon-core →
//! domain crates → axon-jobs → axon-services → transports`). This generates a
//! deterministic snapshot of every workspace crate's intra-workspace **normal**
//! dependencies into `docs/reference/crate-dependency-graph.md`, and:
//!   - fails if the committed snapshot drifts from the live Cargo.toml graph
//!     (so a new/removed edge must be reviewed), and
//!   - fails if a cycle appears in the normal-dependency graph (forbidden edge).
//!
//! Dev-dependencies are intentionally excluded from the acyclicity graph — Cargo
//! permits dev-dependency cycles (a crate's tests may depend on a sibling that
//! depends back), so counting them would produce false cycle reports.
//!
//! This is the "crate dependency graph snapshots so forbidden edges fail CI"
//! deliverable from the schema/docs generator contract.

use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;

use anyhow::{Context, Result, bail};

const SNAPSHOT_PATH: &str = "docs/reference/crate-dependency-graph.md";

/// crate name -> its intra-workspace normal dependencies (sorted).
type Graph = BTreeMap<String, BTreeSet<String>>;

pub fn check(root: &Path) -> Result<()> {
    let graph = build_graph(root)?;
    check_acyclic(&graph)?;
    let expected = render(&graph);
    let snapshot = root.join(SNAPSHOT_PATH);
    let actual = std::fs::read_to_string(&snapshot).unwrap_or_default();
    if actual != expected {
        bail!(
            "check-dep-graph: {SNAPSHOT_PATH} is out of date with the live crate graph.\n\
             Run `cargo xtask gen-dep-graph` and commit the result."
        );
    }
    println!(
        "check-dep-graph: {} crates, acyclic, snapshot in sync.",
        graph.len()
    );
    Ok(())
}

pub fn write(root: &Path) -> Result<()> {
    let graph = build_graph(root)?;
    check_acyclic(&graph)?;
    let out = root.join(SNAPSHOT_PATH);
    if let Some(dir) = out.parent() {
        std::fs::create_dir_all(dir)?;
    }
    std::fs::write(&out, render(&graph))?;
    println!(
        "gen-dep-graph: wrote {SNAPSHOT_PATH} ({} crates).",
        graph.len()
    );
    Ok(())
}

/// Parse every `crates/*/Cargo.toml` into a normal-dependency graph over
/// workspace (`axon-*`) crates.
pub fn build_graph(root: &Path) -> Result<Graph> {
    let crates_dir = root.join("crates");
    let mut names = BTreeSet::new();
    let mut manifests = Vec::new();
    for entry in std::fs::read_dir(&crates_dir)
        .with_context(|| format!("reading {}", crates_dir.display()))?
    {
        let path = entry?.path();
        let manifest = path.join("Cargo.toml");
        if !manifest.is_file() {
            continue;
        }
        let text = std::fs::read_to_string(&manifest)?;
        let value: toml::Value =
            toml::from_str(&text).with_context(|| format!("parsing {}", manifest.display()))?;
        let name = value
            .get("package")
            .and_then(|p| p.get("name"))
            .and_then(|n| n.as_str())
            .with_context(|| format!("{} has no [package].name", manifest.display()))?
            .to_string();
        names.insert(name.clone());
        manifests.push((name, value));
    }

    let mut graph: Graph = BTreeMap::new();
    for (name, value) in &manifests {
        let mut deps = BTreeSet::new();
        // Normal + build dependencies define the compile-time DAG. Dev-deps excluded.
        for table in ["dependencies", "build-dependencies"] {
            if let Some(t) = value.get(table).and_then(|t| t.as_table()) {
                for dep in t.keys() {
                    if dep != name && names.contains(dep) {
                        deps.insert(dep.clone());
                    }
                }
            }
        }
        graph.insert(name.clone(), deps);
    }
    Ok(graph)
}

fn render(graph: &Graph) -> String {
    let mut out = String::from(
        "# Crate Dependency Graph\n\n\
         Generated by `cargo xtask gen-dep-graph`. Normal + build dependencies over \
         workspace crates (dev-dependencies excluded). The graph is acyclic.\n\n",
    );
    for (crate_name, deps) in graph {
        if deps.is_empty() {
            out.push_str(&format!("- `{crate_name}` → (no workspace deps)\n"));
        } else {
            let list = deps
                .iter()
                .map(|d| format!("`{d}`"))
                .collect::<Vec<_>>()
                .join(", ");
            out.push_str(&format!("- `{crate_name}` → {list}\n"));
        }
    }
    out
}

/// DFS cycle detection over the normal-dependency graph.
fn check_acyclic(graph: &Graph) -> Result<()> {
    #[derive(Clone, Copy, PartialEq)]
    enum Mark {
        Unvisited,
        InProgress,
        Done,
    }
    let mut marks: BTreeMap<&str, Mark> = graph
        .keys()
        .map(|k| (k.as_str(), Mark::Unvisited))
        .collect();
    let mut stack = Vec::new();
    for start in graph.keys() {
        visit(start, graph, &mut marks, &mut stack)?;
    }
    return Ok(());

    fn visit<'a>(
        node: &'a str,
        graph: &'a Graph,
        marks: &mut BTreeMap<&'a str, Mark>,
        stack: &mut Vec<&'a str>,
    ) -> Result<()> {
        match marks.get(node).copied().unwrap_or(Mark::Unvisited) {
            Mark::Done => return Ok(()),
            Mark::InProgress => {
                let cycle_from = stack.iter().position(|n| *n == node).unwrap_or(0);
                let mut path: Vec<&str> = stack[cycle_from..].to_vec();
                path.push(node);
                bail!("check-dep-graph: dependency cycle: {}", path.join(" → "));
            }
            Mark::Unvisited => {}
        }
        marks.insert(node, Mark::InProgress);
        stack.push(node);
        if let Some(deps) = graph.get(node) {
            for dep in deps {
                visit(dep.as_str(), graph, marks, stack)?;
            }
        }
        stack.pop();
        marks.insert(node, Mark::Done);
        Ok(())
    }
}

#[cfg(test)]
#[path = "dep_graph_tests.rs"]
mod tests;
