//! `cargo xtask check-public-api` / `gen-public-api` — per-crate public-API
//! surface snapshot.
//!
//! Generates a deterministic snapshot of every workspace crate's **crate-public**
//! API surface (items reachable via an all-`pub` module path from `src/lib.rs`)
//! into `docs/reference/public-api-surface.md`, and fails if the committed
//! snapshot drifts from the live source — so any change to a crate's public
//! surface (a new/removed/renamed `pub` item, module, or re-export) must be
//! reviewed and re-committed.
//!
//! This is the "per-crate public-API doc generator" deliverable from the
//! schema/docs generator contract, complementing the crate-dependency-graph
//! snapshot ([`super::dep_graph`]).

use std::collections::BTreeMap;
use std::path::Path;

use anyhow::{Context, Result, bail};

use self::extract::{ApiEntry, extract_crate};

mod extract;

const SNAPSHOT_PATH: &str = "docs/reference/public-api-surface.md";

/// crate name -> its sorted public API entries.
type Surface = BTreeMap<String, Vec<ApiEntry>>;

pub fn check(root: &Path) -> Result<()> {
    let surface = build(root)?;
    let expected = render(&surface);
    let snapshot = root.join(SNAPSHOT_PATH);
    let actual = std::fs::read_to_string(&snapshot).unwrap_or_default();
    if actual != expected {
        bail!(
            "check-public-api: {SNAPSHOT_PATH} is out of date with the live public API surface.\n\
             Run `cargo xtask gen-public-api` and commit the result."
        );
    }
    let items: usize = surface.values().map(Vec::len).sum();
    println!(
        "check-public-api: {} crates, {items} public items, snapshot in sync.",
        surface.len()
    );
    Ok(())
}

pub fn write(root: &Path) -> Result<()> {
    let surface = build(root)?;
    let out = root.join(SNAPSHOT_PATH);
    if let Some(dir) = out.parent() {
        std::fs::create_dir_all(dir)?;
    }
    std::fs::write(&out, render(&surface))?;
    let items: usize = surface.values().map(Vec::len).sum();
    println!(
        "gen-public-api: wrote {SNAPSHOT_PATH} ({} crates, {items} public items).",
        surface.len()
    );
    Ok(())
}

/// Extract the public API surface of every `crates/*` library crate, keyed by
/// its `[package].name`.
fn build(root: &Path) -> Result<Surface> {
    let crates_dir = root.join("crates");
    let mut surface: Surface = BTreeMap::new();
    for entry in std::fs::read_dir(&crates_dir)
        .with_context(|| format!("reading {}", crates_dir.display()))?
    {
        let crate_dir = entry?.path();
        let manifest = crate_dir.join("Cargo.toml");
        if !manifest.is_file() {
            continue;
        }
        let text = std::fs::read_to_string(&manifest)?;
        let value: toml::Value =
            toml::from_str(&text).with_context(|| format!("parsing {}", manifest.display()))?;
        let name = value
            .get("package")
            .and_then(|p| p.get("name"))
            .and_then(|n| n.as_str())
            .with_context(|| format!("{} has no [package].name", manifest.display()))?
            .to_string();
        let entries = extract_crate(&crate_dir)
            .with_context(|| format!("extracting public API of {name}"))?;
        surface.insert(name, entries);
    }
    Ok(surface)
}

fn render(surface: &Surface) -> String {
    let mut out = String::from(
        "# Public API Surface\n\n\
         Generated by `cargo xtask gen-public-api`. Lists each workspace crate's \
         **crate-public** items — those reachable via an all-`pub` module path from \
         `src/lib.rs`. `pub(crate)`/`pub(super)`/`pub(in …)` visibilities and \
         `#[cfg(test)]` modules are excluded. Binary-only crates (no `lib.rs`) show \
         no surface.\n",
    );
    for (crate_name, entries) in surface {
        out.push_str(&format!("\n## {crate_name}\n\n"));
        if entries.is_empty() {
            out.push_str("_(no crate-public library surface)_\n");
            continue;
        }
        for e in entries {
            out.push_str(&format!("- `{}` ({})\n", e.path, e.kind));
        }
    }
    out
}

#[cfg(test)]
#[path = "public_api_tests.rs"]
mod tests;
