use super::*;
use std::fs;
use std::path::{Path, PathBuf};
use tempfile::TempDir;

#[test]
fn reads_component_manifest() {
    let root = repo_root();
    let manifest = load_manifest(&root).expect("manifest loads");
    assert_eq!(manifest.schema_version, 1);
    assert_eq!(manifest.components.len(), 4);
    let actual = manifest
        .components
        .iter()
        .map(|component| {
            (
                component.id.as_str(),
                component.tag_prefix.as_str(),
                component.release_please_path.as_str(),
                component.release_workflow.as_str(),
                component.shipping_paths.as_slice(),
            )
        })
        .collect::<Vec<_>>();
    assert_eq!(
        actual,
        [
            (
                "cli",
                "v",
                ".",
                "release.yml",
                &[
                    "src".to_owned(),
                    "crates".to_owned(),
                    "Cargo.toml".to_owned(),
                    "Cargo.lock".to_owned(),
                    "build.rs".to_owned(),
                    "migrations".to_owned(),
                    "apps/web".to_owned(),
                    "rust-toolchain.toml".to_owned(),
                    "vendor".to_owned(),
                ][..],
            ),
            (
                "palette",
                "palette-v",
                "apps/palette-tauri",
                "palette-release.yml",
                &["apps/palette-tauri".to_owned()][..],
            ),
            (
                "android",
                "android-v",
                "apps/android",
                "android-release.yml",
                &["apps/android".to_owned()][..],
            ),
            (
                "chrome",
                "chrome-ext-v",
                "apps/chrome-extension",
                "chrome-extension-release.yml",
                &["apps/chrome-extension".to_owned()][..],
            ),
        ]
    );
}

#[test]
fn cargo_package_version_reader_ignores_workspace_version() {
    let content = r#"
[workspace.package]
version = "9.9.9"

[package]
name = "axon"
version = "1.2.3"
"#;
    assert_eq!(
        read_cargo_package_version(content, Some("axon")).expect("version"),
        "1.2.3"
    );
}

#[test]
fn read_workspace_package_version_present_and_absent() {
    let with = r#"[workspace.package]
version = "5.19.0"

[package]
name = "axon"
version = "5.19.0"
"#;
    assert_eq!(
        read_workspace_package_version(with).expect("parse"),
        Some("5.19.0".to_owned())
    );
    let without = r#"[package]
name = "axon-palette-tauri"
version = "5.10.2"
"#;
    assert_eq!(
        read_workspace_package_version(without).expect("parse"),
        None
    );
}

#[test]
fn workspace_package_version_must_equal_product_version() {
    let temp = TempDir::new().expect("tempdir");
    let manifest = |ws: &str, pkg: &str| {
        format!(
            "[workspace.package]\nversion = \"{ws}\"\n\n[package]\nname = \"axon\"\nversion = \"{pkg}\"\n"
        )
    };
    let path = temp.path().join("Cargo.toml");

    fs::write(&path, manifest("5.19.0", "5.19.0")).unwrap();
    check_workspace_package_version(temp.path(), "5.19.0").expect("matching versions pass");

    fs::write(&path, manifest("5.18.0", "5.19.0")).unwrap();
    let err = check_workspace_package_version(temp.path(), "5.19.0")
        .expect_err("drifted workspace version must fail");
    assert!(err.to_string().contains("[workspace.package] version"));

    // No [workspace.package] table → guard is a no-op.
    fs::write(&path, "[package]\nname = \"axon\"\nversion = \"5.19.0\"\n").unwrap();
    check_workspace_package_version(temp.path(), "5.19.0").expect("no workspace table is a no-op");
}

#[test]
fn cargo_lock_package_version_reader_targets_one_package() {
    let content = r#"# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "axon"
version = "1.2.3"

[[package]]
name = "xtask"
version = "0.1.0"
"#;
    assert_eq!(
        read_cargo_lock_package_version(content, Some("axon")).expect("version"),
        "1.2.3"
    );
}

#[test]
fn json_version_reader_handles_pretty_and_compact_json() {
    assert_eq!(
        read_json_version(
            r#"{ "name": "axon", "version": "1.2.3" }"#,
            Some("/version")
        )
        .expect("pretty"),
        "1.2.3"
    );
    assert_eq!(
        read_json_version(r#"{"name":"axon","version":"1.2.4"}"#, Some("/version"))
            .expect("compact"),
        "1.2.4"
    );
    assert_eq!(
        read_json_version(r#"{"info":{"version":"1.2.5"}}"#, Some("/info/version"))
            .expect("nested"),
        "1.2.5"
    );
}

#[test]
fn json_version_reader_uses_configured_pointer() {
    let content = r#"{"version":"0.1.0","info":{"version":"1.2.5"}}"#;
    assert_eq!(
        read_json_version(content, Some("/info/version")).expect("openapi info version"),
        "1.2.5"
    );
}

#[test]
fn npm_package_lock_version_reader_uses_root_package() {
    let content = r#"{
  "name": "@axon/admin-panel",
  "version": "1.2.3",
  "lockfileVersion": 3,
  "packages": {
    "": {
      "name": "@axon/admin-panel",
      "version": "1.2.3"
    }
  }
}"#;
    assert_eq!(
        read_npm_package_lock_version(content, Some("@axon/admin-panel")).expect("version"),
        "1.2.3"
    );
}

#[test]
fn gradle_version_reader_extracts_version_name_and_code() {
    let content = r#"
android {
    defaultConfig {
        versionCode = 42
        versionName = "1.3.2"
    }
}
"#;
    assert_eq!(read_gradle_version_name(content).expect("name"), "1.3.2");
    assert_eq!(read_gradle_version_code(content).expect("code"), 42);
}

#[test]
fn gradle_version_code_enforces_google_play_bounds() {
    assert!(read_gradle_version_code("versionCode = 1\n").is_ok());
    assert!(read_gradle_version_code("versionCode = 2100000000\n").is_ok());
    let zero = read_gradle_version_code("versionCode = 0\n").expect_err("zero invalid");
    assert!(zero.to_string().contains("between 1 and"));
    let too_large =
        read_gradle_version_code("versionCode = 2100000001\n").expect_err("too large invalid");
    assert!(too_large.to_string().contains("between 1 and"));
}

#[test]
fn gradle_version_code_bump_rejects_cap() {
    let error = increment_gradle_version_code("versionCode = 2100000000\n")
        .expect_err("cap cannot be bumped");
    assert!(error.to_string().contains("between 1 and"));
}

#[test]
fn cli_parity_requires_changelog_and_web_versions() {
    let fixture = Fixture::new();
    fs::write(fixture.path("CHANGELOG.md"), "# Changelog\n\n## [0.9.9]\n").unwrap();
    fs::write(
        fixture.path("apps/web/package.json"),
        r#"{"version":"0.9.9"}"#,
    )
    .unwrap();
    let manifest = load_manifest(fixture.root()).unwrap();
    let cli = manifest
        .components
        .iter()
        .find(|component| component.id == "cli")
        .unwrap();
    let errors = check_component_parity(fixture.root(), cli, "1.0.0").unwrap();
    assert!(errors.iter().any(|error| error.contains("CHANGELOG.md")));
    assert!(
        errors
            .iter()
            .any(|error| error.contains("apps/web/package.json"))
    );
}

#[test]
fn plugin_json_version_is_rejected() {
    let fixture = Fixture::new();
    fs::write(
        fixture.path("plugins/axon/.claude-plugin/plugin.json"),
        r#"{"name":"axon","version":"1.0.0"}"#,
    )
    .unwrap();
    let manifest = load_manifest(fixture.root()).unwrap();
    let cli = manifest
        .components
        .iter()
        .find(|component| component.id == "cli")
        .unwrap();
    let errors = check_component_parity(fixture.root(), cli, "1.0.0").unwrap();
    assert!(
        errors
            .iter()
            .any(|error| error.contains("must not contain"))
    );
}

#[test]
fn android_parity_requires_version_code() {
    let fixture = Fixture::new();
    fs::write(
        fixture.path("apps/android/app/build.gradle.kts"),
        r#"android {
    defaultConfig {
        versionName = "1.3.2"
    }
}
"#,
    )
    .unwrap();
    let manifest = load_manifest(fixture.root()).unwrap();
    let android = manifest
        .components
        .iter()
        .find(|component| component.id == "android")
        .unwrap();
    let errors = check_component_parity(fixture.root(), android, "1.3.2").unwrap();
    assert!(
        !errors.iter().any(|error| error.contains("versionName")),
        "fixture should isolate the missing versionCode error"
    );
    assert!(errors.iter().any(|error| error.contains("versionCode")));
}

#[test]
fn cli_parity_rejects_invalid_semver_even_when_versions_match() {
    let fixture = Fixture::new();
    fs::write(
        fixture.path("Cargo.toml"),
        r#"[package]
name = "axon"
version = "banana"
"#,
    )
    .unwrap();
    fs::write(fixture.path("README.md"), "# Axon\n\nVersion: banana\n").unwrap();
    fs::write(fixture.path("CHANGELOG.md"), "# Changelog\n\n## [banana]\n").unwrap();
    fs::write(
        fixture.path("apps/web/package.json"),
        r#"{"version":"banana"}"#,
    )
    .unwrap();
    fs::write(
        fixture.path("apps/web/openapi/axon.json"),
        r#"{"info":{"version":"banana"}}"#,
    )
    .unwrap();

    let error =
        check_cli_parity_only(fixture.root()).expect_err("invalid semver should fail parity");
    assert!(error.to_string().contains("not valid semver"));
}

#[test]
fn semver_tag_sorting_keeps_component_prefixes_separate() {
    let fixture = Fixture::new();
    fixture.init_repo();
    fixture.git(&["tag", "v1.9.0"]);
    fixture.git(&["tag", "v1.10.0"]);
    fixture.git(&["tag", "palette-v9.9.9"]);

    assert_eq!(
        latest_tag(fixture.root(), "v").unwrap(),
        Some("v1.10.0".to_owned())
    );
    assert_eq!(
        latest_tag(fixture.root(), "palette-v").unwrap(),
        Some("palette-v9.9.9".to_owned())
    );
}

#[test]
fn changed_shipping_path_requires_new_tag() {
    let fixture = Fixture::new();
    fixture.init_repo();
    fixture.git(&["tag", "v1.0.0"]);
    fs::write(fixture.path("src/lib.rs"), "pub fn changed() {}\n").unwrap();
    fixture.git(&["add", "src/lib.rs"]);
    fixture.git(&["commit", "-m", "change cli"]);

    let error = check(fixture.root(), Some("v1.0.0"), "HEAD", GateMode::Pr, false)
        .expect_err("unchanged version should fail");
    assert!(error.to_string().contains("release version check failed"));
}

#[test]
fn docs_only_change_does_not_require_component_bump() {
    let fixture = Fixture::new();
    fixture.init_repo();
    fixture.git(&["tag", "v1.0.0"]);
    fs::create_dir_all(fixture.path("docs")).unwrap();
    fs::write(fixture.path("docs/notes.md"), "docs only\n").unwrap();
    fixture.git(&["add", "docs/notes.md"]);
    fixture.git(&["commit", "-m", "docs"]);

    check(fixture.root(), Some("v1.0.0"), "HEAD", GateMode::Pr, false)
        .expect("docs-only change is allowed");
}

#[test]
fn documentation_inside_shipping_paths_does_not_require_component_bump() {
    let fixture = Fixture::new();
    fixture.init_repo();
    fixture.git(&["tag", "v1.0.0"]);
    fixture.git(&["tag", "palette-v1.0.0"]);
    fixture.git(&["tag", "android-v1.0.0"]);
    fixture.git(&["tag", "chrome-ext-v1.0.0"]);
    fs::create_dir_all(fixture.path("crates/axon-ingest/src")).unwrap();
    fs::write(
        fixture.path("crates/axon-ingest/src/README.md"),
        "crate docs\n",
    )
    .unwrap();
    fs::write(
        fixture.path("crates/axon-ingest/src/CLAUDE.md"),
        "agent notes\n",
    )
    .unwrap();
    fs::write(
        fixture.path("apps/palette-tauri/README.md"),
        "palette docs\n",
    )
    .unwrap();
    fs::write(fixture.path("apps/android/README.md"), "android docs\n").unwrap();
    fs::write(
        fixture.path("apps/chrome-extension/README.md"),
        "chrome docs\n",
    )
    .unwrap();
    fixture.git(&[
        "add",
        "crates/axon-ingest/src/README.md",
        "crates/axon-ingest/src/CLAUDE.md",
        "apps/palette-tauri/README.md",
        "apps/android/README.md",
        "apps/chrome-extension/README.md",
    ]);
    fixture.git(&["commit", "-m", "docs in shipping paths"]);

    check(fixture.root(), Some("v1.0.0"), "HEAD", GateMode::Pr, false)
        .expect("documentation inside shipping paths is allowed");
}

#[test]
fn pr_mode_ignores_shipping_changes_that_only_exist_on_base_branch() {
    let fixture = Fixture::new();
    fixture.init_repo();
    fixture.git(&["checkout", "-b", "feature"]);
    fs::create_dir_all(fixture.path("docs")).unwrap();
    fs::write(fixture.path("docs/notes.md"), "feature docs\n").unwrap();
    fixture.git(&["add", "docs/notes.md"]);
    fixture.git(&["commit", "-m", "docs"]);
    fixture.git(&["checkout", "main"]);
    fs::write(fixture.path("src/lib.rs"), "pub fn main_changed() {}\n").unwrap();
    fixture.git(&["add", "src/lib.rs"]);
    fixture.git(&["commit", "-m", "main cli change"]);
    fixture.git(&["checkout", "feature"]);

    check(fixture.root(), Some("main"), "HEAD", GateMode::Pr, false)
        .expect("base-only shipping changes do not force PR bump");
}

#[test]
fn xtask_only_lockfile_change_does_not_require_cli_bump() {
    let fixture = Fixture::new();
    fs::write(
        fixture.path("Cargo.lock"),
        r#"# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "axon"
version = "1.0.0"

[[package]]
name = "xtask"
version = "0.1.0"
dependencies = [
 "anyhow",
]
"#,
    )
    .unwrap();
    fixture.init_repo();
    fixture.git(&["tag", "v1.0.0"]);
    fs::write(
        fixture.path("Cargo.lock"),
        r#"# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "axon"
version = "1.0.0"

[[package]]
name = "xtask"
version = "0.1.0"
dependencies = [
 "anyhow",
 "serde",
]
"#,
    )
    .unwrap();
    fixture.git(&["add", "Cargo.lock"]);
    fixture.git(&["commit", "-m", "update xtask lock deps"]);

    let plans = build_plan(
        fixture.root(),
        &load_manifest(fixture.root()).unwrap(),
        Some("v1.0.0"),
        "HEAD",
        GateMode::Pr,
    )
    .unwrap();
    let cli = plans.iter().find(|plan| plan.id == "cli").unwrap();
    assert!(!cli.changed, "xtask-only lockfile changes are tooling-only");
    check(fixture.root(), Some("v1.0.0"), "HEAD", GateMode::Pr, false)
        .expect("xtask-only lockfile change is allowed");
}

#[test]
fn xtask_lockfile_change_with_new_package_sections_requires_cli_bump() {
    let fixture = Fixture::new();
    fs::write(
        fixture.path("Cargo.lock"),
        r#"# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "axon"
version = "1.0.0"

[[package]]
name = "xtask"
version = "0.1.0"
"#,
    )
    .unwrap();
    fixture.init_repo();
    fixture.git(&["tag", "v1.0.0"]);
    fs::write(
        fixture.path("Cargo.lock"),
        r#"# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "axon"
version = "1.0.0"

[[package]]
name = "serde"
version = "1.0.0"

[[package]]
name = "xtask"
version = "0.1.0"
dependencies = [
 "serde",
]
"#,
    )
    .unwrap();
    fixture.git(&["add", "Cargo.lock"]);
    fixture.git(&["commit", "-m", "add xtask dep"]);

    let plans = build_plan(
        fixture.root(),
        &load_manifest(fixture.root()).unwrap(),
        Some("v1.0.0"),
        "HEAD",
        GateMode::Pr,
    )
    .unwrap();
    let cli = plans.iter().find(|plan| plan.id == "cli").unwrap();
    assert!(
        cli.changed,
        "new lockfile package sections are conservatively release-relevant"
    );
}

#[test]
fn non_xtask_lockfile_change_requires_cli_bump() {
    let fixture = Fixture::new();
    fs::write(
        fixture.path("Cargo.lock"),
        r#"# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "axon"
version = "1.0.0"
dependencies = [
 "anyhow",
]

[[package]]
name = "xtask"
version = "0.1.0"
"#,
    )
    .unwrap();
    fixture.init_repo();
    fixture.git(&["tag", "v1.0.0"]);
    fs::write(
        fixture.path("Cargo.lock"),
        r#"# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "axon"
version = "1.0.0"
dependencies = [
 "anyhow",
 "serde",
]

[[package]]
name = "xtask"
version = "0.1.0"
"#,
    )
    .unwrap();
    fixture.git(&["add", "Cargo.lock"]);
    fixture.git(&["commit", "-m", "update app lock deps"]);

    let plans = build_plan(
        fixture.root(),
        &load_manifest(fixture.root()).unwrap(),
        Some("v1.0.0"),
        "HEAD",
        GateMode::Pr,
    )
    .unwrap();
    let cli = plans.iter().find(|plan| plan.id == "cli").unwrap();
    assert!(cli.changed, "app lockfile changes are release-relevant");
    let error = check(fixture.root(), Some("v1.0.0"), "HEAD", GateMode::Pr, false)
        .expect_err("app lockfile change requires CLI bump");
    assert!(error.to_string().contains("release version check failed"));
}

#[test]
fn android_change_requires_version_code_increase() {
    let fixture = Fixture::new();
    fixture.init_repo();
    fixture.git(&["tag", "android-v1.3.2"]);
    fs::write(
        fixture.path("apps/android/app/build.gradle.kts"),
        r#"android {
    defaultConfig {
        versionCode = 6
        versionName = "1.3.3"
    }
}
"#,
    )
    .unwrap();
    fixture.git(&["add", "apps/android/app/build.gradle.kts"]);
    fixture.git(&["commit", "-m", "bump android version name"]);

    let error = check(
        fixture.root(),
        Some("android-v1.3.2"),
        "HEAD",
        GateMode::Pr,
        false,
    )
    .expect_err("android versionCode must increase");
    assert!(format!("{error:?}").contains("versionCode must increase"));
}

#[test]
fn android_change_allows_version_code_increase() {
    let fixture = Fixture::new();
    fixture.init_repo();
    fixture.git(&["tag", "android-v1.3.2"]);
    fs::write(
        fixture.path("apps/android/app/build.gradle.kts"),
        r#"android {
    defaultConfig {
        versionCode = 7
        versionName = "1.3.3"
    }
}
"#,
    )
    .unwrap();
    fs::write(
        fixture.path("apps/android/CHANGELOG.md"),
        "# Changelog\n\n## [1.3.3]\n",
    )
    .unwrap();
    fs::write(
        fixture.path(".release-please-manifest.json"),
        r#"{
  ".": "1.0.0",
  "apps/palette-tauri": "5.10.2",
  "apps/android": "1.3.3",
  "apps/chrome-extension": "0.2.0"
}
"#,
    )
    .unwrap();
    fixture.git(&[
        "add",
        "apps/android/app/build.gradle.kts",
        ".release-please-manifest.json",
    ]);
    fixture.git(&["commit", "-m", "bump android version"]);

    check(
        fixture.root(),
        Some("android-v1.3.2"),
        "HEAD",
        GateMode::Pr,
        false,
    )
    .expect("android versionName and versionCode bump is accepted");
}

#[test]
fn changed_shipping_path_rejects_version_downgrade_without_existing_tag() {
    let fixture = Fixture::new();
    fixture.init_repo();
    fixture.git(&["tag", "v1.2.0"]);
    fs::write(
        fixture.path("Cargo.toml"),
        r#"[package]
name = "axon"
version = "1.1.0"
"#,
    )
    .unwrap();
    fs::write(fixture.path("README.md"), "# Axon\n\nVersion: 1.1.0\n").unwrap();
    fs::write(fixture.path("CHANGELOG.md"), "# Changelog\n\n## [1.1.0]\n").unwrap();
    fs::write(
        fixture.path("apps/web/package.json"),
        r#"{"version":"1.1.0"}"#,
    )
    .unwrap();
    fs::write(
        fixture.path("apps/web/openapi/axon.json"),
        r#"{"info":{"version":"1.1.0"}}"#,
    )
    .unwrap();
    fs::write(fixture.path("src/lib.rs"), "pub fn downgraded() {}\n").unwrap();
    fixture.git(&["add", "."]);
    fixture.git(&["commit", "-m", "downgrade cli"]);

    let error = check(fixture.root(), Some("v1.2.0"), "HEAD", GateMode::Pr, false)
        .expect_err("version downgrade should fail even when tag does not exist");
    assert!(error.to_string().contains("not greater than latest"));
}

#[test]
fn chrome_assets_change_requires_chrome_bump() {
    let fixture = Fixture::new();
    fixture.init_repo();
    fixture.git(&["tag", "chrome-ext-v0.2.0"]);
    fs::create_dir_all(fixture.path("apps/chrome-extension/assets")).unwrap();
    fs::write(
        fixture.path("apps/chrome-extension/assets/axon-glyph.svg"),
        "<svg />\n",
    )
    .unwrap();
    fixture.git(&["add", "apps/chrome-extension/assets/axon-glyph.svg"]);
    fixture.git(&["commit", "-m", "change asset"]);

    let error = check(
        fixture.root(),
        Some("chrome-ext-v0.2.0"),
        "HEAD",
        GateMode::Pr,
        false,
    )
    .expect_err("chrome asset change requires bump");
    assert!(error.to_string().contains("release version check failed"));
}

#[test]
fn main_mode_marks_changed_since_latest_tag() {
    let fixture = Fixture::new();
    fixture.init_repo();
    fixture.git(&["tag", "v1.0.0"]);
    bump_cli_fixture_to(&fixture, "1.0.1");
    fs::write(fixture.path("src/lib.rs"), "pub fn changed() {}\n").unwrap();
    fixture.git(&["add", "."]);
    fixture.git(&["commit", "-m", "change cli"]);

    let plans = plan(fixture.root(), None, "HEAD", GateMode::Main).unwrap();
    let cli = plans.iter().find(|plan| plan.id == "cli").unwrap();
    assert!(cli.changed);
    assert_eq!(cli.last_tag.as_deref(), Some("v1.0.0"));
}

#[test]
fn main_mode_marks_unchanged_when_latest_tag_points_at_head() {
    let fixture = Fixture::new();
    fixture.init_repo();
    fixture.git(&["tag", "v1.0.0"]);

    let plans = plan(fixture.root(), None, "HEAD", GateMode::Main).unwrap();
    let cli = plans.iter().find(|plan| plan.id == "cli").unwrap();
    assert!(!cli.changed);
}

#[test]
fn main_mode_treats_missing_component_tag_as_first_release() {
    let fixture = Fixture::new();
    fixture.init_repo();

    let plans = plan(fixture.root(), None, "HEAD", GateMode::Main).unwrap();
    let cli = plans.iter().find(|plan| plan.id == "cli").unwrap();
    assert!(cli.changed);
    assert!(cli.last_tag.is_none());
}

#[test]
fn main_mode_android_version_code_compares_against_latest_tag() {
    let fixture = Fixture::new();
    fixture.init_repo();
    fixture.git(&["tag", "android-v1.3.2"]);
    fs::write(
        fixture.path("apps/android/app/build.gradle.kts"),
        r#"android {
    defaultConfig {
        versionCode = 6
        versionName = "1.3.3"
    }
}
"#,
    )
    .unwrap();
    fixture.git(&["add", "apps/android/app/build.gradle.kts"]);
    fixture.git(&["commit", "-m", "bump android name only"]);

    let error = check(fixture.root(), None, "HEAD", GateMode::Main, false)
        .expect_err("main mode must compare versionCode with latest tag");
    assert!(error.to_string().contains("versionCode must increase"));
}

#[test]
fn release_manifest_requires_release_please_path() {
    let fixture = Fixture::new();
    let path = fixture.path("release/components.toml");
    let content = fs::read_to_string(&path).unwrap();
    fs::write(&path, content.replace("release_please_path = \".\"\n", "")).unwrap();

    let err = plan(fixture.root(), Some("origin/main"), "HEAD", GateMode::Pr)
        .expect_err("missing release_please_path must fail");
    assert!(err.to_string().contains("release_please_path"));
}

#[test]
fn release_please_manifest_matches_component_versions() {
    let fixture = Fixture::new();
    fs::write(
        fixture.path(".release-please-manifest.json"),
        r#"{
  ".": "9.9.9",
  "apps/palette-tauri": "5.10.2",
  "apps/android": "1.3.2",
  "apps/chrome-extension": "0.2.0"
}"#,
    )
    .unwrap();

    let manifest = load_manifest(fixture.root()).unwrap();
    let errors =
        release_please::check_manifest_versions(fixture.root(), &manifest.components).unwrap();
    assert!(
        errors
            .iter()
            .any(|error| error.contains(".release-please-manifest.json"))
    );
}

#[test]
fn release_please_dispatch_plan_uses_manifest_metadata() {
    let fixture = Fixture::new();
    let release_outputs = r#"{
  "paths_released": "[\".\", \"apps/palette-tauri\"]",
  "cli_tag": "v1.0.0",
  "palette_tag": "palette-v5.10.2"
}"#;
    let items = release_please_dispatch_plan(fixture.root(), release_outputs).unwrap();
    assert_eq!(
        items,
        vec![
            release_please::ReleasePleaseDispatchItem {
                id: "cli".to_owned(),
                workflow: "release.yml".to_owned(),
                tag: "v1.0.0".to_owned(),
            },
            release_please::ReleasePleaseDispatchItem {
                id: "palette".to_owned(),
                workflow: "palette-release.yml".to_owned(),
                tag: "palette-v5.10.2".to_owned(),
            },
        ]
    );
}

#[test]
fn release_please_dispatch_plan_rejects_object_paths() {
    let fixture = Fixture::new();
    let release_outputs = r#"{
  "paths_released": "{\".\": \"yes\"}",
  "cli_tag": "v1.0.0"
}"#;
    let err = release_please_dispatch_plan(fixture.root(), release_outputs).unwrap_err();
    assert!(
        err.to_string()
            .contains("paths_released must be a JSON array")
    );
}

#[test]
fn release_please_fixup_plan_uses_component_manifest() {
    let fixture = Fixture::new();
    let items = release_please_fixup_plan(
        fixture.root(),
        "apps/palette-tauri/CHANGELOG.md\napps/android/app/build.gradle.kts\n",
    )
    .unwrap();
    assert_eq!(
        items,
        vec![
            release_please::ReleasePleaseFixupItem {
                id: "palette".to_owned(),
                version: "5.10.2".to_owned(),
            },
            release_please::ReleasePleaseFixupItem {
                id: "android".to_owned(),
                version: "1.3.2".to_owned(),
            },
        ]
    );
}

#[test]
fn android_fixup_increments_version_code() {
    let fixture = Fixture::new();
    fs::write(
        fixture.path("apps/android/app/build.gradle.kts"),
        r#"android {
    defaultConfig {
        versionCode = 14 // x-release-please-version-code
        // x-release-please-start-version
        versionName = "1.5.1"
        // x-release-please-end
    }
}
"#,
    )
    .unwrap();

    release_please_fixups(fixture.root(), "android", "1.5.1").unwrap();
    release_please_fixups(fixture.root(), "android", "1.5.1").unwrap();

    let content = fs::read_to_string(fixture.path("apps/android/app/build.gradle.kts")).unwrap();
    assert_eq!(read_gradle_version_name(&content).unwrap(), "1.5.1");
    assert_eq!(read_gradle_version_code(&content).unwrap(), 15);
    assert!(content.contains("x-release-please-version-code 1.5.1"));
}

#[test]
fn manifest_validation_rejects_duplicate_ids() {
    let fixture = Fixture::new();
    let mut manifest = load_manifest(fixture.root()).unwrap();
    manifest.components[1].id = manifest.components[0].id.clone();
    let error = validate_manifest(fixture.root(), &manifest).expect_err("duplicate id invalid");
    assert!(error.to_string().contains("duplicate release component id"));
}

#[test]
fn manifest_validation_rejects_overlapping_tag_prefixes() {
    let fixture = Fixture::new();
    let mut manifest = load_manifest(fixture.root()).unwrap();
    manifest.components[1].tag_prefix = "v".to_owned();
    let error = validate_manifest(fixture.root(), &manifest).expect_err("overlap invalid");
    assert!(error.to_string().contains("tag_prefix overlaps"));
}

#[test]
fn manifest_validation_rejects_empty_shipping_paths() {
    let fixture = Fixture::new();
    let mut manifest = load_manifest(fixture.root()).unwrap();
    manifest.components[0].shipping_paths.clear();
    let error = validate_manifest(fixture.root(), &manifest).expect_err("empty paths invalid");
    assert!(error.to_string().contains("has no shipping_paths"));
}

#[test]
fn manifest_validation_rejects_missing_shipping_path_and_workflow() {
    let fixture = Fixture::new();
    let mut manifest = load_manifest(fixture.root()).unwrap();
    manifest.components[0]
        .shipping_paths
        .push("missing/path".to_owned());
    let error = validate_manifest(fixture.root(), &manifest).expect_err("missing path invalid");
    assert!(error.to_string().contains("shipping path does not exist"));

    let mut manifest = load_manifest(fixture.root()).unwrap();
    manifest.components[0].release_workflow = "missing.yml".to_owned();
    let error = validate_manifest(fixture.root(), &manifest).expect_err("missing workflow invalid");
    assert!(
        error
            .to_string()
            .contains("release_workflow does not exist")
    );
}

#[test]
fn manifest_validation_rejects_bad_json_pointer() {
    let fixture = Fixture::new();
    let mut manifest = load_manifest(fixture.root()).unwrap();
    let file = manifest.components[0]
        .version_files
        .iter_mut()
        .find(|file| file.kind == VersionKind::JsonVersion)
        .unwrap();
    file.json_pointer = Some("version".to_owned());
    let error = validate_manifest(fixture.root(), &manifest).expect_err("relative pointer invalid");
    assert!(
        error
            .to_string()
            .contains("requires an absolute json_pointer")
    );
}

#[test]
fn manifest_validation_rejects_missing_version_source_in_version_files() {
    let fixture = Fixture::new();
    let mut manifest = load_manifest(fixture.root()).unwrap();
    let source = manifest.components[0].version_source.clone();
    manifest.components[0]
        .version_files
        .retain(|file| !same_version_file(file, &source));
    let error = validate_manifest(fixture.root(), &manifest).expect_err("source must be listed");
    assert!(error.to_string().contains("version_source is not listed"));
}

struct Fixture {
    temp: TempDir,
}

impl Fixture {
    fn new() -> Self {
        let temp = TempDir::new().expect("tempdir");
        let fixture = Self { temp };
        fixture.write_minimal_tree();
        fixture
    }

    fn root(&self) -> &Path {
        self.temp.path()
    }

    fn path(&self, path: &str) -> PathBuf {
        self.root().join(path)
    }

    fn init_repo(&self) {
        self.git(&["init"]);
        self.git(&["config", "user.email", "test@example.com"]);
        self.git(&["config", "user.name", "Test User"]);
        self.git(&["add", "."]);
        self.git(&["commit", "-m", "initial"]);
        self.git(&["branch", "-M", "main"]);
    }

    fn git(&self, args: &[&str]) {
        git(self.root(), args);
    }

    fn write_minimal_tree(&self) {
        let manifest = fs::read_to_string(
            Path::new(env!("CARGO_MANIFEST_DIR")).join("../release/components.toml"),
        )
        .expect("release/components.toml fixture exists");
        write(&self.path("release/components.toml"), &manifest);
        write(
            &self.path(".release-please-manifest.json"),
            r#"{
  ".": "1.0.0",
  "apps/palette-tauri": "5.10.2",
  "apps/android": "1.3.2",
  "apps/chrome-extension": "0.2.0"
}
"#,
        );
        for workflow in [
            "release.yml",
            "palette-release.yml",
            "android-release.yml",
            "chrome-extension-release.yml",
        ] {
            write(
                &self.path(&format!(".github/workflows/{workflow}")),
                "name: test\n",
            );
        }
        write(
            &self.path("Cargo.toml"),
            r#"[package]
name = "axon"
version = "1.0.0"
"#,
        );
        write(
            &self.path("Cargo.lock"),
            r#"# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "axon"
version = "1.0.0"

[[package]]
name = "xtask"
version = "0.1.0"
"#,
        );
        write(&self.path("README.md"), "# Axon\n\nVersion: 1.0.0\n");
        write(&self.path("CHANGELOG.md"), "# Changelog\n\n## [1.0.0]\n");
        write(
            &self.path("apps/web/package.json"),
            r#"{"version":"1.0.0"}"#,
        );
        write(
            &self.path("apps/web/package-lock.json"),
            &package_lock("@axon/admin-panel", "1.0.0"),
        );
        write(
            &self.path("apps/web/openapi/axon.json"),
            r#"{"info":{"version":"1.0.0"}}"#,
        );
        write(
            &self.path("plugins/axon/.claude-plugin/plugin.json"),
            r#"{"name":"axon"}"#,
        );
        write(&self.path("src/lib.rs"), "pub fn original() {}\n");
        write(&self.path("crates/.keep"), "");
        write(&self.path("build.rs"), "");
        write(&self.path("migrations/.keep"), "");
        write(&self.path("rust-toolchain.toml"), "");
        write(&self.path("vendor/.keep"), "");
        write(
            &self.path("apps/palette-tauri/src-tauri/tauri.conf.json"),
            r#"{"version":"5.10.2"}"#,
        );
        write(
            &self.path("apps/palette-tauri/package.json"),
            r#"{"version":"5.10.2"}"#,
        );
        write(
            &self.path("apps/palette-tauri/src-tauri/Cargo.toml"),
            r#"[package]
name = "axon-palette-tauri"
version = "5.10.2"
"#,
        );
        write(
            &self.path("apps/palette-tauri/src-tauri/Cargo.lock"),
            r#"# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "axon-palette-tauri"
version = "5.10.2"
"#,
        );
        write(
            &self.path("apps/android/app/build.gradle.kts"),
            r#"android {
    defaultConfig {
        versionCode = 6
        versionName = "1.3.2"
    }
}
"#,
        );
        write(
            &self.path("apps/chrome-extension/manifest.json"),
            r#"{"manifest_version":3,"version":"0.2.0"}"#,
        );
        // Per-component changelogs (headings match each version_source above) so
        // the copied manifest's changelog_heading entries validate and pass parity.
        write(
            &self.path("apps/palette-tauri/CHANGELOG.md"),
            "# Changelog\n\n## [5.10.2]\n",
        );
        write(
            &self.path("apps/android/CHANGELOG.md"),
            "# Changelog\n\n## [1.3.2]\n",
        );
        write(
            &self.path("apps/chrome-extension/CHANGELOG.md"),
            "# Changelog\n\n## [0.2.0]\n",
        );
        write(&self.path("assets/.keep"), "");
    }
}

fn bump_cli_fixture_to(fixture: &Fixture, version: &str) {
    fs::write(
        fixture.path("Cargo.toml"),
        format!(
            r#"[package]
name = "axon"
version = "{version}"
"#
        ),
    )
    .unwrap();
    fs::write(
        fixture.path("README.md"),
        format!("# Axon\n\nVersion: {version}\n"),
    )
    .unwrap();
    fs::write(
        fixture.path("CHANGELOG.md"),
        format!("# Changelog\n\n## [{version}]\n"),
    )
    .unwrap();
    fs::write(
        fixture.path("Cargo.lock"),
        format!(
            r#"# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "axon"
version = "{version}"
"#
        ),
    )
    .unwrap();
    fs::write(
        fixture.path("apps/web/package.json"),
        format!(r#"{{"version":"{version}"}}"#),
    )
    .unwrap();
    fs::write(
        fixture.path("apps/web/package-lock.json"),
        package_lock("@axon/admin-panel", version),
    )
    .unwrap();
    fs::write(
        fixture.path("apps/web/openapi/axon.json"),
        format!(r#"{{"info":{{"version":"{version}"}}}}"#),
    )
    .unwrap();
}

fn package_lock(name: &str, version: &str) -> String {
    format!(
        r#"{{
  "name": "{name}",
  "version": "{version}",
  "lockfileVersion": 3,
  "packages": {{
    "": {{
      "name": "{name}",
      "version": "{version}"
    }}
  }}
}}"#
    )
}

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask parent")
        .to_path_buf()
}

fn write(path: &Path, content: &str) {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).unwrap();
    }
    fs::write(path, content).unwrap();
}

fn git(root: &Path, args: &[&str]) {
    let status = std::process::Command::new("git")
        .arg("-C")
        .arg(root)
        .args(args)
        .status()
        .expect("git runs");
    assert!(status.success(), "git {:?} failed", args);
}
