pub const REQUIRED_WORKSPACE_MEMBERS: &[&str] = &[
    "xtask",
    // axon-error graduated from the PR0 skeleton in Phase 1 (issue #298): it now
    // carries real dependencies and sidecar tests, so it is a required member
    // rather than a `TARGET_CRATES` skeleton entry.
    "crates/axon-error",
    "crates/axon-api",
    "crates/axon-authz",
    "crates/axon-core",
    "crates/axon-crawl",
    "crates/axon-vector",
    "crates/axon-ingest",
    "crates/axon-extract",
    "crates/axon-jobs",
    "crates/axon-source-ledger",
    "crates/axon-code-index",
    "crates/axon-services",
    "crates/axon-mcp",
    "crates/axon-web",
    "crates/axon-cli",
];

pub struct TargetCrate {
    pub name: &'static str,
    pub modules: &'static [&'static str],
}

// NOTE: `axon-error` is intentionally NOT listed here. It was filled in during
// Phase 1 (issue #298) — real dependencies, sidecar tests, and public API — so
// it is no longer an empty PR0 skeleton and is instead a required workspace
// member (see `REQUIRED_WORKSPACE_MEMBERS`).
pub const TARGET_CRATES: &[TargetCrate] = &[
    TargetCrate {
        name: "axon-observe",
        modules: &[
            "event",
            "phase",
            "heartbeat",
            "progress",
            "metric",
            "span",
            "log",
            "collector",
            "testing",
        ],
    },
    TargetCrate {
        name: "axon-route",
        modules: &[
            "resolver",
            "router",
            "canonical",
            "source_id",
            "scope",
            "authority",
            "alias",
            "capability",
            "testing",
        ],
    },
    TargetCrate {
        name: "axon-adapters",
        modules: &[
            "adapter",
            "registry",
            "capability",
            "acquisition",
            "manifest",
            "web",
            "local",
            "git",
            "registry_sources",
            "feed",
            "youtube",
            "reddit",
            "sessions",
            "cli_tool",
            "mcp_tool",
            "testing",
        ],
    },
    TargetCrate {
        name: "axon-ledger",
        modules: &[
            "store",
            "sqlite",
            "migration",
            "source",
            "item",
            "manifest",
            "diff",
            "generation",
            "document_status",
            "lease",
            "cleanup_debt",
            "transaction",
            "testing",
        ],
    },
    TargetCrate {
        name: "axon-parse",
        modules: &[
            "parser",
            "registry",
            "facts",
            "graph_candidate",
            "code",
            "manifest",
            "schema",
            "session",
            "tool",
            "env",
            "docker",
            "config",
            "testing",
        ],
    },
    TargetCrate {
        name: "axon-graph",
        modules: &[
            "store",
            "sqlite",
            "migration",
            "node",
            "edge",
            "evidence",
            "candidate",
            "authority",
            "merge",
            "query",
            "testing",
        ],
    },
    TargetCrate {
        name: "axon-memory",
        modules: &[
            "store",
            "sqlite",
            "migration",
            "record",
            "link",
            "decay",
            "review",
            "recall",
            "context",
            "graph",
            "testing",
        ],
    },
    TargetCrate {
        name: "axon-document",
        modules: &[
            "preparer",
            "chunk_router",
            "profile",
            "prepared",
            "chunk",
            "metadata",
            "code",
            "markdown",
            "transcript",
            "session",
            "schema",
            "text",
            "testing",
        ],
    },
    TargetCrate {
        name: "axon-embedding",
        modules: &[
            "provider",
            "batch",
            "capability",
            "reservation",
            "tei",
            "openai_compat",
            "fake",
            "testing",
        ],
    },
    TargetCrate {
        name: "axon-vectors",
        modules: &[
            "store",
            "qdrant",
            "collection",
            "point",
            "payload",
            "filter",
            "query",
            "health",
            "testing",
        ],
    },
    TargetCrate {
        name: "axon-retrieval",
        modules: &[
            "engine", "plan", "query", "filter", "rank", "context", "citation", "memory", "graph",
            "testing",
        ],
    },
    TargetCrate {
        name: "axon-llm",
        modules: &[
            "provider",
            "capability",
            "completion",
            "stream",
            "prompt",
            "openai_compat",
            "codex",
            "gemini",
            "fake",
            "testing",
        ],
    },
    TargetCrate {
        name: "axon-prune",
        modules: &[
            "plan",
            "executor",
            "debt",
            "generation",
            "orphan",
            "dedupe",
            "receipt",
            "safety",
            "testing",
        ],
    },
];
