//! Static source-family matrix for public source contracts.

use axon_api::source::{SourceKind, SourceScope};

use crate::spec::{ParserFamily, SourceAdapterSpec, SourceFamily, SourceScopeCapability};

pub type SourceFamilyMatrix = &'static [SourceAdapterSpec];

const LOCAL_SCOPES: &[SourceScopeCapability] = &[
    SourceScopeCapability {
        scope: SourceScope::File,
        required: true,
        notes: "single trusted local file",
    },
    SourceScopeCapability {
        scope: SourceScope::Directory,
        required: true,
        notes: "trusted contained directory walk",
    },
    SourceScopeCapability {
        scope: SourceScope::Workspace,
        required: false,
        notes: "trusted workspace source",
    },
];

const GIT_SCOPES: &[SourceScopeCapability] = &[
    SourceScopeCapability {
        scope: SourceScope::Repo,
        required: true,
        notes: "repository snapshot",
    },
    SourceScopeCapability {
        scope: SourceScope::Branch,
        required: false,
        notes: "branch-specific snapshot",
    },
    SourceScopeCapability {
        scope: SourceScope::Org,
        required: false,
        notes: "provider-specific hardening",
    },
];

const WEB_SCOPES: &[SourceScopeCapability] = &[
    SourceScopeCapability {
        scope: SourceScope::Page,
        required: true,
        notes: "single URL",
    },
    SourceScopeCapability {
        scope: SourceScope::Site,
        required: true,
        notes: "site crawl",
    },
    SourceScopeCapability {
        scope: SourceScope::Map,
        required: true,
        notes: "URL discovery",
    },
];

const FEED_SCOPES: &[SourceScopeCapability] = &[
    SourceScopeCapability {
        scope: SourceScope::Feed,
        required: true,
        notes: "RSS/Atom/JSON feed",
    },
    SourceScopeCapability {
        scope: SourceScope::Page,
        required: false,
        notes: "linked entry page",
    },
];

const YOUTUBE_SCOPES: &[SourceScopeCapability] = &[
    SourceScopeCapability {
        scope: SourceScope::Video,
        required: true,
        notes: "single video transcript/metadata",
    },
    SourceScopeCapability {
        scope: SourceScope::Playlist,
        required: true,
        notes: "playlist items",
    },
    SourceScopeCapability {
        scope: SourceScope::Channel,
        required: false,
        notes: "channel hardening",
    },
];

const REDDIT_SCOPES: &[SourceScopeCapability] = &[
    SourceScopeCapability {
        scope: SourceScope::Subreddit,
        required: true,
        notes: "subreddit listing",
    },
    SourceScopeCapability {
        scope: SourceScope::Thread,
        required: true,
        notes: "thread and comments",
    },
    SourceScopeCapability {
        scope: SourceScope::Comment,
        required: false,
        notes: "comment permalink",
    },
];

const SESSIONS_SCOPES: &[SourceScopeCapability] = &[
    SourceScopeCapability {
        scope: SourceScope::File,
        required: true,
        notes: "session export file",
    },
    SourceScopeCapability {
        scope: SourceScope::Directory,
        required: true,
        notes: "session export directory",
    },
];

const REGISTRY_SCOPES: &[SourceScopeCapability] = &[
    SourceScopeCapability {
        scope: SourceScope::Package,
        required: true,
        notes: "package metadata",
    },
    SourceScopeCapability {
        scope: SourceScope::Version,
        required: true,
        notes: "version metadata",
    },
];

const TOOL_SCOPES: &[SourceScopeCapability] = &[
    SourceScopeCapability {
        scope: SourceScope::Tool,
        required: true,
        notes: "metadata-only tool definition by default",
    },
    SourceScopeCapability {
        scope: SourceScope::Script,
        required: false,
        notes: "explicit script source class",
    },
];

const MCP_SCOPES: &[SourceScopeCapability] = &[
    SourceScopeCapability {
        scope: SourceScope::Tool,
        required: true,
        notes: "MCP tool schema",
    },
    SourceScopeCapability {
        scope: SourceScope::Api,
        required: false,
        notes: "MCP call result with explicit execution scope",
    },
];

const MEMORY_SCOPES: &[SourceScopeCapability] = &[];
const NO_CREDENTIALS: &[axon_api::source::CredentialRequirement] = &[];

const MATRIX: &[SourceAdapterSpec] = &[
    SourceAdapterSpec {
        family: SourceFamily::Local,
        adapter: "local",
        version: "1",
        source_kinds: &[SourceKind::Local],
        vector_namespace: "source:local",
        supported_schemes: &["file"],
        shorthand_patterns: &["./path", "../path", "/absolute/path", "~/<path>"],
        default_scope: SourceScope::File,
        scopes: LOCAL_SCOPES,
        credential_requirements: NO_CREDENTIALS,
        option_schema: "local-source-options/v1",
        parser_families: &[
            ParserFamily::Markdown,
            ParserFamily::Code,
            ParserFamily::Manifest,
        ],
        metadata_families: &["local", "filesystem", "security"],
        watch_supported: true,
        refresh_supported: true,
        may_access_local_paths: true,
        may_perform_network_fetches: false,
        may_call_render_provider: false,
        may_execute_tools: false,
        is_source_adapter: true,
        degraded_modes: &[
            "permission-denied",
            "file-too-large",
            "symlink-outside-root",
        ],
        required_graph_fact_kinds: &["document", "filesystem_path"],
        optional_graph_fact_kinds: &["symbol", "dependency"],
    },
    SourceAdapterSpec {
        family: SourceFamily::Git,
        adapter: "git",
        version: "1",
        source_kinds: &[SourceKind::Git],
        vector_namespace: "source:git",
        supported_schemes: &["git", "ssh", "http", "https"],
        shorthand_patterns: &["github:owner/repo", "gitlab:owner/repo", "owner/repo"],
        default_scope: SourceScope::Repo,
        scopes: GIT_SCOPES,
        credential_requirements: NO_CREDENTIALS,
        option_schema: "git-source-options/v1",
        parser_families: &[
            ParserFamily::Code,
            ParserFamily::Manifest,
            ParserFamily::Markdown,
        ],
        metadata_families: &["git", "repository", "security"],
        watch_supported: true,
        refresh_supported: true,
        may_access_local_paths: true,
        may_perform_network_fetches: true,
        may_call_render_provider: false,
        may_execute_tools: false,
        is_source_adapter: true,
        degraded_modes: &["shallow-clone", "missing-provider-token", "rate-limited"],
        required_graph_fact_kinds: &["repository", "revision"],
        optional_graph_fact_kinds: &["symbol", "dependency", "release"],
    },
    SourceAdapterSpec {
        family: SourceFamily::Web,
        adapter: "web",
        version: "1",
        source_kinds: &[SourceKind::Web],
        vector_namespace: "source:web",
        supported_schemes: &["http", "https"],
        shorthand_patterns: &["https://example.com/path"],
        default_scope: SourceScope::Page,
        scopes: WEB_SCOPES,
        credential_requirements: NO_CREDENTIALS,
        option_schema: "web-source-options/v1",
        parser_families: &[ParserFamily::Html, ParserFamily::Markdown],
        metadata_families: &["web", "http", "security"],
        watch_supported: true,
        refresh_supported: true,
        may_access_local_paths: false,
        may_perform_network_fetches: true,
        may_call_render_provider: true,
        may_execute_tools: false,
        is_source_adapter: true,
        degraded_modes: &["http-only", "render-unavailable", "thin-content"],
        required_graph_fact_kinds: &["web_page", "canonical_url"],
        optional_graph_fact_kinds: &["link", "structured_data"],
    },
    SourceAdapterSpec {
        family: SourceFamily::Feed,
        adapter: "feed",
        version: "1",
        source_kinds: &[SourceKind::Feed],
        vector_namespace: "source:feed",
        supported_schemes: &["http", "https", "feed", "rss", "atom"],
        shorthand_patterns: &["feed:https://example.com/feed.xml", "rss:<url>"],
        default_scope: SourceScope::Feed,
        scopes: FEED_SCOPES,
        credential_requirements: NO_CREDENTIALS,
        option_schema: "feed-source-options/v1",
        parser_families: &[
            ParserFamily::Feed,
            ParserFamily::Html,
            ParserFamily::Markdown,
        ],
        metadata_families: &["feed", "web", "security"],
        watch_supported: true,
        refresh_supported: true,
        may_access_local_paths: false,
        may_perform_network_fetches: true,
        may_call_render_provider: false,
        may_execute_tools: false,
        is_source_adapter: true,
        degraded_modes: &["malformed-entry", "linked-page-unavailable", "rate-limited"],
        required_graph_fact_kinds: &["feed", "feed_entry"],
        optional_graph_fact_kinds: &["author", "link"],
    },
    SourceAdapterSpec {
        family: SourceFamily::Youtube,
        adapter: "youtube",
        version: "1",
        source_kinds: &[SourceKind::Youtube],
        vector_namespace: "source:youtube",
        supported_schemes: &["http", "https", "youtube", "youtu"],
        shorthand_patterns: &["youtube:<video-id>", "youtu.be/<video-id>"],
        default_scope: SourceScope::Video,
        scopes: YOUTUBE_SCOPES,
        credential_requirements: NO_CREDENTIALS,
        option_schema: "youtube-source-options/v1",
        parser_families: &[ParserFamily::Transcript],
        metadata_families: &["youtube", "video", "security"],
        watch_supported: true,
        refresh_supported: true,
        may_access_local_paths: false,
        may_perform_network_fetches: true,
        may_call_render_provider: false,
        may_execute_tools: false,
        is_source_adapter: true,
        degraded_modes: &["metadata-only", "transcript-unavailable", "rate-limited"],
        required_graph_fact_kinds: &["video"],
        optional_graph_fact_kinds: &["channel", "playlist", "transcript_segment"],
    },
    SourceAdapterSpec {
        family: SourceFamily::Reddit,
        adapter: "reddit",
        version: "1",
        source_kinds: &[SourceKind::Reddit],
        vector_namespace: "source:reddit",
        supported_schemes: &["http", "https", "reddit"],
        shorthand_patterns: &["r/<subreddit>", "reddit:<subreddit>", "reddit:<thread-url>"],
        default_scope: SourceScope::Thread,
        scopes: REDDIT_SCOPES,
        credential_requirements: NO_CREDENTIALS,
        option_schema: "reddit-source-options/v1",
        parser_families: &[ParserFamily::Markdown],
        metadata_families: &["reddit", "thread", "security"],
        watch_supported: true,
        refresh_supported: true,
        may_access_local_paths: false,
        may_perform_network_fetches: true,
        may_call_render_provider: false,
        may_execute_tools: false,
        is_source_adapter: true,
        degraded_modes: &[
            "public-json-unavailable",
            "comments-truncated",
            "rate-limited",
        ],
        required_graph_fact_kinds: &["thread", "comment"],
        optional_graph_fact_kinds: &["author", "subreddit"],
    },
    SourceAdapterSpec {
        family: SourceFamily::Sessions,
        adapter: "sessions",
        version: "1",
        source_kinds: &[SourceKind::Session],
        vector_namespace: "source:sessions",
        supported_schemes: &["session", "file"],
        shorthand_patterns: &[
            "session:claude:<path>",
            "session:codex:<path>",
            "session:gemini:<path>",
        ],
        default_scope: SourceScope::File,
        scopes: SESSIONS_SCOPES,
        credential_requirements: NO_CREDENTIALS,
        option_schema: "sessions-source-options/v1",
        parser_families: &[ParserFamily::Session],
        metadata_families: &["session", "agent", "security"],
        watch_supported: false,
        refresh_supported: true,
        may_access_local_paths: true,
        may_perform_network_fetches: false,
        may_call_render_provider: false,
        may_execute_tools: false,
        is_source_adapter: true,
        degraded_modes: &["unknown-export-format", "partial-turn", "redacted-secret"],
        required_graph_fact_kinds: &["session", "turn"],
        optional_graph_fact_kinds: &["tool_call", "artifact"],
    },
    SourceAdapterSpec {
        family: SourceFamily::Registry,
        adapter: "registry",
        version: "1",
        source_kinds: &[SourceKind::Registry],
        vector_namespace: "source:registry",
        supported_schemes: &["pkg", "npm", "pypi", "crates", "docker"],
        shorthand_patterns: &["pkg:npm/<name>", "pkg:pypi/<name>", "pkg:crates/<name>"],
        default_scope: SourceScope::Package,
        scopes: REGISTRY_SCOPES,
        credential_requirements: NO_CREDENTIALS,
        option_schema: "registry-source-options/v1",
        parser_families: &[ParserFamily::PackageMetadata, ParserFamily::Manifest],
        metadata_families: &["package", "registry", "security"],
        watch_supported: true,
        refresh_supported: true,
        may_access_local_paths: false,
        may_perform_network_fetches: true,
        may_call_render_provider: false,
        may_execute_tools: false,
        is_source_adapter: true,
        degraded_modes: &["provider-unavailable", "version-yanked", "rate-limited"],
        required_graph_fact_kinds: &["package", "version"],
        optional_graph_fact_kinds: &["dependency", "release"],
    },
    SourceAdapterSpec {
        family: SourceFamily::CliTool,
        adapter: "cli_tool",
        version: "1",
        source_kinds: &[SourceKind::CliTool],
        vector_namespace: "source:cli_tool",
        supported_schemes: &["tool"],
        shorthand_patterns: &["tool:<command>"],
        default_scope: SourceScope::Tool,
        scopes: TOOL_SCOPES,
        credential_requirements: NO_CREDENTIALS,
        option_schema: "cli-tool-source-options/v1",
        parser_families: &[ParserFamily::ToolOutput],
        metadata_families: &["tool", "execution", "security"],
        watch_supported: false,
        refresh_supported: false,
        may_access_local_paths: true,
        may_perform_network_fetches: false,
        may_call_render_provider: false,
        may_execute_tools: true,
        is_source_adapter: true,
        degraded_modes: &["metadata-only", "command-denied", "output-capped"],
        required_graph_fact_kinds: &["tool"],
        optional_graph_fact_kinds: &["tool_call", "artifact"],
    },
    SourceAdapterSpec {
        family: SourceFamily::McpTool,
        adapter: "mcp_tool",
        version: "1",
        source_kinds: &[SourceKind::McpTool],
        vector_namespace: "source:mcp_tool",
        supported_schemes: &["mcp"],
        shorthand_patterns: &["mcp://server/tool"],
        default_scope: SourceScope::Tool,
        scopes: MCP_SCOPES,
        credential_requirements: NO_CREDENTIALS,
        option_schema: "mcp-tool-source-options/v1",
        parser_families: &[ParserFamily::ApiSchema, ParserFamily::ToolOutput],
        metadata_families: &["mcp", "tool", "security"],
        watch_supported: false,
        refresh_supported: false,
        may_access_local_paths: false,
        may_perform_network_fetches: true,
        may_call_render_provider: false,
        may_execute_tools: true,
        is_source_adapter: true,
        degraded_modes: &["schema-only", "tool-unavailable", "output-capped"],
        required_graph_fact_kinds: &["mcp_server", "mcp_tool"],
        optional_graph_fact_kinds: &["tool_call", "external_resource"],
    },
    SourceAdapterSpec {
        family: SourceFamily::MemoryIntegration,
        adapter: "memory",
        version: "1",
        source_kinds: &[SourceKind::Memory],
        vector_namespace: "memory",
        supported_schemes: &[],
        shorthand_patterns: &[],
        default_scope: SourceScope::Api,
        scopes: MEMORY_SCOPES,
        credential_requirements: NO_CREDENTIALS,
        option_schema: "memory-shared-pipeline-options/v1",
        parser_families: &[ParserFamily::Memory, ParserFamily::Markdown],
        metadata_families: &["memory", "retrieval", "graph"],
        watch_supported: false,
        refresh_supported: false,
        may_access_local_paths: false,
        may_perform_network_fetches: false,
        may_call_render_provider: false,
        may_execute_tools: false,
        is_source_adapter: false,
        degraded_modes: &["namespace-filtered", "superseded-memory"],
        required_graph_fact_kinds: &["memory_document"],
        optional_graph_fact_kinds: &["memory_link", "supersedes"],
    },
];

pub fn source_family_matrix() -> SourceFamilyMatrix {
    MATRIX
}
