use super::config::{AdaptiveConcurrencyConfig, Config};
use super::enums::{
    CommandKind, EvaluateResponsesMode, MapFallback, McpTransport, PerformanceProfile, RedditSort,
    RedditTime, RenderMode, ScrapeFormat,
};
use super::subconfigs::AskConfig;
use super::{
    DEFAULT_CRAWL_BROADCAST_BUFFER_MAX, DEFAULT_CRAWL_BROADCAST_BUFFER_MIN,
    DEFAULT_CRAWL_MEMORY_ABORT_PERCENT, DEFAULT_MAX_PAGE_BYTES,
};
use std::path::PathBuf;

impl Default for Config {
    fn default() -> Self {
        Self {
            command: CommandKind::Status,
            start_url: String::new(),
            positional: Vec::new(),
            urls_csv: None,
            url_glob: Vec::new(),
            query: None,
            search_limit: 10,
            code_search_cwd: None,
            code_search_path_prefix: None,
            code_search_no_freshness: false,
            code_search_watch: None,
            freshness: None,
            retrieve_max_points: None,
            train_best_rank: None,
            train_notes: None,
            max_pages: 0,
            max_depth: 10,
            include_subdomains: false,
            exclude_path_prefix: Vec::new(),
            ingest_exclude_paths: Vec::new(),
            output_dir: PathBuf::from(".cache/axon-rust/output"),
            output_path: None,
            warc_output: None,
            automation_script: None,
            render_mode: RenderMode::AutoSwitch,
            chrome_remote_url: None,
            chrome_proxy: None,
            user_agent: None,
            chrome_user_agent: None,
            chrome_bootstrap_timeout_ms: 3_000,
            chrome_bootstrap_retries: 2,
            chrome_remote_local_policy: false,
            respect_robots: false,
            min_markdown_chars: 200,
            drop_thin_markdown: true,
            discover_sitemaps: true,
            sitemap_since_days: 0,
            map_fallback: MapFallback::Structure,
            endpoints_include_bundles: true,
            endpoints_first_party_only: false,
            endpoints_unique_only: true,
            endpoints_max_scripts: 40,
            endpoints_max_scan_bytes: 8 * 1024 * 1024,
            endpoints_verify: false,
            endpoints_capture_network: false,
            endpoints_probe_rpc: false,
            endpoints_probe_rpc_subdomains: false,
            max_sitemaps: 512,
            discover_llms_txt: true,
            max_llms_txt_urls: 512,
            cache: false,
            cache_http_only: false,
            etag_conditional: false,
            path_budgets: Vec::new(),
            format: ScrapeFormat::Markdown,
            collection: "axon".to_string(),
            embed: true,
            mcp_embed_allowed_roots: Vec::new(),
            mcp_embed_max_local_bytes: 10 * 1024 * 1024,
            mcp_embed_max_local_depth: 16,
            mcp_embed_max_local_entries: 10_000,
            batch_concurrency: 16,
            wait: false,
            sqlite_path: crate::paths::axon_data_base_dir().join("jobs.db"),
            yes: false,
            purge_prefix: false,
            purge_dry_run: false,
            setup_method: None,
            color_choice: super::enums::ColorChoice::Auto,
            watch_mode: false,
            performance_profile: PerformanceProfile::HighStable,
            crawl_concurrency_limit: None,
            backfill_concurrency_limit: None,
            adaptive_concurrency: AdaptiveConcurrencyConfig {
                enabled: false,
                min: 1,
                max: None,
            },
            sitemap_only: false,
            delay_ms: 0,
            request_timeout_ms: None,
            scrape_batch_timeout_secs: 120,
            fetch_retries: 2,
            retry_backoff_ms: 250,
            sessions_claude: false,
            sessions_codex: false,
            sessions_gemini: false,
            sessions_project: None,
            sessions_watch: None,
            sessions_action: None,
            setup_session_watch_action: None,
            github_token: None,
            gitlab_token: None,
            gitea_token: None,
            github_include_source: true,
            github_max_issues: 100,
            github_max_prs: 100,
            reddit_client_id: None,
            reddit_client_secret: None,
            reddit_sort: RedditSort::Hot,
            reddit_time: RedditTime::Day,
            reddit_max_posts: 25,
            reddit_min_score: 0,
            reddit_depth: 2,
            reddit_scrape_links: false,
            tei_url: String::new(),
            qdrant_url: "http://127.0.0.1:53333".to_string(),
            headless_gemini_model: String::new(),
            headless_gemini_chat_model: String::new(),
            llm_backend: crate::llm::LlmBackendKind::GeminiHeadless,
            headless_gemini_cmd: "gemini".to_string(),
            headless_gemini_home: None,
            codex_cmd: "codex".to_string(),
            codex_home: None,
            codex_model: String::new(),
            codex_completion_concurrency: 4,
            codex_load_user_config: false,
            llm_completion_concurrency: 4,
            llm_completion_timeout_secs: 300,
            openai_base_url: String::new(),
            openai_api_key: String::new(),
            openai_model: String::new(),
            openai_chat_model: String::new(),
            tavily_api_key: String::new(),
            searxng_url: String::new(),
            research_full_content: true,
            mcp_allowed_origins: vec![],
            ask_diagnostics: false,
            ask_explain: false,
            ask_stream: false,
            ask_follow_up: false,
            ask_session: None,
            ask_follow_up_context: None,
            ask_reset_session: false,
            ask_new_session: false,
            ask_list_sessions: false,
            evaluate_responses_mode: EvaluateResponsesMode::Inline,
            ask_max_context_chars: 300_000,
            ask_candidate_limit: 250,
            ask_chunk_limit: 24,
            ask_full_docs: 6,
            ask_full_docs_explicit: false,
            ask_backfill_chunks: 5,
            ask_doc_fetch_concurrency: 4,
            ask_doc_chunk_limit: 96,
            ask_min_relevance_score: 0.45,
            ask_authoritative_domains: vec![],
            ask_authoritative_boost: 0.0,
            ask_min_citations_nontrivial: 2,
            synthesis_high_context: None,
            hybrid_search_enabled: true,
            hybrid_search_candidates: 100,
            ask_hybrid_candidates: 150,
            ask_cache_enabled: false,
            ask_cache_max_capacity_bytes: 256 * 1024 * 1024,
            ask_cache_ttl_secs: 300,
            ask_fulldoc_skip_enabled: false,
            ask_fulldoc_skip_min_urls: 3,
            ask_fulldoc_skip_min_chars: 4000,
            ask_fulldoc_skip_score_delta: 0.15,
            tei_max_retries: 5,
            tei_request_timeout_ms: 30_000,
            tei_max_client_batch_size: 96,
            ingest_lanes: 2,
            embed_lanes: 2,
            embed_doc_timeout_secs: 300,
            queue_summary_secs: 30,
            freshness_tick_secs: 60,
            freshness_lease_secs: 1800,
            freshness_max_due_per_tick: 4,
            freshness_max_concurrent_runs: 2,
            freshness_run_retention_days: 90,
            qdrant_point_buffer: 1024,
            max_pending_crawl_jobs: 100,
            max_pending_embed_jobs: 50,
            max_pending_extract_jobs: 50,
            max_pending_ingest_jobs: 50,
            hnsw_ef_search: 128,
            hnsw_ef_search_legacy: 64,
            evaluate_retrieval_ab: false,
            cron_every_seconds: None,
            cron_max_runs: None,
            watchdog_stale_timeout_secs: 300,
            watchdog_confirm_secs: 60,
            watchdog_sweep_secs: 15,
            worker_starvation_secs: 120,
            crawl_job_timeout_secs: 7200,
            max_job_attempts: 5,
            json_output: false,
            reclaimed_status_only: false,
            active_status_only: false,
            recent_status_only: false,
            normalize: true,
            chrome_network_idle_timeout_secs: 15,
            auto_switch_thin_ratio: 0.60,
            auto_switch_min_pages: 10,
            crawl_broadcast_buffer_min: DEFAULT_CRAWL_BROADCAST_BUFFER_MIN,
            crawl_broadcast_buffer_max: DEFAULT_CRAWL_BROADCAST_BUFFER_MAX,
            allow_unbounded_broad_crawl: false,
            url_whitelist: vec![],
            block_assets: false,
            max_page_bytes: Some(DEFAULT_MAX_PAGE_BYTES),
            crawl_memory_abort_percent: Some(DEFAULT_CRAWL_MEMORY_ABORT_PERCENT),
            redirect_policy_strict: false,
            chrome_wait_for_selector: None,
            root_selector: None,
            exclude_selector: None,
            chrome_screenshot: false,
            research_depth: None,
            search_time_range: None,
            since: None,
            before: None,
            seed_url: None,
            sources_by_schema_version: false,
            sources_domain: None,
            sources_domain_all: false,
            domains_domain: None,
            bypass_csp: false,
            accept_invalid_certs: false,
            screenshot_full_page: true,
            viewport_width: 1920,
            viewport_height: 1080,
            mcp_transport: McpTransport::Stdio,
            mcp_http_host: "127.0.0.1".to_string(),
            mcp_http_port: 8001,
            custom_headers: vec![],
            quiet: false,
            log_level: None,
            job_wait_timeout_secs: 300,
            doctor_diagnose: false,

            // ── Webclaw port (axon_rust-zehr) ─────────────────────────────
            enable_verticals: true,
            auto_dispatch_skip: Vec::new(),
            vertical_cache_ttl_secs: {
                let mut m = std::collections::HashMap::new();
                m.insert("github".to_string(), 86_400);
                m.insert("reddit".to_string(), 3_600);
                m.insert("hn".to_string(), 21_600);
                m
            },
            structured_data_max_bytes: 65_536,
            ladder_word_threshold_strategy1: 30,
            ladder_word_threshold_strategy2: 200,
            ladder_body_multiplier: 2.0,
            antibot_cookie_warmup: true,
            antibot_max_body_scan_bytes: 150_000,
        }
    }
}

impl Config {
    pub fn ask_config(&self) -> AskConfig {
        AskConfig {
            ask_max_context_chars: self.ask_max_context_chars,
            ask_candidate_limit: self.ask_candidate_limit,
            ask_chunk_limit: self.ask_chunk_limit,
            ask_full_docs: self.ask_full_docs,
            ask_backfill_chunks: self.ask_backfill_chunks,
            ask_doc_fetch_concurrency: self.ask_doc_fetch_concurrency,
            ask_doc_chunk_limit: self.ask_doc_chunk_limit,
            ask_min_relevance_score: self.ask_min_relevance_score,
            ask_authoritative_domains: self.ask_authoritative_domains.clone(),
            ask_authoritative_boost: self.ask_authoritative_boost,
            ask_min_citations_nontrivial: self.ask_min_citations_nontrivial,
            ask_diagnostics: self.ask_diagnostics,
            ask_hybrid_candidates: self.ask_hybrid_candidates,
        }
    }
}

impl Config {
    /// Construct a minimal `Config` with default tuning applied.
    pub fn default_minimal() -> Self {
        let mut cfg = Self::default();
        crate::config::parse::tuning::apply_default_minimal_tuning(&mut cfg);
        cfg
    }
}

#[cfg(any(test, feature = "test-util"))]
impl Config {
    /// Construct a minimal `Config` suitable for unit tests.
    /// Uses `Config::default()` as the base so new non-Option fields
    /// do not require manual updates across test helpers.
    pub fn test_default() -> Self {
        Self {
            tavily_api_key: "test-key".to_string(),
            ..Default::default()
        }
    }
}
