use std::path::Path;

use anyhow::Result;
use serde_json::Value;

use super::super::artifact::SchemaArtifact;
use super::super::rel;
use super::super::schema_json::{json_string, schema_defs};
use super::super::source_input::{SourceInput, source_inputs};
use super::{enum_defs, schema_bundle};

pub(super) fn provider_artifacts(root: &Path) -> Result<Vec<SchemaArtifact>> {
    let inputs = source_inputs(
        root,
        &[
            "crates/axon-api/src/source/capability.rs",
            "crates/axon-embedding/src/provider.rs",
            "crates/axon-embedding/src/fake.rs",
            "crates/axon-llm/src/provider.rs",
            "crates/axon-llm/src/fake.rs",
            "crates/axon-vectors/src/store.rs",
            "crates/axon-adapters/src/boundary.rs",
            "crates/axon-core/src/boundary.rs",
            "crates/axon-authz/src/policy.rs",
            "crates/axon-observe/src/reservation.rs",
            "docs/pipeline-unification/runtime/provider-contract.md",
            "docs/pipeline-unification/schemas/provider-capability-schema.md",
        ],
    )?;
    let defs = schema_defs(&provider_schema_defs(), Some(enum_defs("providers")));
    let schema = schema_bundle(
        "https://axon.local/schemas/runtime/provider-capabilities.schema.json",
        "AxonProviderCapabilitySchema",
        "cargo xtask schemas providers",
        &[
            "axon-api",
            "axon-embedding",
            "axon-llm",
            "axon-vectors",
            "axon-adapters",
            "axon-core",
            "axon-authz",
            "axon-observe",
        ],
        &inputs,
        defs,
    );
    Ok(vec![
        SchemaArtifact::new(
            rel("docs/reference/runtime/provider-capabilities.schema.json"),
            json_string(&schema)?,
        ),
        SchemaArtifact::new(
            rel("docs/reference/runtime/provider-capabilities.md"),
            provider_markdown(&inputs),
        ),
    ])
}

fn provider_schema_defs() -> Vec<(&'static str, Value)> {
    vec![
        (
            "ProviderCapability",
            schemars::schema_for!(axon_api::source::ProviderCapability).into(),
        ),
        (
            "ProviderLimits",
            schemars::schema_for!(axon_api::source::ProviderLimits).into(),
        ),
        (
            "ReservationPolicy",
            schemars::schema_for!(axon_api::source::ReservationPolicy).into(),
        ),
        (
            "ReservationStateSnapshot",
            schemars::schema_for!(axon_api::source::ReservationStateSnapshot).into(),
        ),
        (
            "ProviderCostClass",
            schemars::schema_for!(axon_api::source::ProviderCostClass).into(),
        ),
        (
            "DegradedMode",
            schemars::schema_for!(axon_api::source::DegradedMode).into(),
        ),
        (
            "EmbeddingProviderCapability",
            schemars::schema_for!(axon_api::source::EmbeddingProviderCapability).into(),
        ),
        (
            "LlmProviderCapability",
            schemars::schema_for!(axon_api::source::LlmProviderCapability).into(),
        ),
        (
            "VectorStoreCapability",
            schemars::schema_for!(axon_api::source::VectorStoreCapability).into(),
        ),
        (
            "FetchProviderCapability",
            schemars::schema_for!(axon_api::source::FetchProviderCapability).into(),
        ),
        (
            "RenderProviderCapability",
            schemars::schema_for!(axon_api::source::RenderProviderCapability).into(),
        ),
        (
            "CredentialProviderCapability",
            schemars::schema_for!(axon_api::source::CredentialProviderCapability).into(),
        ),
    ]
}

fn provider_markdown(inputs: &[SourceInput]) -> String {
    let mut output = String::from(
        "<!-- generated by cargo xtask schemas providers; do not edit directly -->\n\n",
    );
    output.push_str("# Provider Capability Schema Reference\n\n");
    output.push_str("Generated by `cargo xtask schemas providers`.\n\n");
    output.push_str("## Contract\n\n");
    output.push_str(
        "Provider capabilities report health, limits, cooling, reservation policy, reservation state, degraded modes, cost class, and family-specific capability details.\n\n",
    );
    output.push_str("## Required Common Fields\n\n");
    for field in [
        "provider_id",
        "provider_kind",
        "implementation",
        "version",
        "health",
        "limits",
        "features",
        "reservation_policy",
        "reservation_state",
        "cost_class",
        "degraded_modes",
        "fake_overrides_supported",
    ] {
        output.push_str(&format!("- `{field}`\n"));
    }
    output.push_str("\n## Source Inputs\n\n");
    output.push_str("| Path | SHA-256 |\n|---|---|\n");
    for input in inputs {
        output.push_str(&format!("| `{}` | `{}` |\n", input.path, input.checksum));
    }
    output
}
