use serde_json::Value;

use super::*;

pub(super) fn markdown(inputs: &[SourceInput], registry: &StaticVectorPayloadContract) -> String {
    let mut out = String::from(
        "<!-- generated by cargo xtask schemas vector-payload; do not edit directly -->\n\n# vector-payload Schema Reference\n\n## Overview\n\nGenerated by `cargo xtask schemas vector-payload`.\n\n## Generated Artifacts\n\nSee the family contract for declared output paths.\n\n",
    );
    out.push_str("## Source Inputs\n\n| Path | SHA-256 |\n|---|---|\n");
    for input in inputs {
        out.push_str(&format!("| `{}` | `{}` |\n", input.path, input.checksum));
    }
    out.push_str("\n## Root Shape\n\nGenerated JSON schema object with vector payload definitions and Qdrant index plan annotations.\n\n");
    out.push_str(
        "## Required Definitions\n\nSee `docs/reference/sources/vector-payload.schema.json`.\n\n",
    );
    out.push_str("## Field Tables\n\n| Field | Schema |\n|---|---|\n");
    for field in registry.required_fields {
        out.push_str(&format!(
            "| `{field}` | `{}` |\n",
            display_schema(&shared_field_schema(field))
        ));
    }
    out.push_str("\nGeneration fields are deliberately split: `source_generation` is the staged source generation written during prepare/vector-point construction, while `committed_generation` is `null` until a later publisher promotes a complete generation. Retrieval generation filters target `committed_generation`.\n");

    out.push_str("\n## Redaction Guardrails\n\n");
    out.push_str("Payload validation applies metadata and locator guardrails before vector writes. `chunk_text` is treated as document body text and is not rejected merely for containing examples such as local paths or HTML snippets, but auth headers, cookies, dotenv-style assignments, bare secret tokens, and adapter response markers still fail closed.\n\n");
    out.push_str("| Category | Values |\n|---|---|\n");
    out.push_str(&format!(
        "| Forbidden field fragments | `{}` |\n",
        FORBIDDEN_FIELD_FRAGMENTS.join("`, `")
    ));
    out.push_str(&format!(
        "| Forbidden value fragments | `{}` |\n",
        FORBIDDEN_VALUE_FRAGMENTS.join("`, `")
    ));
    out.push_str(&format!(
        "| Bare token prefixes | `{}` |\n",
        BARE_SECRET_TOKEN_PREFIXES.join("`, `")
    ));

    out.push_str("\n## Enum Tables\n\nVisibility and source-family enum values are generated in the JSON schema definitions.\n\n");
    out.push_str("## Extension Points\n\nSource-specific metadata families are declared by the vector payload registry.\n\n");
    out.push_str("## Forbidden Fields\n\n");
    out.push_str("Payload validation rejects secret field fragments and secret value fragments before public writes.\n\n");
    out.push_str("\n## Source-Specific Families\n\n| Family | Fields |\n|---|---|\n");
    for (family, fields) in registry.source_families {
        out.push_str(&format!("| `{}` | `{}` |\n", family, fields.join("`, `")));
    }

    out.push_str("\n## Indexable Payload Fields\n\n");
    out.push_str("This table lists schema-declared payload fields that may be indexed by a vector-store collection spec. Runtime Qdrant index creation uses the normalized `CollectionSpec.payload_indexes`; the required retrieval indexes are owned by `axon-vectors::collection`.\n\n");
    out.push_str("| Field | Schema |\n|---|---|\n");
    for index in index_plan(registry)["indexes"].as_array().unwrap() {
        out.push_str(&format!(
            "| `{}` | `{}` |\n",
            index["field_name"].as_str().unwrap(),
            index["field_schema"].as_str().unwrap()
        ));
    }

    out.push_str("\n## API DTO Coverage\n\n");
    out.push_str(
        "Vector payload docs are paired with the DTO definitions in `docs/reference/api/schemas.json`.\n\n",
    );
    out.push_str("| DTO |\n|---|\n");
    for dto in VECTOR_API_DTOS {
        out.push_str(&format!("| `{dto}` |\n"));
    }

    out.push_str("\n## Examples\n\nExamples validate through the vector-payload fixture set.\n\n");
    out.push_str("## Fixture Paths\n\n`xtask/tests/fixtures/schemas/vector-payload`.\n\n");
    out.push_str("## Drift Checks\n\nRun `cargo xtask schemas vector-payload --check`.\n");
    out
}

fn display_schema(schema: &Value) -> String {
    if let Some(reference) = schema.get("$ref").and_then(Value::as_str) {
        return reference.to_string();
    }
    let mut parts = Vec::new();
    match schema.get("type") {
        Some(Value::String(kind)) => parts.push(kind.clone()),
        Some(Value::Array(kinds)) => parts.push(
            kinds
                .iter()
                .filter_map(Value::as_str)
                .collect::<Vec<_>>()
                .join(" | "),
        ),
        _ => parts.push("unknown".to_string()),
    }
    if let Some(value) = schema.get("const").and_then(Value::as_str) {
        parts.push(format!("const={value}"));
    }
    if let Some(values) = schema.get("enum").and_then(Value::as_array) {
        let values = values
            .iter()
            .filter_map(Value::as_str)
            .collect::<Vec<_>>()
            .join("|");
        parts.push(format!("enum={values}"));
    }
    if let Some(format) = schema.get("format").and_then(Value::as_str) {
        parts.push(format!("format={format}"));
    }
    if let Some(minimum) = schema.get("minimum") {
        parts.push(format!("minimum={minimum}"));
    }
    if let Some(min_length) = schema.get("minLength") {
        parts.push(format!("minLength={min_length}"));
    }
    parts.join("; ")
}
