use super::*;

pub(super) fn bump(
    root: &Path,
    component_id: &str,
    level: Option<BumpLevel>,
    skip_changelog: bool,
) -> ReleaseResult<()> {
    let manifest = load_manifest(root)?;
    let component = manifest
        .components
        .iter()
        .find(|component| component.id == component_id)
        .with_release_context(|| format!("unknown release component {component_id}"))?;
    let current = read_version(root, &component.version_source)?;
    let current = Version::parse(&current).with_release_context(|| {
        format!("{} version is not valid semver: {current}", component.id)
    })?;

    // Tolerate a missing/headless git context (e.g. unit fixtures): fall back to
    // bumping from version_source. The release gate still enforces monotonicity.
    let latest_tag_version = latest_tag(root, &component.tag_prefix)
        .ok()
        .flatten()
        .as_deref()
        .and_then(|tag| tag.strip_prefix(component.tag_prefix.as_str()))
        .and_then(|version| Version::parse(version).ok());

    let next_version = match level {
        Some(level) => cliff::resolve_next(&current, latest_tag_version.as_ref(), level),
        None => cliff::next_version(root, component, &current, latest_tag_version.as_ref())?,
    };
    let next = next_version.to_string();

    for file in &component.version_files {
        // The changelog is generated by git-cliff (real entries), not stamped.
        if file.kind == VersionKind::ChangelogHeading {
            if skip_changelog {
                let path = root.join(&file.path);
                let content = std::fs::read_to_string(&path)
                    .with_release_context(|| format!("failed to read {}", file.path))?;
                let updated = ensure_changelog_heading(&content, &next)?;
                if updated != content {
                    std::fs::write(&path, updated)
                        .with_release_context(|| format!("failed to write {}", file.path))?;
                }
            } else {
                cliff::prepend_changelog(root, component, &next_version, &file.path)?;
            }
            continue;
        }

        let path = root.join(&file.path);
        let content = std::fs::read_to_string(&path)
            .with_release_context(|| format!("failed to read {}", file.path))?;
        let updated = match file.kind {
            VersionKind::CargoPackage => {
                replace_cargo_package_version(&content, file.package.as_deref(), &next)?
            }
            VersionKind::CargoLockPackage => {
                replace_cargo_lock_package_version(&content, file.package.as_deref(), &next)?
            }
            VersionKind::ReadmeVersionLine => replace_readme_version_line(&content, &next)?,
            VersionKind::ChangelogHeading => unreachable!("changelog handled above"),
            VersionKind::JsonVersion => {
                replace_json_version(&content, file.json_pointer.as_deref(), &next)?
            }
            VersionKind::JsonNoVersion => content.clone(),
            VersionKind::NpmPackageLock => {
                replace_npm_package_lock_version(&content, file.package.as_deref(), &next)?
            }
            VersionKind::GradleVersionName => replace_gradle_version_name(&content, &next)?,
            VersionKind::GradleVersionCode => increment_gradle_version_code(&content)?,
        };
        if updated != content {
            std::fs::write(&path, updated)
                .with_release_context(|| format!("failed to write {}", file.path))?;
        }
    }

    println!("bumped {} to {next}", component.id);
    Ok(())
}
