use super::{Component, ReleaseContext, ReleaseResult, VersionFile, VersionKind};
use regex::Regex;
use std::path::Path;

mod readme;
mod writers;

use writers::{
    replace_cargo_package_version, replace_changelog_heading, replace_json_version,
    replace_npm_package_lock_version, replace_workspace_package_version,
};

pub(super) const MAX_ANDROID_VERSION_CODE: u64 = 2_100_000_000;

pub(super) fn read_version(root: &Path, file: &VersionFile) -> ReleaseResult<String> {
    let path = root.join(&file.path);
    let content = std::fs::read_to_string(&path)
        .with_release_context(|| format!("failed to read {}", file.path))?;
    match file.kind {
        VersionKind::CargoPackage => read_cargo_package_version(&content, file.package.as_deref())
            .with_release_context(|| {
                format!("failed to read Cargo package version from {}", file.path)
            }),
        VersionKind::CargoLockPackage => {
            read_cargo_lock_package_version(&content, file.package.as_deref()).with_release_context(
                || {
                    format!(
                        "failed to read Cargo.lock package version from {}",
                        file.path
                    )
                },
            )
        }
        VersionKind::JsonVersion => read_json_version(&content, file.json_pointer.as_deref())
            .with_release_context(|| format!("failed to read JSON version from {}", file.path)),
        VersionKind::NpmPackageLock => {
            read_npm_package_lock_version(&content, file.package.as_deref()).with_release_context(
                || format!("failed to read npm package-lock version from {}", file.path),
            )
        }
        VersionKind::GradleVersionName => read_gradle_version_name(&content)
            .with_release_context(|| format!("failed to read versionName from {}", file.path)),
        VersionKind::ReadmeVersionLine
        | VersionKind::ChangelogHeading
        | VersionKind::JsonNoVersion
        | VersionKind::GradleVersionCode => {
            release_bail!("{:?} is not a canonical version source", file.kind)
        }
    }
}

pub(super) fn check_component_parity(
    root: &Path,
    component: &Component,
    expected: &str,
) -> ReleaseResult<Vec<String>> {
    let mut errors = Vec::new();
    for file in &component.version_files {
        let content = match std::fs::read_to_string(root.join(&file.path)) {
            Ok(content) => content,
            Err(error) => {
                errors.push(format!("{}: failed to read: {error}", file.path));
                continue;
            }
        };
        let result = match file.kind {
            VersionKind::CargoPackage => {
                check_cargo_package_version(&content, file.package.as_deref(), expected)
            }
            VersionKind::CargoLockPackage => {
                check_cargo_lock_package_version(&content, file.package.as_deref(), expected)
            }
            VersionKind::ReadmeVersionLine => readme::check_version_line(&content, expected),
            VersionKind::ChangelogHeading => check_changelog_heading(&content, expected),
            VersionKind::JsonVersion => {
                check_json_version(&content, file.json_pointer.as_deref(), expected)
            }
            VersionKind::JsonNoVersion => check_json_no_version(&content),
            VersionKind::NpmPackageLock => {
                check_npm_package_lock_version(&content, file.package.as_deref(), expected)
            }
            VersionKind::GradleVersionName => check_gradle_version_name(&content, expected),
            VersionKind::GradleVersionCode => check_gradle_version_code_present(&content),
        };
        if let Err(error) = result {
            errors.push(format!("{}: {error}", file.path));
        }
    }
    Ok(errors)
}

/// Write `next` into a single version-bearing file, dispatching by
/// [`VersionKind`] the same way [`check_component_parity`] reads/checks one.
/// Used by the manual `bump-version` fallback for components release-please
/// no longer manages (currently only `cli` — see `release/components.toml`).
///
/// `CargoLockPackage` is deliberately unsupported here: Cargo.lock isn't a
/// hand-editable text replace, it's regenerated by `cargo update --precise`
/// after the owning `Cargo.toml` is written — the caller handles that
/// separately (mirroring the release-please fixup path's `run_cargo_update`).
/// `JsonNoVersion` is a no-op by design (that file must never carry a
/// version key at all).
pub(super) fn write_version_file(root: &Path, file: &VersionFile, next: &str) -> ReleaseResult<()> {
    let path = root.join(&file.path);
    let content = std::fs::read_to_string(&path)
        .with_release_context(|| format!("failed to read {}", file.path))?;
    let updated = match file.kind {
        VersionKind::CargoPackage => {
            let updated = replace_cargo_package_version(&content, next)?;
            replace_workspace_package_version(&updated, next)?
        }
        VersionKind::ReadmeVersionLine => readme::replace_version_line(&content, next)?,
        VersionKind::ChangelogHeading => replace_changelog_heading(&content, next)?,
        VersionKind::JsonVersion => {
            replace_json_version(&content, file.json_pointer.as_deref(), next)?
        }
        VersionKind::NpmPackageLock => {
            replace_npm_package_lock_version(&content, file.package.as_deref(), next)?
        }
        VersionKind::GradleVersionName => replace_gradle_version_name(&content, next)?,
        VersionKind::JsonNoVersion => content.clone(),
        VersionKind::CargoLockPackage => {
            release_bail!(
                "{} is a Cargo.lock entry; regenerate it with `cargo update`, not a direct write",
                file.path
            )
        }
        VersionKind::GradleVersionCode => {
            release_bail!(
                "{} needs the Android-specific fixup writer, not this one",
                file.path
            )
        }
    };
    if updated != content {
        std::fs::write(&path, updated)
            .with_release_context(|| format!("failed to write {}", file.path))?;
    }
    Ok(())
}

pub(super) fn read_cargo_package_version(
    content: &str,
    package: Option<&str>,
) -> ReleaseResult<String> {
    let value: toml::Value = toml::from_str(content).release_context("invalid TOML")?;
    let package_table = value
        .get("package")
        .and_then(|value| value.as_table())
        .release_context("missing [package] table")?;
    if let Some(expected_name) = package {
        let name = package_table
            .get("name")
            .and_then(|value| value.as_str())
            .release_context("missing package.name")?;
        if name != expected_name {
            release_bail!("expected package {expected_name}, found {name}");
        }
    }
    package_table
        .get("version")
        .and_then(|value| value.as_str())
        .map(ToOwned::to_owned)
        .release_context("missing package.version")
}

/// Read `[workspace.package] version` if the manifest declares one.
///
/// Returns `Ok(None)` when there is no `[workspace.package]` table or it carries
/// no string `version` (e.g. a workspace that shares only `edition`). Used to
/// enforce that the workspace-inherited version — which every extracted crate
/// picks up via `version.workspace = true`, and therefore every crate's
/// `CARGO_PKG_VERSION` — stays equal to the product's `[package] version`.
pub(super) fn read_workspace_package_version(content: &str) -> ReleaseResult<Option<String>> {
    let value: toml::Value = toml::from_str(content).release_context("invalid TOML")?;
    Ok(value
        .get("workspace")
        .and_then(|workspace| workspace.get("package"))
        .and_then(|package| package.get("version"))
        .and_then(|version| version.as_str())
        .map(ToOwned::to_owned))
}

pub(super) fn read_cargo_lock_package_version(
    content: &str,
    package: Option<&str>,
) -> ReleaseResult<String> {
    let package = package.release_context("cargo_lock_package requires package")?;
    let section = cargo_lock_package_section(content, package)
        .with_release_context(|| format!("missing Cargo.lock package {package}"))?;
    cargo_lock_field(section, "version")
        .with_release_context(|| format!("missing Cargo.lock package {package} version"))
}

pub(super) fn read_json_version(content: &str, pointer: Option<&str>) -> ReleaseResult<String> {
    let value: serde_json::Value = serde_json::from_str(content).release_context("invalid JSON")?;
    let pointer = pointer.unwrap_or("/version");
    value
        .pointer(pointer)
        .and_then(|value| value.as_str())
        .map(ToOwned::to_owned)
        .with_release_context(|| format!("missing JSON version field at {pointer}"))
}

pub(super) fn read_npm_package_lock_version(
    content: &str,
    package: Option<&str>,
) -> ReleaseResult<String> {
    let package = package.release_context("npm_package_lock requires package")?;
    let value: serde_json::Value = serde_json::from_str(content).release_context("invalid JSON")?;
    let root_name = value
        .get("name")
        .and_then(|value| value.as_str())
        .release_context("missing package-lock root name")?;
    if root_name != package {
        release_bail!("expected package-lock package {package}, found {root_name}");
    }
    let root_version = value
        .get("version")
        .and_then(|value| value.as_str())
        .release_context("missing package-lock root version")?;
    let package_version = value
        .pointer("/packages/")
        .and_then(|value| value.get("version"))
        .and_then(|value| value.as_str())
        .release_context("missing package-lock packages[''] version")?;
    if root_version != package_version {
        release_bail!(
            "package-lock root version {root_version} does not match packages[''] version {package_version}"
        );
    }
    Ok(root_version.to_owned())
}

pub(super) fn read_gradle_version_name(content: &str) -> ReleaseResult<String> {
    let regex = Regex::new(r#"(?m)^\s*versionName\s*=\s*"([^"]+)""#)
        .release_context("invalid versionName regex")?;
    regex
        .captures(content)
        .and_then(|captures| captures.get(1))
        .map(|value| value.as_str().to_owned())
        .release_context("missing versionName")
}

pub(super) fn read_gradle_version_code(content: &str) -> ReleaseResult<u64> {
    let regex = Regex::new(r#"(?m)^\s*versionCode\s*=\s*(\d+)"#)
        .release_context("invalid versionCode regex")?;
    regex
        .captures(content)
        .and_then(|captures| captures.get(1))
        .release_context("missing versionCode")?
        .as_str()
        .parse()
        .release_context("versionCode is not an integer")
        .and_then(validate_gradle_version_code)
}

fn check_cargo_package_version(
    content: &str,
    package: Option<&str>,
    expected: &str,
) -> ReleaseResult<()> {
    let actual = read_cargo_package_version(content, package)?;
    if actual != expected {
        release_bail!("expected package version {expected}, found {actual}");
    }
    Ok(())
}

fn check_cargo_lock_package_version(
    content: &str,
    package: Option<&str>,
    expected: &str,
) -> ReleaseResult<()> {
    let actual = read_cargo_lock_package_version(content, package)?;
    if actual != expected {
        release_bail!("expected Cargo.lock package version {expected}, found {actual}");
    }
    Ok(())
}

fn check_changelog_heading(content: &str, expected: &str) -> ReleaseResult<()> {
    let expected = format!("## [{expected}]");
    if !content.lines().any(|line| line.starts_with(&expected)) {
        release_bail!("missing '{expected}' heading");
    }
    Ok(())
}

fn check_json_version(content: &str, pointer: Option<&str>, expected: &str) -> ReleaseResult<()> {
    let actual = read_json_version(content, pointer)?;
    if actual != expected {
        release_bail!("expected JSON version {expected}, found {actual}");
    }
    Ok(())
}

fn check_npm_package_lock_version(
    content: &str,
    package: Option<&str>,
    expected: &str,
) -> ReleaseResult<()> {
    let actual = read_npm_package_lock_version(content, package)?;
    if actual != expected {
        release_bail!("expected package-lock version {expected}, found {actual}");
    }
    Ok(())
}

fn check_json_no_version(content: &str) -> ReleaseResult<()> {
    let value: serde_json::Value = serde_json::from_str(content).release_context("invalid JSON")?;
    if contains_json_version_key(&value) {
        release_bail!("must not contain a version key");
    }
    Ok(())
}

fn contains_json_version_key(value: &serde_json::Value) -> bool {
    match value {
        serde_json::Value::Object(map) => {
            map.contains_key("version") || map.values().any(contains_json_version_key)
        }
        serde_json::Value::Array(values) => values.iter().any(contains_json_version_key),
        _ => false,
    }
}

fn check_gradle_version_name(content: &str, expected: &str) -> ReleaseResult<()> {
    let actual = read_gradle_version_name(content)?;
    if actual != expected {
        release_bail!("expected versionName {expected}, found {actual}");
    }
    Ok(())
}

fn check_gradle_version_code_present(content: &str) -> ReleaseResult<()> {
    read_gradle_version_code(content)?;
    Ok(())
}

pub(super) fn replace_gradle_version_name(content: &str, next: &str) -> ReleaseResult<String> {
    let regex = Regex::new(r#"(?m)^(\s*versionName\s*=\s*)"[^"]+""#)
        .release_context("invalid versionName replacement regex")?;
    if !regex.is_match(content) {
        release_bail!("missing versionName");
    }
    Ok(regex.replace(content, format!(r#"$1"{next}""#)).to_string())
}

pub(super) fn increment_gradle_version_code(content: &str) -> ReleaseResult<String> {
    let regex = Regex::new(r#"(?m)^(\s*versionCode\s*=\s*)(\d+)"#)
        .release_context("invalid versionCode replacement regex")?;
    let captures = regex
        .captures(content)
        .release_context("missing versionCode")?;
    let current: u64 = captures[2]
        .parse()
        .release_context("versionCode is not an integer")?;
    validate_gradle_version_code(current)?;
    let next = current
        .checked_add(1)
        .release_context("versionCode overflowed while bumping")?;
    validate_gradle_version_code(next)?;
    Ok(regex.replace(content, format!("${{1}}{next}")).to_string())
}

fn validate_gradle_version_code(code: u64) -> ReleaseResult<u64> {
    if code == 0 || code > MAX_ANDROID_VERSION_CODE {
        release_bail!("versionCode {code} must be between 1 and {MAX_ANDROID_VERSION_CODE}");
    }
    Ok(code)
}

fn cargo_lock_package_section<'a>(content: &'a str, package: &str) -> Option<&'a str> {
    content
        .split("[[package]]")
        .skip(1)
        .find(|section| cargo_lock_field(section, "name").as_deref() == Some(package))
}

fn cargo_lock_field(section: &str, key: &str) -> Option<String> {
    section
        .lines()
        .find_map(|line| cargo_lock_assignment(line.trim(), key))
}

fn cargo_lock_assignment(line: &str, key: &str) -> Option<String> {
    let prefix = format!("{key} = ");
    line.strip_prefix(&prefix)
        .and_then(|value| value.trim().strip_prefix('"')?.strip_suffix('"'))
        .map(ToOwned::to_owned)
}
