#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RestRouteContract {
    pub method: &'static str,
    pub path: &'static str,
    pub schema_name: &'static str,
    pub fields: &'static [&'static str],
}

pub fn rest_route_contracts() -> &'static [RestRouteContract] {
    REST_ROUTE_CONTRACTS
}

const REST_ROUTE_CONTRACTS: &[RestRouteContract] = &[
    RestRouteContract {
        method: "POST",
        path: "/v1/scrape",
        schema_name: "RestScrapeRequest",
        fields: &[
            "collection",
            "embed",
            "exclude_selector",
            "format",
            "headers",
            "render_mode",
            "root_selector",
            "url",
            "urls",
        ],
    },
    RestRouteContract {
        method: "POST",
        path: "/v1/summarize",
        schema_name: "RestSummarizeRequest",
        fields: &[
            "exclude_selector",
            "headers",
            "render_mode",
            "root_selector",
            "url",
            "urls",
        ],
    },
    RestRouteContract {
        method: "POST",
        path: "/v1/summarize/stream",
        schema_name: "RestSummarizeRequest",
        fields: &[
            "exclude_selector",
            "headers",
            "render_mode",
            "root_selector",
            "url",
            "urls",
        ],
    },
    RestRouteContract {
        method: "POST",
        path: "/v1/crawl",
        schema_name: "RestCrawlRequest",
        fields: &[
            "collection",
            "delay_ms",
            "discover_llms_txt",
            "discover_sitemaps",
            "headers",
            "include_subdomains",
            "max_depth",
            "max_llms_txt_urls",
            "max_pages",
            "max_sitemaps",
            "render_mode",
            "respect_robots",
            "sitemap_since_days",
            "urls",
        ],
    },
    RestRouteContract {
        method: "POST",
        path: "/v1/extract",
        schema_name: "RestExtractRequest",
        fields: &[
            "collection",
            "embed",
            "headers",
            "max_pages",
            "mode",
            "prompt",
            "render_mode",
            "urls",
        ],
    },
    RestRouteContract {
        method: "POST",
        path: "/v1/embed",
        schema_name: "RestEmbedRequest",
        fields: &["collection", "input", "source_type"],
    },
    RestRouteContract {
        method: "POST",
        path: "/v1/ingest",
        schema_name: "RestIngestRequest",
        fields: &["include_source", "sessions", "source_type", "target"],
    },
    RestRouteContract {
        method: "POST",
        path: "/v1/query",
        schema_name: "RestQueryRequest",
        fields: &["collection", "limit", "offset", "query"],
    },
    RestRouteContract {
        method: "POST",
        path: "/v1/retrieve",
        schema_name: "RestRetrieveRequest",
        fields: &["collection", "cursor", "max_points", "token_budget", "url"],
    },
    RestRouteContract {
        method: "POST",
        path: "/v1/evaluate",
        schema_name: "RestEvaluateRequest",
        fields: &["collection", "question"],
    },
    RestRouteContract {
        method: "POST",
        path: "/v1/suggest",
        schema_name: "RestSuggestRequest",
        fields: &["collection", "focus"],
    },
    RestRouteContract {
        method: "POST",
        path: "/v1/map",
        schema_name: "RestMapRequest",
        fields: &["limit", "offset", "url"],
    },
    RestRouteContract {
        method: "POST",
        path: "/v1/search",
        schema_name: "RestSearchRequest",
        fields: &["limit", "offset", "query", "time_range"],
    },
    RestRouteContract {
        method: "POST",
        path: "/v1/research",
        schema_name: "RestResearchRequest",
        fields: &["limit", "offset", "query", "time_range"],
    },
    RestRouteContract {
        method: "POST",
        path: "/v1/research/stream",
        schema_name: "RestResearchRequest",
        fields: &["limit", "offset", "query", "time_range"],
    },
    RestRouteContract {
        method: "POST",
        path: "/v1/brand",
        schema_name: "RestBrandRequest",
        fields: &["url"],
    },
    RestRouteContract {
        method: "POST",
        path: "/v1/diff",
        schema_name: "RestDiffRequest",
        fields: &["render_mode", "url_a", "url_b"],
    },
    RestRouteContract {
        method: "POST",
        path: "/v1/screenshot",
        schema_name: "RestScreenshotRequest",
        fields: &["full_page", "url", "viewport"],
    },
    RestRouteContract {
        method: "POST",
        path: "/v1/ask",
        schema_name: "RestAskRequest",
        fields: &[
            "ask_authoritative_boost",
            "ask_authoritative_domains",
            "ask_backfill_chunks",
            "ask_candidate_limit",
            "ask_chunk_limit",
            "ask_doc_chunk_limit",
            "ask_doc_fetch_concurrency",
            "ask_full_docs",
            "ask_hybrid_candidates",
            "ask_max_context_chars",
            "ask_min_citations_nontrivial",
            "ask_min_relevance_score",
            "before",
            "collection",
            "diagnostics",
            "explain",
            "hybrid_search",
            "query",
            "since",
        ],
    },
    RestRouteContract {
        method: "POST",
        path: "/v1/ask/stream",
        schema_name: "RestAskRequest",
        fields: &[
            "ask_authoritative_boost",
            "ask_authoritative_domains",
            "ask_backfill_chunks",
            "ask_candidate_limit",
            "ask_chunk_limit",
            "ask_doc_chunk_limit",
            "ask_doc_fetch_concurrency",
            "ask_full_docs",
            "ask_hybrid_candidates",
            "ask_max_context_chars",
            "ask_min_citations_nontrivial",
            "ask_min_relevance_score",
            "before",
            "collection",
            "diagnostics",
            "explain",
            "hybrid_search",
            "query",
            "since",
        ],
    },
    RestRouteContract {
        method: "POST",
        path: "/v1/chat",
        schema_name: "RestChatRequest",
        fields: &["message"],
    },
    RestRouteContract {
        method: "POST",
        path: "/v1/chat/stream",
        schema_name: "RestChatRequest",
        fields: &["message"],
    },
    RestRouteContract {
        method: "POST",
        path: "/v1/memory",
        schema_name: "RestMemoryRequest",
        fields: &[
            "body",
            "confidence",
            "depth",
            "edge_type",
            "file",
            "id",
            "limit",
            "memory_type",
            "project",
            "query",
            "repo",
            "source_id",
            "status",
            "subaction",
            "target_id",
            "title",
            "token_budget",
        ],
    },
];
