// generated by cargo xtask presentation generate; do not edit directly
// contract-version: 1.0.0 | source-hash: b0d52d4c5b22
// source of truth: docs/pipeline-unification/surfaces/presentation-contract.md

//! Presentation tokens for CLI truecolor/ANSI-256 output.

pub const CONTRACT_VERSION: &str = "1.0.0";
pub const SOURCE_HASH: &str = "b0d52d4c5b22";

/// Truecolor `(r, g, b)` per semantic color token (dark theme).
pub struct Rgb(pub u8, pub u8, pub u8);

pub const BACKGROUND: Rgb = Rgb(7, 19, 28);
pub const SURFACE: Rgb = Rgb(16, 35, 48);
pub const SURFACE_RAISED: Rgb = Rgb(19, 41, 58);
pub const BORDER: Rgb = Rgb(29, 61, 78);
pub const DIVIDER: Rgb = Rgb(29, 61, 78);
pub const TEXT_PRIMARY: Rgb = Rgb(230, 244, 251);
pub const TEXT_SECONDARY: Rgb = Rgb(167, 188, 201);
pub const TEXT_MUTED: Rgb = Rgb(167, 188, 201);
pub const TEXT_INVERSE: Rgb = Rgb(5, 21, 32);
pub const ACCENT: Rgb = Rgb(41, 182, 246);
pub const ACCENT_STRONG: Rgb = Rgb(103, 203, 250);
pub const SERVICE_NAME: Rgb = Rgb(249, 168, 196);
pub const AUTOMATION: Rgb = Rgb(167, 139, 250);
pub const SUCCESS: Rgb = Rgb(125, 211, 199);
pub const WARNING: Rgb = Rgb(198, 163, 107);
pub const ERROR: Rgb = Rgb(199, 132, 144);
pub const INFO: Rgb = Rgb(114, 200, 245);
pub const NEUTRAL: Rgb = Rgb(145, 168, 182);
pub const WAITING: Rgb = Rgb(114, 200, 245);
pub const DEGRADED: Rgb = Rgb(198, 163, 107);
pub const SOURCE: Rgb = Rgb(41, 182, 246);
pub const JOB: Rgb = Rgb(114, 200, 245);
pub const GRAPH: Rgb = Rgb(167, 139, 250);
pub const MEMORY: Rgb = Rgb(249, 168, 196);
pub const ARTIFACT: Rgb = Rgb(103, 203, 250);
pub const PROVIDER: Rgb = Rgb(145, 168, 182);
pub const FOCUS_RING: Rgb = Rgb(41, 182, 246);
pub const HOVER: Rgb = Rgb(23, 54, 75);
pub const SELECTED: Rgb = Rgb(41, 182, 246);
pub const DISABLED: Rgb = Rgb(167, 188, 201);

pub const FONT_SIZE_XS: u32 = 11;
pub const FONT_SIZE_SM: u32 = 13;
pub const FONT_SIZE_MD: u32 = 14;
pub const FONT_SIZE_LG: u32 = 18;
pub const FONT_SIZE_XL: u32 = 24;

/// CLI symbol fallback per icon slot (ASCII-safe; used with `LAB_SYMBOLS=ascii`).
pub struct IconSlot {
    pub intent: &'static str,
    pub slot: &'static str,
    pub cli_symbol: &'static str,
}

pub const ICONS: &[IconSlot] = &[
    IconSlot {
        intent: "success",
        slot: "icon.success",
        cli_symbol: "ok",
    },
    IconSlot {
        intent: "warning",
        slot: "icon.warning",
        cli_symbol: "!",
    },
    IconSlot {
        intent: "error",
        slot: "icon.error",
        cli_symbol: "x",
    },
    IconSlot {
        intent: "source",
        slot: "icon.source",
        cli_symbol: "src",
    },
    IconSlot {
        intent: "job",
        slot: "icon.job",
        cli_symbol: "job",
    },
    IconSlot {
        intent: "graph",
        slot: "icon.graph",
        cli_symbol: "graph",
    },
    IconSlot {
        intent: "memory",
        slot: "icon.memory",
        cli_symbol: "mem",
    },
    IconSlot {
        intent: "artifact",
        slot: "icon.artifact",
        cli_symbol: "file",
    },
    IconSlot {
        intent: "provider",
        slot: "icon.provider",
        cli_symbol: "svc",
    },
    IconSlot {
        intent: "refresh",
        slot: "icon.refresh",
        cli_symbol: "refresh",
    },
    IconSlot {
        intent: "watch",
        slot: "icon.watch",
        cli_symbol: "watch",
    },
    IconSlot {
        intent: "prune",
        slot: "icon.prune",
        cli_symbol: "prune",
    },
    IconSlot {
        intent: "search",
        slot: "icon.search",
        cli_symbol: "search",
    },
    IconSlot {
        intent: "ask",
        slot: "icon.ask",
        cli_symbol: "ask",
    },
];
