"""Markdown renderer for MCP schema documentation.

Takes parsed struct/enum definitions and produces the full
MCP-TOOL-SCHEMA.md content.
"""

from __future__ import annotations

from datetime import datetime, timezone

from mcp_schema_models import (
    CRAWL_FIELD_DESCRIPTIONS,
    MCP_AUTH_ENV_VARS,
    MCP_TRANSPORT_ENV_VARS,
    RUNTIME_ENV_VARS,
    RUNTIME_ENV_VARS_DEPRECATED,
    STRUCT_TO_ACTION,
    EnumDef,
    FieldDef,
    StructDef,
)


def generate_markdown(
    structs: dict[str, StructDef],
    enums: dict[str, EnumDef],
) -> str:
    """Produce the full MCP-TOOL-SCHEMA.md content."""
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    lines: list[str] = []

    def emit(text: str = "") -> None:
        lines.append(text)

    _emit_header(emit, today)
    _emit_contract(emit)
    _emit_task_augmented_calls(emit)
    _emit_success_envelope(emit)
    _emit_parser_rules(emit)

    # Classify actions
    lifecycle_actions, direct_actions = _classify_actions(structs)

    _emit_preferred_client_actions(emit, lifecycle_actions, direct_actions)
    _emit_response_policy(emit)
    _emit_direct_actions(emit, direct_actions, structs)
    _emit_crawl_parameters(emit, structs)
    _emit_lifecycle_families(emit, lifecycle_actions, structs, enums)
    _emit_ingest_source_types(emit, enums)
    _emit_sessions_ingest_options(emit, structs)
    _emit_enum_values(emit, enums)
    _emit_pagination(emit)
    _emit_mcp_resources(emit)
    _emit_runtime_dependencies(emit)
    _emit_error_semantics(emit)

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Section emitters
# ---------------------------------------------------------------------------


def _emit_header(emit, today: str) -> None:
    emit("# Axon MCP Tool Schema (Source of Truth)")
    emit(f"Last Modified: {today}")
    emit()
    emit(
        "<!-- AUTO-GENERATED by scripts/generate_mcp_schema_doc.py — do not edit manually -->"
    )
    emit()


def _emit_contract(emit) -> None:
    emit("## Contract")
    emit("- MCP server command: `axon mcp`")
    emit("- Tool count: `1`")
    emit("- Tool name: `axon`")
    emit("- Primary route field: `action`")
    emit("- Canonical route form: `action` + optional `subaction`")
    emit(
        "- Response control field: `response_mode` (`path|inline|both|auto_inline`; most actions default `path`, while `scrape`/`retrieve` default to inline paged reads)"
    )
    emit()
    emit("Code references:")
    emit("- `src/mcp/schema.rs`")
    emit("- `src/mcp/server.rs`")
    emit()


def _emit_task_augmented_calls(emit) -> None:
    emit("## Task-Augmented Calls")
    emit()
    emit("- Server capabilities advertise RMCP task support for `tools/call`.")
    emit(
        "- The routed `axon` tool advertises `execution.taskSupport: \"optional\"`; clients may use normal calls or task-augmented calls."
    )
    emit(
        "- `axon_status_dashboard` does not advertise task support. It is an MCP Apps widget tool, not a durable job task."
    )
    emit(
        "- Normal calls still return Axon's canonical JSON success envelope with `job_id` or `job_ids` fields for async starts."
    )
    emit(
        "- Task-augmented calls use RMCP task lifecycle methods backed by the same durable SQLite job rows."
    )
    emit(
        "- Supported task starts: `crawl.start`, `extract.start`, `embed.start`, and `ingest.start`."
    )
    emit(
        "- Unsupported task action/subaction pairs return `invalid_params`; immediate actions such as `help`, `status`, and `query` remain normal calls."
    )
    emit(
        "- Task IDs are stable aliases over Axon job IDs: `axon:<kind>:<job_uuid>`."
    )
    emit(
        "- Task-mode `crawl.start` accepts exactly one URL because one RMCP task maps to one Axon crawl job. Use normal non-task `crawl.start` for multi-URL crawl submissions."
    )
    emit(
        "- `tasks/get` and `tasks/cancel` return Task fields at top level; `tasks/result` waits until the job is terminal, then returns a compact sanitized payload instead of a raw `ServiceJob` row."
    )
    emit(
        "- Task objects include `pollInterval` of at least 5000 ms. Clients should not hot-poll SQLite-backed task status."
    )
    emit(
        "- If `_meta.progressToken` is supplied on a task call, Axon sends allowlisted `notifications/progress` updates from persisted job progress and stops on terminal status or send failure."
    )
    emit(
        "- MCP task metadata belongs in protocol request metadata (`_meta.progressToken` / task-augmented request fields), not inside the Axon tool argument map."
    )
    emit(
        "- Authorization is server-scoped: valid Axon OAuth/static credentials grant Axon server access. Job and task IDs are server-bound references, not per-user ACL objects."
    )
    emit()
    emit("See also:")
    emit()
    emit(
        "- [MCP overview](overview.md#task-augmented-calls) for normal versus task-augmented workflow guidance."
    )
    emit(
        "- [Configuration guide](../../guides/configuration.md) for server auth and async job runtime settings."
    )
    emit(
        "- [Architecture overview](../../architecture/stack/arch.md) for MCP, service, and job-runtime boundaries."
    )
    emit(
        "- [Repository guide](../../contributing/repo/repo.md) for source layout and testing policy."
    )
    emit(
        "- [This tool-schema reference](tool-schema.md#task-augmented-calls) for `tasks/get`, `tasks/cancel`, `tasks/result`, `_meta.progressToken`, and `axon:<kind>:<job_uuid>` wire details."
    )
    emit()


def _emit_success_envelope(emit) -> None:
    emit("## Canonical Success Envelope")
    emit("```json")
    emit("{")
    emit('  "ok": true,')
    emit('  "action": "<resolved action>",')
    emit('  "subaction": "<resolved subaction>",')
    emit('  "data": { "...": "..." }')
    emit("}")
    emit("```")
    emit()


def _emit_parser_rules(emit) -> None:
    emit("## Parser Rules")
    emit("Incoming request map is parsed strictly with serde:")
    emit()
    emit("- `action` is required and must match canonical schema names")
    emit(
        "- `subaction` is optional for lifecycle families "
        "(`crawl|extract|embed|ingest`); when omitted, handlers default to `start`"
    )
    emit("- No fallback fields (`command`, `op`, `operation`)")
    emit("- No token normalization or case folding")
    emit("- No action alias remapping")
    emit()


def _emit_preferred_client_actions(
    emit, lifecycle_actions: list[str], direct_actions: list[str]
) -> None:
    emit("## Preferred Client Actions")
    emit("Use CLI-identical top-level actions:")
    lifecycle_str = ", ".join(f"`{a}`" for a in sorted(lifecycle_actions))
    direct_str = ", ".join(f"`{a}`" for a in sorted(direct_actions))
    emit(f"- Lifecycle families: {lifecycle_str}")
    emit(f"- Direct actions: {direct_str}")
    emit()
    emit(
        "For lifecycle management (`status|cancel|list|cleanup|clear|recover`), "
        "use canonical families with `subaction`:"
    )
    emit()
    emit("```json")
    emit('{ "action": "ingest", "subaction": "status", "job_id": "..." }')
    emit("```")
    emit()


def _emit_response_policy(emit) -> None:
    emit("## Response Policy (Context-Safe Defaults)")
    emit("- Most actions default to artifact-first (`response_mode=path`).")
    emit("- `scrape` and `retrieve` are document-reading actions and default to inline-first paged responses.")
    emit(
        "- Heavy operations write result artifacts to `~/.axon/artifacts/<context>/` "
        "(override root with `AXON_MCP_ARTIFACT_DIR`)."
    )
    emit("- Tool response returns compact metadata only by default:")
    emit("  - `path`, `bytes`, `line_count`, `sha256`, `preview`, `preview_truncated`")
    emit("- Explicit `inline` and `both` modes are capped/truncated and include artifact pointers.")
    emit(
        "- `response_mode=auto_inline`/`auto-inline` selects threshold-based automatic inlining: "
        "small payloads return `auto-inline`, larger payloads return path metadata."
    )
    emit()


def _emit_direct_actions(
    emit, direct_actions: list[str], structs: dict[str, StructDef]
) -> None:
    emit("## Direct Actions")
    emit("These actions do not require `subaction`:")
    emit()
    emit("| Action | Required Fields | Optional Fields |")
    emit("|--------|----------------|-----------------|")
    for action in sorted(direct_actions):
        struct_name = _action_to_struct(action)
        sdef = structs.get(struct_name)
        if not sdef:
            continue
        handler_required = HANDLER_REQUIRED_FIELDS.get(action, set())
        optional_override = OPTIONAL_FIELD_OVERRIDES.get(action, set())
        def wire_required(field: FieldDef) -> bool:
            if field.name in handler_required:
                return True
            if field.name in optional_override:
                return False
            return not field.is_optional

        required = [f for f in [*sdef.required_fields(), *sdef.optional_fields()] if wire_required(f)]
        optional = [
            f
            for f in [*sdef.required_fields(), *sdef.optional_fields()]
            if f.name != "subaction" and not wire_required(f)
        ]
        req_str = ", ".join(
            f"{_field_name_with_aliases(f)} ({f.display_type})" for f in required
        ) or "--"
        opt_str = ", ".join(_field_name_with_aliases(f) for f in optional) or "--"
        emit(f"| `{action}` | {req_str} | {opt_str} |")
    if "ask" in direct_actions:
        emit()
        emit(
            "Note: `graph` is a deprecated compatibility field. `false`/unset is accepted as a no-op; `true` is rejected because graph retrieval is not wired in production."
        )
    if "search" in direct_actions:
        emit()
        emit(
            "Note: MCP `search` uses the same SearXNG-first/Tavily-fallback search-and-crawl service as the CLI and REST route. It queues one-page crawl jobs for returned URLs so terminal and agent searches are auto-indexed."
        )
    emit()


def _emit_crawl_parameters(emit, structs: dict[str, StructDef]) -> None:
    emit("## Crawl Start Parameters")
    emit(
        'Optional fields accepted on `{ "action": "crawl", "subaction": "start", ... }`:'
    )
    emit()
    emit("| Field | Type | Default | Description |")
    emit("|-------|------|---------|-------------|")
    crawl_struct = structs.get("CrawlRequest")
    if crawl_struct:
        for f in crawl_struct.optional_fields():
            if f.name in ("job_id", "limit", "offset", "response_mode"):
                continue  # Common lifecycle fields, not crawl-specific
            desc_info = CRAWL_FIELD_DESCRIPTIONS.get(f.name)
            default = desc_info[0] if desc_info else "--"
            desc = desc_info[1] if desc_info else ""
            emit(f"| `{f.name}` | {f.display_type} | {default} | {desc} |")
    emit()


def _emit_lifecycle_families(
    emit,
    lifecycle_actions: list[str],
    structs: dict[str, StructDef],
    enums: dict[str, EnumDef],
) -> None:
    emit("## Lifecycle Action Families")
    for action in sorted(lifecycle_actions):
        struct_name = _action_to_struct(action)
        sdef = structs.get(struct_name)
        if not sdef:
            continue
        enum_name = sdef.subaction_enum_name
        edef = enums.get(enum_name, None) if enum_name else None
        subactions = "|".join(edef.snake_variants()) if edef else "?"
        start_fields = _start_requirement_summary(action, sdef)
        emit(f"- `{action}`: `{subactions}` -- {start_fields}")
    emit()


def _emit_ingest_source_types(emit, enums: dict[str, EnumDef]) -> None:
    emit("## Ingest Source Types")
    ingest_enum = enums.get("IngestSourceType")
    if ingest_enum:
        emit()
        emit("| Source Type | Description |")
        emit("|------------|-------------|")
        source_descriptions: dict[str, str] = {
            "github": "Ingest GitHub repo (code, issues, PRs, wiki)",
            "reddit": "Ingest subreddit posts/comments",
            "youtube": "Ingest YouTube video transcript via yt-dlp",
            "sessions": "Ingest AI session exports (Claude/Codex/Gemini)",
        }
        for v in ingest_enum.snake_variants():
            desc = source_descriptions.get(v, "")
            emit(f"| `{v}` | {desc} |")
    emit()


def _emit_sessions_ingest_options(emit, structs: dict[str, StructDef]) -> None:
    sessions_struct = structs.get("SessionsIngestOptions")
    if sessions_struct:
        emit("### Sessions Ingest Options")
        emit(
            "When `source_type` is `sessions`, the optional `sessions` object accepts:"
        )
        emit()
        emit("| Field | Type | Description |")
        emit("|-------|------|-------------|")
        for f in sessions_struct.fields:
            emit(f"| `{f.name}` | {f.display_type} | -- |")
        emit()


def _emit_enum_values(emit, enums: dict[str, EnumDef]) -> None:
    emit("## Enum Values")
    emit()
    user_enums = [
        "ResponseMode",
        "McpRenderMode",
        "SearchTimeRange",
        "IngestSourceType",
    ]
    for enum_name in user_enums:
        edef = enums.get(enum_name)
        if not edef:
            continue
        emit(f"### `{enum_name}`")
        emit(f"Values: `{'|'.join(edef.snake_variants())}`")
        emit()


def _emit_pagination(emit) -> None:
    emit("## Pagination Defaults")
    emit(
        "List/search style endpoints default to low limits and accept `limit` + `offset`."
    )
    emit()


def _emit_mcp_resources(emit) -> None:
    emit("## MCP Resources")
    emit("Implemented resource(s):")
    emit("- `axon://schema/mcp-tool`")
    emit("- `ui://axon/status-dashboard`")
    emit()


def _emit_runtime_dependencies(emit) -> None:
    emit("## Runtime Dependencies")
    emit("Server reads existing Axon stack vars:")
    for entry in RUNTIME_ENV_VARS:
        if isinstance(entry, tuple):
            name, desc = entry
            emit(f"- `{name}` — {desc}")
        else:
            emit(f"- `{entry}`")
    emit()
    if RUNTIME_ENV_VARS_DEPRECATED:
        emit("> **Deprecated (compat shims — emit a warning at startup if set):**")
        joined = ", ".join(f"`{v}`" for v in RUNTIME_ENV_VARS_DEPRECATED)
        emit(f"> {joined} — still read at startup as compatibility shims;")
        emit("> setting them emits a startup warning. LLM synthesis runs through")
        emit("> the Gemini headless path exclusively.")
        emit()
    emit("MCP transport env vars:")
    for var in MCP_TRANSPORT_ENV_VARS:
        emit(f"- `{var}`")
    emit()
    emit("MCP auth env vars:")
    for var in MCP_AUTH_ENV_VARS:
        emit(f"- `{var}`")
    emit()


def _emit_error_semantics(emit) -> None:
    emit("## Error Semantics")
    emit("- Input or shape failures -> MCP `invalid_params`")
    emit("- Runtime failures -> MCP `internal_error`")
    emit()


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


HANDLER_REQUIRED_FIELDS: dict[str, set[str]] = {
    "ask": {"query"},
    "endpoints": {"url"},
    "evaluate": {"query"},
    "map": {"url"},
    "purge": {"target"},
    "query": {"query"},
    "research": {"query"},
    "retrieve": {"url"},
    "scrape": {"url"},
    "screenshot": {"url"},
    "search": {"query"},
}

OPTIONAL_FIELD_OVERRIDES: dict[str, set[str]] = {
    # `prefix` is a non-Option bool in Rust but has `#[serde(default)]`; clients
    # may omit it and receive the default `false`.
    "purge": {"prefix"},
}


def _classify_actions(
    structs: dict[str, StructDef],
) -> tuple[list[str], list[str]]:
    """Split actions into subaction families and direct singleton actions."""
    lifecycle_actions: list[str] = []
    direct_actions: list[str] = []
    for struct_name, action in sorted(STRUCT_TO_ACTION.items(), key=lambda x: x[1]):
        sdef = structs.get(struct_name)
        if sdef and sdef.subaction_enum_name:
            lifecycle_actions.append(action)
        else:
            direct_actions.append(action)
    return lifecycle_actions, direct_actions


def _action_to_struct(action: str) -> str:
    """Convert action name back to struct name."""
    for struct_name, act in STRUCT_TO_ACTION.items():
        if act == action:
            return struct_name
    return ""


def _field_name_with_aliases(field: FieldDef) -> str:
    text = f"`{field.name}`"
    if field.aliases:
        aliases = ", ".join(f"`{alias}`" for alias in field.aliases)
        text += f" (aliases: {aliases})"
    return text


def _start_requirement_summary(action: str, sdef: StructDef) -> str:
    """Summarize what the 'start' subaction requires."""
    match action:
        case "crawl":
            return "start requires `urls` (array)"
        case "extract":
            return "start requires `urls` (array)"
        case "embed":
            return "start requires `input` (string)"
        case "ingest":
            return (
                "start requires `target`; `source_type` is optional and "
                "auto-detected from `target` (github/gitlab/gitea/git/reddit/"
                "youtube/rss) when omitted"
            )
        case _:
            req = sdef.required_fields()
            if req:
                return "requires " + ", ".join(f"`{f.name}`" for f in req)
            return "no required fields"
