use super::*;
use std::fs;

fn seed(root: &std::path::Path) {
    fs::create_dir_all(root.join("docs/reference/cli")).unwrap();
    fs::write(
        root.join("docs/reference/cli/commands.json"),
        serde_json::to_string_pretty(&serde_json::json!({
            "x-axon": {
                "generated_by": "cargo xtask schemas cli",
                "source_inputs": [
                    {"path": "crates/axon-cli/src/lib.rs", "kind": "rust_module", "checksum": "sha256:aaa"}
                ],
            }
        }))
        .unwrap(),
    )
    .unwrap();
    fs::write(
        root.join("docs/reference/cli/commands.md"),
        "<!-- generated by cargo xtask schemas cli; do not edit directly -->\n\n# cli Schema Reference\n",
    )
    .unwrap();
}

#[test]
fn generate_writes_manifest_and_rewrites_header() {
    let dir = tempfile::tempdir().unwrap();
    seed(dir.path());
    run(
        dir.path(),
        &DocsGenerateArgs {
            check: false,
            family: None,
        },
    )
    .unwrap();

    let manifest_path = dir.path().join(manifest::MANIFEST_PATH);
    assert!(manifest_path.exists());
    let md = fs::read_to_string(dir.path().join("docs/reference/cli/commands.md")).unwrap();
    assert!(md.starts_with(
        "<!-- generated by cargo xtask docs generate --family cli; do not edit directly -->\n"
    ));
    assert!(md.contains("<!-- source inputs: sha256:"));
}

#[test]
fn generate_twice_is_byte_identical() {
    let dir = tempfile::tempdir().unwrap();
    seed(dir.path());
    let args = DocsGenerateArgs {
        check: false,
        family: None,
    };
    run(dir.path(), &args).unwrap();
    let manifest_1 = fs::read_to_string(dir.path().join(manifest::MANIFEST_PATH)).unwrap();
    let md_1 = fs::read_to_string(dir.path().join("docs/reference/cli/commands.md")).unwrap();

    run(dir.path(), &args).unwrap();
    let manifest_2 = fs::read_to_string(dir.path().join(manifest::MANIFEST_PATH)).unwrap();
    let md_2 = fs::read_to_string(dir.path().join("docs/reference/cli/commands.md")).unwrap();

    assert_eq!(manifest_1, manifest_2);
    assert_eq!(md_1, md_2);
}

#[test]
fn check_passes_after_generate_and_fails_before() {
    let dir = tempfile::tempdir().unwrap();
    seed(dir.path());
    let check_args = DocsGenerateArgs {
        check: true,
        family: None,
    };
    assert!(run(dir.path(), &check_args).is_err());

    run(
        dir.path(),
        &DocsGenerateArgs {
            check: false,
            family: None,
        },
    )
    .unwrap();
    assert!(run(dir.path(), &check_args).is_ok());
}

#[test]
fn unknown_family_is_rejected() {
    let dir = tempfile::tempdir().unwrap();
    seed(dir.path());
    let args = DocsGenerateArgs {
        check: false,
        family: Some("does-not-exist".to_string()),
    };
    assert!(run(dir.path(), &args).is_err());
}
