use super::*;

#[test]
fn family_slug_parses_schemas_header() {
    let line = "<!-- generated by cargo xtask schemas cli; do not edit directly -->";
    assert_eq!(family_slug(line).as_deref(), Some("cli"));
}

#[test]
fn family_slug_parses_docs_header() {
    let line = "<!-- generated by cargo xtask docs generate --family cli; do not edit directly -->";
    assert_eq!(family_slug(line).as_deref(), Some("cli"));
}

#[test]
fn family_slug_rejects_unrelated_line() {
    assert_eq!(family_slug("# cli Schema Reference"), None);
}

#[test]
fn rewrite_replaces_schemas_header_with_two_line_docs_header() {
    let content = "<!-- generated by cargo xtask schemas cli; do not edit directly -->\n\n# cli Schema Reference\n";
    let out = rewrite(content, "cli", "abc123").unwrap();
    let mut lines = out.lines();
    assert_eq!(
        lines.next().unwrap(),
        "<!-- generated by cargo xtask docs generate --family cli; do not edit directly -->"
    );
    assert_eq!(
        lines.next().unwrap(),
        "<!-- source inputs: sha256:abc123 -->"
    );
    assert_eq!(lines.next().unwrap(), "");
    assert_eq!(lines.next().unwrap(), "# cli Schema Reference");
}

#[test]
fn rewrite_is_idempotent() {
    let content = "<!-- generated by cargo xtask schemas cli; do not edit directly -->\n\n# cli Schema Reference\n";
    let once = rewrite(content, "cli", "abc123").unwrap();
    let twice = rewrite(&once, "cli", "abc123").unwrap();
    assert_eq!(once, twice);
}

#[test]
fn rewrite_rejects_empty_family() {
    assert!(rewrite("# doc", "", "abc").is_err());
}
