//! Generated-doc header parsing/rewriting.
//!
//! Contract header shape (`docs-generator-contract.md` "Generated Header"):
//!
//! ```text
//! <!-- generated by cargo xtask docs <family>; do not edit directly -->
//! <!-- source inputs: <manifest checksum> -->
//! ```

use anyhow::{Result, bail};

const SCHEMAS_PREFIX: &str = "<!-- generated by cargo xtask schemas ";
const DOCS_PREFIX: &str = "<!-- generated by cargo xtask docs generate --family ";
const SUFFIX: &str = "; do not edit directly -->";

/// Extract the family slug from either a `schemas <slug>` header (the form
/// the frozen `schemas generate` writer produces today) or an already
/// rewritten `docs generate --family <slug>` header.
pub fn family_slug(first_line: &str) -> Option<String> {
    if let Some(rest) = first_line
        .strip_prefix(SCHEMAS_PREFIX)
        .and_then(|s| s.strip_suffix(SUFFIX))
    {
        return Some(rest.to_string());
    }
    if let Some(rest) = first_line
        .strip_prefix(DOCS_PREFIX)
        .and_then(|s| s.strip_suffix(SUFFIX))
    {
        return Some(rest.to_string());
    }
    None
}

/// Strip any leading contiguous block of `<!-- ... -->` header comment lines
/// and rebuild the file with the canonical two-line docs header. Idempotent:
/// running this twice on its own output is a no-op.
pub fn rewrite(content: &str, family: &str, manifest_checksum: &str) -> Result<String> {
    if family.is_empty() {
        bail!("docs header rewrite: family slug must not be empty");
    }
    let mut idx = 0;
    let lines: Vec<&str> = content.lines().collect();
    while idx < lines.len() && lines[idx].trim_start().starts_with("<!--") {
        idx += 1;
    }
    let mut out = String::new();
    out.push_str(DOCS_PREFIX);
    out.push_str(family);
    out.push_str(SUFFIX);
    out.push('\n');
    out.push_str(&format!(
        "<!-- source inputs: sha256:{manifest_checksum} -->\n"
    ));
    for line in &lines[idx..] {
        out.push_str(line);
        out.push('\n');
    }
    Ok(out)
}

#[cfg(test)]
#[path = "header_tests.rs"]
mod tests;
