//! REST route registry entries for the `/v1/memory` and `/v1/memories/*` surface.
//!
//! Split out of the parent `schema_registry` module to keep it under the
//! repo's monolith line cap. Spliced back into `rest_route_registry()`'s
//! output in original position by the parent module.

use super::{RestRouteSpec, read, read_query_surface, write};

pub(super) static MEMORY_ROUTES: &[RestRouteSpec] = &[
    write(
        "POST",
        "/v1/memory",
        "memory",
        Some("MemoryRequest"),
        "MemoryResponse",
    ),
    write(
        "POST",
        "/v1/memories",
        "remember_memory",
        Some("MemoryRequest"),
        "MemoryResponse",
    ),
    // U2-20/C6-20: memory search/context default to `axon:read`.
    read_query_surface(
        "POST",
        "/v1/memories/search",
        "search_memories",
        Some("MemoryRequest"),
        "MemoryResponse",
    ),
    read_query_surface(
        "POST",
        "/v1/memories/context",
        "memory_context",
        Some("MemoryRequest"),
        "MemoryResponse",
    ),
    write(
        "POST",
        "/v1/memories/review",
        "review_memories",
        Some("MemoryRequest"),
        "MemoryResponse",
    ),
    write(
        "POST",
        "/v1/memories/compact",
        "compact_memories",
        Some("MemoryRequest"),
        "MemoryResponse",
    ),
    read(
        "GET",
        "/v1/memories/{memory_id}",
        "show_memory",
        "MemoryResponse",
    ),
    write(
        "POST",
        "/v1/memories/{memory_id}/link",
        "link_memory",
        Some("MemoryRequest"),
        "MemoryResponse",
    ),
    write(
        "POST",
        "/v1/memories/{memory_id}/supersede",
        "supersede_memory",
        Some("MemoryRequest"),
        "MemoryResponse",
    ),
    write(
        "POST",
        "/v1/memories/{memory_id}/reinforce",
        "reinforce_memory",
        Some("MemoryRequest"),
        "MemoryResponse",
    ),
    write(
        "POST",
        "/v1/memories/{memory_id}/contradict",
        "contradict_memory",
        Some("MemoryRequest"),
        "MemoryResponse",
    ),
    write(
        "POST",
        "/v1/memories/{memory_id}/pin",
        "pin_memory",
        Some("MemoryRequest"),
        "MemoryResponse",
    ),
    write(
        "POST",
        "/v1/memories/{memory_id}/archive",
        "archive_memory",
        Some("MemoryRequest"),
        "MemoryResponse",
    ),
    write(
        "POST",
        "/v1/memories/{memory_id}/compact",
        "compact_one_memory",
        Some("MemoryRequest"),
        "MemoryResponse",
    ),
    write(
        "DELETE",
        "/v1/memories/{memory_id}",
        "forget_memory",
        None,
        "MemoryResponse",
    ),
    write(
        "POST",
        "/v1/memories/import",
        "import_memories",
        Some("MemoryImportRequest"),
        "MemoryImportResult",
    ),
    write(
        "POST",
        "/v1/memories/export",
        "export_memories",
        Some("MemoryExportRequest"),
        "MemoryExportResult",
    ),
];
