use super::{FieldSpec, env, toml};

pub(crate) const ENV_FIELDS: &[FieldSpec] = &[
    env(
        "Runtime",
        "AXON_SERVER_URL",
        "Palette and CLI REST server URL",
        false,
    ),
    env(
        "Runtime",
        "AXON_MCP_HTTP_TOKEN",
        "Bearer token for Axon HTTP",
        true,
    ),
    env("Runtime", "QDRANT_URL", "Qdrant endpoint", false),
    env("Runtime", "TEI_URL", "TEI embedding endpoint", false),
    env(
        "Runtime",
        "AXON_CHROME_REMOTE_URL",
        "Chrome management endpoint",
        false,
    ),
    env(
        "Runtime",
        "AXON_COLLECTION",
        "Default Qdrant collection",
        false,
    ),
    env("Runtime", "AXON_DATA_DIR", "Axon data directory", false),
    env("Runtime", "AXON_HOME", "Axon home directory", false),
    env("MCP HTTP", "AXON_MCP_HTTP_HOST", "Server bind host", false),
    env("MCP HTTP", "AXON_MCP_HTTP_PORT", "Server bind port", false),
    env("MCP HTTP", "AXON_MCP_AUTH_MODE", "bearer or oauth", false),
    env("MCP HTTP", "AXON_MCP_PUBLIC_URL", "Public OAuth URL", false),
    env(
        "MCP HTTP",
        "AXON_MCP_GOOGLE_CLIENT_ID",
        "Google OAuth client id",
        true,
    ),
    env(
        "MCP HTTP",
        "AXON_MCP_GOOGLE_CLIENT_SECRET",
        "Google OAuth client secret",
        true,
    ),
    env(
        "MCP HTTP",
        "AXON_MCP_AUTH_ADMIN_EMAIL",
        "OAuth admin email",
        false,
    ),
    env(
        "MCP HTTP",
        "AXON_MCP_AUTH_ALLOWED_REDIRECT_URIS",
        "Allowed OAuth redirects",
        false,
    ),
    env(
        "MCP HTTP",
        "AXON_MCP_ALLOWED_ORIGINS",
        "Allowed CORS origins",
        false,
    ),
    env("Secrets", "TAVILY_API_KEY", "Tavily search API key", true),
    env("Secrets", "GITHUB_TOKEN", "GitHub ingest token", true),
    env("Secrets", "REDDIT_CLIENT_ID", "Reddit client id", true),
    env(
        "Secrets",
        "REDDIT_CLIENT_SECRET",
        "Reddit client secret",
        true,
    ),
    env("Secrets", "HF_TOKEN", "Hugging Face token", true),
    env("Gemini", "GEMINI_API_KEY", "Gemini API key", true),
    env(
        "Gemini",
        "GEMINI_HOME",
        "Gemini OAuth home for Docker",
        false,
    ),
    env(
        "Gemini",
        "AXON_HEADLESS_GEMINI_HOME",
        "Source Gemini home",
        false,
    ),
    env(
        "Gemini",
        "AXON_HEADLESS_GEMINI_CMD",
        "Gemini CLI path",
        false,
    ),
    env(
        "Gemini",
        "AXON_HEADLESS_GEMINI_MODEL",
        "Gemini model override",
        false,
    ),
    env("HTTP", "AXON_USER_AGENT", "Default HTTP User-Agent", false),
    env("HTTP", "AXON_CHROME_USER_AGENT", "Chrome User-Agent", false),
    env("Logging", "AXON_LOG_PATH", "Active log file path", false),
];

pub(crate) const TOML_FIELDS: &[FieldSpec] = &[
    toml(
        "Search",
        "search.hybrid-enabled",
        "Enable RRF hybrid search",
    ),
    toml(
        "Search",
        "search.hybrid-candidates",
        "Hybrid candidates per arm",
    ),
    toml(
        "Search",
        "search.ask-hybrid-candidates",
        "Ask hybrid window",
    ),
    toml("Search", "search.hnsw-ef", "Named collection HNSW ef"),
    toml(
        "Search",
        "search.hnsw-ef-legacy",
        "Legacy collection HNSW ef",
    ),
    toml("Ask", "ask.max-context-chars", "LLM context budget"),
    toml("Ask", "ask.chunk-limit", "Chunks returned to ask"),
    toml("Ask", "ask.candidate-limit", "Candidate chunks fetched"),
    toml("Ask", "ask.full-docs", "Full documents in context"),
    toml("Ask", "ask.backfill-chunks", "Backfill chunks per top doc"),
    toml(
        "Ask",
        "ask.doc-fetch-concurrency",
        "Concurrent document fetches",
    ),
    toml("Ask", "ask.doc-chunk-limit", "Chunks per full document"),
    toml("Ask", "ask.min-relevance-score", "Minimum relevance score"),
    toml(
        "Ask",
        "ask.authoritative-domains",
        "Authoritative domains array",
    ),
    toml(
        "Ask",
        "ask.authoritative-boost",
        "Authoritative domain boost",
    ),
    toml("Ask", "ask.min-citations-nontrivial", "Minimum citations"),
    toml("Ask Cache", "ask.cache.enabled", "Enable ask chunk cache"),
    toml(
        "Ask Cache",
        "ask.cache.max-capacity-bytes",
        "Ask cache byte cap",
    ),
    toml("Ask Cache", "ask.cache.ttl-secs", "Ask cache TTL seconds"),
    toml(
        "Ask Adaptive",
        "ask.adaptive.fulldoc-skip-enabled",
        "Full-doc skip gate",
    ),
    toml(
        "Ask Adaptive",
        "ask.adaptive.fulldoc-skip-min-urls",
        "Skip minimum URLs",
    ),
    toml(
        "Ask Adaptive",
        "ask.adaptive.fulldoc-skip-min-chars",
        "Skip minimum chars",
    ),
    toml(
        "Ask Adaptive",
        "ask.adaptive.fulldoc-skip-score-delta",
        "Skip score delta",
    ),
    toml("TEI", "tei.max-retries", "TEI retry attempts"),
    toml("TEI", "tei.request-timeout-ms", "TEI request timeout"),
    toml("TEI", "tei.max-client-batch-size", "TEI client batch size"),
    toml("Workers", "workers.ingest-lanes", "Ingest worker lanes"),
    toml("Workers", "workers.embed-lanes", "Embed worker lanes"),
    toml(
        "Workers",
        "workers.embed-doc-timeout-secs",
        "Embed doc timeout",
    ),
    toml(
        "Workers",
        "workers.queue-summary-secs",
        "Queue summary interval",
    ),
    toml(
        "Workers",
        "workers.qdrant-point-buffer",
        "Qdrant point buffer",
    ),
    toml(
        "Workers",
        "workers.max-pending-crawl-jobs",
        "Crawl queue cap",
    ),
    toml(
        "Workers",
        "workers.max-pending-embed-jobs",
        "Embed queue cap",
    ),
    toml(
        "Workers",
        "workers.max-pending-extract-jobs",
        "Extract queue cap",
    ),
    toml(
        "Workers",
        "workers.max-pending-ingest-jobs",
        "Ingest queue cap",
    ),
    toml("Workers", "workers.job-wait-timeout-secs", "Wait timeout"),
    toml(
        "Workers",
        "workers.concurrency-limit",
        "Global concurrency override",
    ),
    toml(
        "Workers",
        "workers.crawl-concurrency-limit",
        "Crawl concurrency",
    ),
    toml(
        "Workers",
        "workers.backfill-concurrency-limit",
        "Backfill concurrency",
    ),
    toml(
        "Workers",
        "workers.watchdog-stale-timeout-secs",
        "Stale timeout",
    ),
    toml(
        "Workers",
        "workers.watchdog-confirm-secs",
        "Stale confirmation",
    ),
    toml(
        "Workers",
        "workers.watchdog-sweep-secs",
        "Watchdog sweep interval",
    ),
    toml("Chrome", "chrome.user-agent", "Chrome User-Agent"),
    toml("Chrome", "chrome.bypass-csp", "Bypass CSP"),
    toml(
        "Chrome",
        "chrome.accept-invalid-certs",
        "Accept invalid TLS certs",
    ),
    toml(
        "Chrome",
        "chrome.network-idle-timeout-secs",
        "Network idle timeout",
    ),
    toml(
        "Chrome",
        "chrome.bootstrap-timeout-ms",
        "Bootstrap probe timeout",
    ),
    toml(
        "Chrome",
        "chrome.bootstrap-retries",
        "Bootstrap probe retries",
    ),
    toml("Scrape", "scrape.respect-robots", "Respect robots.txt"),
];
